export function buildAdminFiles(): Record<string, string> {
  return {
    // --- requireAdmin (FR-14, Story 5.1) — porta simples, checagem pura sobre ctx.user ---
    // (isAdmin já vem decodificado do JWT, nenhuma consulta a banco aqui dentro — ver
    // Dev Notes da story: diferente de requireResource, que consulta Resource/
    // RoleAssignment porque autorização por Módulo/Recurso MUDA sem reemissão de
    // token; isAdmin é re-derivado a cada refresh, então o claim já é confiável).
    'src/core/admin/require-admin.ts': [
      "import { TRPCError } from '@trpc/server';",
      "import { middleware } from '../../trpc.js';",
      '',
      '// Default-deny: UNAUTHORIZED se não autenticado, FORBIDDEN se autenticado mas',
      '// não-admin — nunca confunde os dois casos (mesmo rigor de requireResource).',
      '// isAdmin é escopado ao próprio tenant do usuário (nunca um superusuário',
      '// cross-tenant) — `ctx.user.tenantId` já é a fronteira usada por',
      '// `admin.users.*` via `forTenant`.',
      'export function requireAdmin() {',
      '  return middleware(async ({ ctx, next }) => {',
      '    if (!ctx.user) {',
      "      throw new TRPCError({ code: 'UNAUTHORIZED' });",
      '    }',
      '    if (!ctx.user.isAdmin) {',
      "      throw new TRPCError({ code: 'FORBIDDEN' });",
      '    }',
      '    // Reatribui ctx.user explicitamente — por este ponto TS já estreitou seu',
      '    // tipo (não-undefined) dentro desta função; repassar assim pro `next()`',
      '    // propaga esse estreitamento pros procedures downstream (ctx.user.tenantId',
      '    // sem non-null assertion), mesmo truque já usado em requireResource.',
      '    return next({ ctx: { ...ctx, user: ctx.user } });',
      '  });',
      '}',
      '',
    ].join('\n'),

    'src/core/admin/require-admin.test.ts': [
      "import { describe, it, expect } from 'vitest';",
      "import { requireAdmin } from './require-admin.js';",
      "import { router, publicProcedure } from '../../trpc.js';",
      "import { createTestContext } from '../../test-utils.js';",
      '',
      '// Mesmo padrão de require-resource.test.ts (Story 3.1) — não reimplementa a',
      '// chamada do middleware, exercita através do jeito real de invocar tRPC.',
      'function callProtected(ctx: ReturnType<typeof createTestContext>) {',
      '  const testRouter = router({',
      '    check: publicProcedure',
      '      .use(requireAdmin())',
      "      .query(() => 'ok' as const),",
      '  });',
      '  return testRouter.createCaller(ctx).check();',
      '}',
      '',
      "describe('requireAdmin', () => {",
      "  it('sem ctx.user é UNAUTHORIZED', async () => {",
      '    const ctx = createTestContext();',
      '',
      '    await expect(callProtected(ctx)).rejects.toMatchObject({',
      "      code: 'UNAUTHORIZED',",
      '    });',
      '  });',
      '',
      "  it('autenticado mas isAdmin: false é FORBIDDEN', async () => {",
      '    const ctx = createTestContext({',
      "      user: { userId: 'user-1', tenantId: 'tenant-1', isAdmin: false },",
      '    });',
      '',
      '    await expect(callProtected(ctx)).rejects.toMatchObject({',
      "      code: 'FORBIDDEN',",
      '    });',
      '  });',
      '',
      "  it('autenticado com isAdmin: true passa', async () => {",
      '    const ctx = createTestContext({',
      "      user: { userId: 'user-1', tenantId: 'tenant-1', isAdmin: true },",
      '    });',
      '',
      "    await expect(callProtected(ctx)).resolves.toBe('ok');",
      '  });',
      '});',
      '',
    ].join('\n'),

    // --- adminRouter.users (FR-14 parcial, Story 5.1) — CRUD backend, sem tela ainda ---
    // (ver Dev Notes da story: convenção de UI pras telas de admin ainda em aberto).
    'src/core/admin/router.ts': [
      "import { TRPCError } from '@trpc/server';",
      "import { randomBytes } from 'node:crypto';",
      "import { forTenant } from 'db/extensions/tenant';",
      'import {',
      '  listUsersOutputSchema,',
      '  createUserInputSchema,',
      '  updateUserInputSchema,',
      '  revokeSessionsInputSchema,',
      '  listGroupsOutputSchema,',
      '  createGroupInputSchema,',
      '  updateGroupInputSchema,',
      '  deleteGroupInputSchema,',
      '  listRolesOutputSchema,',
      '  createRoleInputSchema,',
      '  updateRoleInputSchema,',
      '  deleteRoleInputSchema,',
      "} from 'shared/schemas/admin';",
      "import { publicProcedure, router } from '../../trpc.js';",
      "import { requireAdmin } from './require-admin.js';",
      '',
      '// Reaproveita o MESMO PasswordResetTokenStore da Story 4.2, só com um propósito',
      '// diferente (configurar a primeira senha, não redefinir uma existente).',
      '// Constante própria (não importada de auth/router.ts) — mesmo valor de HOJE que',
      '// PASSWORD_RESET_TOKEN_TTL_MS por coincidência, mas deliberadamente um knob',
      '// independente: "quanto tempo um admin recém-criado tem pra configurar a senha"',
      '// é uma decisão de produto separada de "quanto tempo um link de esqueci-minha-',
      '// senha dura", e as duas podem divergir no futuro sem acoplamento nenhum.',
      'const ACCOUNT_SETUP_TOKEN_TTL_MS = 60 * 60 * 1000;',
      '',
      "// 'P2002' (unique constraint, aqui sempre @@unique([tenantId, email])) é o único",
      '// jeito de db.user.create()/updateMany() falharem por entrada do próprio admin —',
      '// nunca deixa vazar como 500 bruto (mesma disciplina anti-500-não-mapeado já',
      '// aplicada em todo o resto do projeto desde a Story 2.1). Checagem estrutural',
      "// (não `instanceof Prisma.PrismaClientKnownRequestError`) — apps/api não",
      '// depende de `@prisma/client` diretamente (só de `db`, workspace:*), e o',
      "// formato `{ code: string }` de erro do Prisma é estável entre versões.",
      'function isDuplicateEmailError(err: unknown): boolean {',
      '  return (',
      "    typeof err === 'object' && err !== null && 'code' in err && err.code === 'P2002'",
      '  );',
      '}',
      '',
      "// 'P2003' (violação de FK) — role_assignments_role_id_fkey é ON DELETE",
      '// RESTRICT (Story 3.1, diferente de role_assignments_group_id_fkey, que',
      '// É CASCADE): excluir um Role ainda atribuído a alguém tem que falhar',
      '// com um erro de PRODUTO (CONFLICT), nunca o P2003 bruto do Postgres.',
      '// Mesma checagem estrutural de isDuplicateEmailError acima.',
      'function isRoleInUseError(err: unknown): boolean {',
      '  return (',
      "    typeof err === 'object' && err !== null && 'code' in err && err.code === 'P2003'",
      '  );',
      '}',
      '',
      'export const adminRouter = router({',
      '  users: router({',
      '    list: publicProcedure',
      '      .use(requireAdmin())',
      '      .output(listUsersOutputSchema)',
      '      .query(async ({ ctx }) => {',
      '        // forTenant (AD-5) — um admin só vê o PRÓPRIO tenant, nunca cross-tenant',
      '        // (não é um superusuário de plataforma).',
      '        const db = forTenant(ctx.user.tenantId);',
      '        return db.user.findMany({',
      '          select: { id: true, email: true, isAdmin: true, createdAt: true },',
      '        });',
      '      }),',
      '',
      '    create: publicProcedure',
      '      .use(requireAdmin())',
      '      .input(createUserInputSchema)',
      '      .mutation(async ({ input, ctx }) => {',
      '        const { tenantId } = ctx.user;',
      '        // Nunca uma senha real (AC #5) — hash de um valor aleatório de alta',
      '        // entropia via a MESMA função já usada em todo o resto do projeto',
      '        // (AuthProvider.hash), garantindo um Argon2id válido que ninguém',
      '        // conhece/pode usar até a configuração real via resetPassword.',
      '        const passwordHash = await ctx.authProvider.hash(',
      "          randomBytes(32).toString('base64url'),",
      '        );',
      '        const db = forTenant(tenantId);',
      '        let user: { id: string };',
      '        try {',
      '          user = await db.user.create({',
      '            data: { tenantId, email: input.email, passwordHash },',
      '            select: { id: true },',
      '          });',
      '        } catch (err) {',
      '          if (isDuplicateEmailError(err)) {',
      '            throw new TRPCError({',
      "              code: 'CONFLICT',",
      "              message: 'Já existe um usuário com este email.',",
      '            });',
      '          }',
      '          throw err;',
      '        }',
      '',
      '        // MESMO PasswordResetTokenStore/mecanismo da Story 4.2, reaproveitado',
      '        // sem modificação — só o template do email muda (account-setup).',
      '        try {',
      '          const rawToken = await ctx.passwordResetTokenStore.issue(',
      '            user.id,',
      '            tenantId,',
      '            new Date(Date.now() + ACCOUNT_SETUP_TOKEN_TTL_MS),',
      '          );',
      '          const setupLink = `${process.env.WEB_PUBLIC_URL ?? \'http://localhost:5173\'}/account-setup?token=${rawToken}`;',
      '          await ctx.emailProvider.send({',
      "            template: 'account-setup',",
      '            to: input.email,',
      '            data: {',
      '              setupLink,',
      '              expiresInMinutes: ACCOUNT_SETUP_TOKEN_TTL_MS / 60_000,',
      '            },',
      '          });',
      '        } catch (err) {',
      '          // Diferente de requestPasswordReset (Story 4.2), que PRECISA engolir',
      '          // esse mesmo tipo de falha pra não vazar enumeração de email — aqui',
      '          // não existe essa restrição (o admin já sabe que acabou de pedir a',
      '          // criação). Desfaz o User recém-criado (achado do code review: sem',
      '          // isso, ficaria uma linha órfã com senha placeholder inutilizável e',
      '          // nenhum email jamais entregue, e uma nova tentativa falharia de novo,',
      '          // agora por email duplicado) e relança um erro claro — nunca devolve',
      '          // sucesso quando o setup não pode ser concluído.',
      '          await db.user',
      '            .delete({ where: { id: user.id } })',
      '            .catch(() => undefined);',
      '          throw err;',
      '        }',
      '      }),',
      '',
      '    update: publicProcedure',
      '      .use(requireAdmin())',
      '      .input(updateUserInputSchema)',
      '      .mutation(async ({ input, ctx }) => {',
      '        const db = forTenant(ctx.user.tenantId);',
      '        // updateMany (não update) — nunca confirma/nega cross-tenant via o',
      '        // formato do erro (P2025 vs. "0 linhas afetadas"); updateMany sempre',
      '        // retorna { count }, nunca lança por "não encontrado".',
      '        let result: { count: number };',
      '        try {',
      '          result = await db.user.updateMany({',
      '            where: { id: input.userId },',
      '            data: { email: input.email },',
      '          });',
      '        } catch (err) {',
      '          if (isDuplicateEmailError(err)) {',
      '            throw new TRPCError({',
      "              code: 'CONFLICT',",
      "              message: 'Já existe um usuário com este email.',",
      '            });',
      '          }',
      '          throw err;',
      '        }',
      '        if (result.count === 0) {',
      '          throw new TRPCError({',
      "            code: 'NOT_FOUND',",
      "            message: 'Usuário não encontrado.',",
      '          });',
      '        }',
      '      }),',
      '',
      '    revokeSessions: publicProcedure',
      '      .use(requireAdmin())',
      '      .input(revokeSessionsInputSchema)',
      '      .mutation(async ({ input, ctx }) => {',
      '        // Bloqueia auto-revogação (Story 5.2, achado do code review + decisão',
      '        // do Boss) — sem isso, um admin que passasse o próprio userId se',
      '        // trancaria fora por engano. "Sair de todos os outros dispositivos"',
      '        // fica pra uma story futura dedicada, se vier a ser pedido.',
      '        if (input.userId === ctx.user.userId) {',
      '          throw new TRPCError({',
      "            code: 'BAD_REQUEST',",
      "            message: 'Não é possível revogar as próprias sessões.',",
      '          });',
      '        }',
      '        const db = forTenant(ctx.user.tenantId);',
      '        // Confirma posse do tenant ANTES de revogar (Story 5.2) —',
      '        // `TokenRevocationStore.revokeAllForUser` é tenant-agnóstico na própria',
      '        // assinatura (só `userId`); a fronteira de tenant É responsabilidade',
      '        // desta procedure, nunca do store. Mesmo princípio anti-enumeração',
      '        // cross-tenant de `update` acima — NOT_FOUND tanto pra "não existe"',
      '        // quanto pra "existe mas é de outro tenant".',
      '        const target = await db.user.findUnique({',
      '          where: { id: input.userId },',
      '          select: { id: true },',
      '        });',
      '        if (!target) {',
      '          throw new TRPCError({',
      "            code: 'NOT_FOUND',",
      "            message: 'Usuário não encontrado.',",
      '          });',
      '        }',
      '        // MESMO TokenRevocationStore/mecanismo da Story 2.1/4.2, reaproveitado',
      '        // sem modificação.',
      '        await ctx.tokenRevocationStore.revokeAllForUser(input.userId);',
      '      }),',
      '  }),',
      '',
      '  // Story 5.3 — mesmo padrão de `users` acima (forTenant, updateMany/deleteMany',
      '  // + count===0 → NOT_FOUND). `delete` nunca limpa RoleAssignment/associação',
      '  // User↔Group manualmente — a FK ON DELETE CASCADE (Story 3.1) já faz isso.',
      '  groups: router({',
      '    list: publicProcedure',
      '      .use(requireAdmin())',
      '      .output(listGroupsOutputSchema)',
      '      .query(async ({ ctx }) => {',
      '        const db = forTenant(ctx.user.tenantId);',
      '        return db.group.findMany({',
      '          select: { id: true, name: true, createdAt: true },',
      '        });',
      '      }),',
      '',
      '    create: publicProcedure',
      '      .use(requireAdmin())',
      '      .input(createGroupInputSchema)',
      '      .mutation(async ({ input, ctx }) => {',
      '        const { tenantId } = ctx.user;',
      '        const db = forTenant(tenantId);',
      '        await db.group.create({',
      '          data: { tenantId, name: input.name },',
      '        });',
      '      }),',
      '',
      '    update: publicProcedure',
      '      .use(requireAdmin())',
      '      .input(updateGroupInputSchema)',
      '      .mutation(async ({ input, ctx }) => {',
      '        const db = forTenant(ctx.user.tenantId);',
      '        const result = await db.group.updateMany({',
      '          where: { id: input.groupId },',
      '          data: { name: input.name },',
      '        });',
      '        if (result.count === 0) {',
      '          throw new TRPCError({',
      "            code: 'NOT_FOUND',",
      "            message: 'Grupo não encontrado.',",
      '          });',
      '        }',
      '      }),',
      '',
      '    delete: publicProcedure',
      '      .use(requireAdmin())',
      '      .input(deleteGroupInputSchema)',
      '      .mutation(async ({ input, ctx }) => {',
      '        const db = forTenant(ctx.user.tenantId);',
      '        const result = await db.group.deleteMany({',
      '          where: { id: input.groupId },',
      '        });',
      '        if (result.count === 0) {',
      '          throw new TRPCError({',
      "            code: 'NOT_FOUND',",
      "            message: 'Grupo não encontrado.',",
      '          });',
      '        }',
      '      }),',
      '  }),',
      '',
      '  // Story 5.4 — mesmo padrão de `groups` acima, exceto `delete`: diferente',
      '  // de Group, role_assignments_role_id_fkey é ON DELETE RESTRICT (não',
      '  // CASCADE) — excluir um Role em uso tem que responder CONFLICT, nunca',
      '  // deixar o P2003 do Postgres vazar cru (ver Dev Notes da story).',
      '  roles: router({',
      '    list: publicProcedure',
      '      .use(requireAdmin())',
      '      .output(listRolesOutputSchema)',
      '      .query(async ({ ctx }) => {',
      '        const db = forTenant(ctx.user.tenantId);',
      '        return db.role.findMany({',
      '          select: { id: true, name: true, createdAt: true },',
      '        });',
      '      }),',
      '',
      '    create: publicProcedure',
      '      .use(requireAdmin())',
      '      .input(createRoleInputSchema)',
      '      .mutation(async ({ input, ctx }) => {',
      '        const { tenantId } = ctx.user;',
      '        const db = forTenant(tenantId);',
      '        await db.role.create({',
      '          data: { tenantId, name: input.name },',
      '        });',
      '      }),',
      '',
      '    update: publicProcedure',
      '      .use(requireAdmin())',
      '      .input(updateRoleInputSchema)',
      '      .mutation(async ({ input, ctx }) => {',
      '        const db = forTenant(ctx.user.tenantId);',
      '        const result = await db.role.updateMany({',
      '          where: { id: input.roleId },',
      '          data: { name: input.name },',
      '        });',
      '        if (result.count === 0) {',
      '          throw new TRPCError({',
      "            code: 'NOT_FOUND',",
      "            message: 'Papel não encontrado.',",
      '          });',
      '        }',
      '      }),',
      '',
      '    delete: publicProcedure',
      '      .use(requireAdmin())',
      '      .input(deleteRoleInputSchema)',
      '      .mutation(async ({ input, ctx }) => {',
      '        const db = forTenant(ctx.user.tenantId);',
      '        let result: { count: number };',
      '        try {',
      '          result = await db.role.deleteMany({',
      '            where: { id: input.roleId },',
      '          });',
      '        } catch (err) {',
      '          if (isRoleInUseError(err)) {',
      '            throw new TRPCError({',
      "              code: 'CONFLICT',",
      '              message:',
      "                'Papel ainda está atribuído a Usuários/Grupos — remova as atribuições antes de excluir.',",
      '            });',
      '          }',
      '          throw err;',
      '        }',
      '        if (result.count === 0) {',
      '          throw new TRPCError({',
      "            code: 'NOT_FOUND',",
      "            message: 'Papel não encontrado.',",
      '          });',
      '        }',
      '      }),',
      '  }),',
      '});',
      '',
    ].join('\n'),

    'src/core/admin/router.test.ts': [
      "import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';",
      "import { prisma } from 'db/client';",
      "import { adminRouter } from './router.js';",
      "import { createTestContext } from '../../test-utils.js';",
      '',
      '// admin.users.* usa forTenant direto (não injetado via ctx, mesmo padrão de',
      '// repository.ts de módulo gerado) — não dá pra fakear sem um Postgres real',
      '// por trás. DATABASE_URL-gated, mesma convenção do Épico 3 (diferente do',
      '// resto de core/auth, que é fake-only — ver Dev Notes da story).',
      'describe.skipIf(!process.env.DATABASE_URL)(',
      "  'adminRouter.users (integração real, precisa de DATABASE_URL)',",
      '  () => {',
      '    let tenantId: string;',
      '    let createdTenantIds: string[];',
      '',
      '    async function cleanupTenant(id: string) {',
      '      // refreshToken ANTES de user (Story 5.2: users.revokeSessions emite',
      '      // refresh tokens reais nos testes) — FK é ON DELETE RESTRICT, mesmo',
      '      // achado já visto na validação real da Story 5.1.',
      '      await prisma.refreshToken.deleteMany({ where: { tenantId: id } });',
      '      await prisma.passwordResetToken.deleteMany({ where: { tenantId: id } });',
      '      // roleAssignment/role ANTES de group (Story 5.3: o teste de CASCADE cria',
      '      // RoleAssignment/Role reais) — roles_tenant_id_fkey/groups_tenant_id_fkey',
      '      // também são RESTRICT. Module é GLOBAL (Story 3.1) — não tem tenantId,',
      '      // cada teste que cria um limpa o próprio Module explicitamente.',
      '      await prisma.roleAssignment.deleteMany({ where: { tenantId: id } });',
      '      await prisma.role.deleteMany({ where: { tenantId: id } });',
      '      await prisma.group.deleteMany({ where: { tenantId: id } });',
      '      await prisma.user.deleteMany({ where: { tenantId: id } });',
      '      await prisma.tenant.delete({ where: { id } });',
      '    }',
      '',
      '    beforeEach(async () => {',
      '      const tenant = await prisma.tenant.create({',
      '        data: { name: `tenant-${Date.now()}-${Math.random()}` },',
      '      });',
      '      tenantId = tenant.id;',
      '      createdTenantIds = [tenantId];',
      '    });',
      '',
      '    afterEach(async () => {',
      '      for (const id of createdTenantIds) {',
      '        await cleanupTenant(id);',
      '      }',
      '    });',
      '',
      '    function makeAdminCtx(overrides: Record<string, unknown> = {}) {',
      '      return createTestContext({',
      "        user: { userId: 'admin-user', tenantId, isAdmin: true },",
      '        ...overrides,',
      '      });',
      '    }',
      '',
      "    it('users.list retorna só os Users do próprio tenant do admin, nunca cross-tenant (AC #4, AD-5)', async () => {",
      '      await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `a-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '      const otherTenant = await prisma.tenant.create({',
      '        data: { name: `tenant-b-${Date.now()}-${Math.random()}` },',
      '      });',
      '      createdTenantIds.push(otherTenant.id);',
      '      await prisma.user.create({',
      '        data: {',
      '          tenantId: otherTenant.id,',
      '          email: `b-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '',
      '      const result = await adminRouter',
      '        .createCaller(makeAdminCtx())',
      '        .users.list();',
      '',
      '      expect(result).toHaveLength(1);',
      "      expect(result[0]?.email.startsWith('a-')).toBe(true);",
      "      expect(result[0]).not.toHaveProperty('passwordHash');",
      '    });',
      '',
      "    it('users.list rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).users.list(),',
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      '    // users.create/users.update usam o MESMO requireAdmin() de users.list — mas',
      '    // nada confirmava que o guard estava de fato conectado nos outros dois',
      '    // (achado do code review: só a lógica do middleware em si, isolada em',
      '    // require-admin.test.ts, tinha cobertura).',
      "    it('users.create rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).users.create({',
      "          email: 'nao-deveria-criar@example.com',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('users.update rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const user = await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `nao-admin-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).users.update({',
      '          userId: user.id,',
      "          email: 'nao-deveria-editar@example.com',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('users.create nunca aceita senha no input, emite token via PasswordResetTokenStore e envia email account-setup (AC #5)', async () => {",
      '      const emailProvider = { send: vi.fn(async () => undefined) };',
      '      const passwordResetTokenStore = {',
      "        issue: vi.fn(async () => 'raw-setup-token'),",
      '        consume: vi.fn(async () => null),',
      '      };',
      '      const ctx = makeAdminCtx({ emailProvider, passwordResetTokenStore });',
      '',
      '      await adminRouter.createCaller(ctx).users.create({',
      "        email: 'novo-usuario@example.com',",
      '      });',
      '',
      '      const created = await prisma.user.findUnique({',
      '        where: {',
      "          tenantId_email: { tenantId, email: 'novo-usuario@example.com' },",
      '        },',
      '      });',
      '      expect(created).not.toBeNull();',
      '      expect(passwordResetTokenStore.issue).toHaveBeenCalledWith(',
      '        created?.id,',
      '        tenantId,',
      '        expect.any(Date),',
      '      );',
      '      expect(emailProvider.send).toHaveBeenCalledWith({',
      "        template: 'account-setup',",
      "        to: 'novo-usuario@example.com',",
      '        data: {',
      "          setupLink: expect.stringContaining('raw-setup-token'),",
      '          expiresInMinutes: expect.any(Number),',
      '        },',
      '      });',
      '    });',
      '',
      "    it('users.create retorna CONFLICT se o email já existe no tenant, em vez de vazar o erro bruto do Prisma (achado do code review)', async () => {",
      '      await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      "          email: 'ja-existe@example.com',",
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).users.create({',
      "          email: 'ja-existe@example.com',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'CONFLICT' });",
      '    });',
      '',
      "    it('users.create desfaz o User recém-criado se o envio do email account-setup falhar, sem deixar linha órfã (achado do code review)', async () => {",
      '      const emailProvider = {',
      "        send: vi.fn(async () => { throw new Error('Mailpit fora do ar'); }),",
      '      };',
      '      const passwordResetTokenStore = {',
      "        issue: vi.fn(async () => 'raw-setup-token'),",
      '        consume: vi.fn(async () => null),',
      '      };',
      '      const ctx = makeAdminCtx({ emailProvider, passwordResetTokenStore });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).users.create({',
      "          email: 'vai-falhar@example.com',",
      '        }),',
      "      ).rejects.toThrow('Mailpit fora do ar');",
      '',
      '      const orphan = await prisma.user.findUnique({',
      '        where: {',
      "          tenantId_email: { tenantId, email: 'vai-falhar@example.com' },",
      '        },',
      '      });',
      '      expect(orphan).toBeNull();',
      '    });',
      '',
      "    it('users.update edita o email de um User do próprio tenant (AC #6)', async () => {",
      '      const user = await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `old-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '',
      '      await adminRouter.createCaller(makeAdminCtx()).users.update({',
      '        userId: user.id,',
      "        email: 'email-novo@example.com',",
      '      });',
      '',
      '      const updated = await prisma.user.findUnique({',
      '        where: { id: user.id },',
      '      });',
      "      expect(updated?.email).toBe('email-novo@example.com');",
      '    });',
      '',
      "    it('users.update retorna CONFLICT se o novo email já pertence a outro User do mesmo tenant (achado do code review)', async () => {",
      '      await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      "          email: 'ja-existe-2@example.com',",
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '      const user = await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `original-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).users.update({',
      '          userId: user.id,',
      "          email: 'ja-existe-2@example.com',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'CONFLICT' });",
      '    });',
      '',
      "    it('users.update nunca cruza tenant — NOT_FOUND pra um User de outro tenant (AD-5)', async () => {",
      '      const otherTenant = await prisma.tenant.create({',
      '        data: { name: `tenant-c-${Date.now()}-${Math.random()}` },',
      '      });',
      '      createdTenantIds.push(otherTenant.id);',
      '      const otherUser = await prisma.user.create({',
      '        data: {',
      '          tenantId: otherTenant.id,',
      '          email: `c-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).users.update({',
      '          userId: otherUser.id,',
      "          email: 'hacked@example.com',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'NOT_FOUND' });",
      '    });',
      '',
      "    it('users.revokeSessions rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const user = await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `revoke-forbidden-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).users.revokeSessions({',
      '          userId: user.id,',
      '        }),',
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('users.revokeSessions nunca cruza tenant — NOT_FOUND pra um User de outro tenant (AD-5)', async () => {",
      '      const otherTenant = await prisma.tenant.create({',
      '        data: { name: `tenant-d-${Date.now()}-${Math.random()}` },',
      '      });',
      '      createdTenantIds.push(otherTenant.id);',
      '      const otherUser = await prisma.user.create({',
      '        data: {',
      '          tenantId: otherTenant.id,',
      '          email: `d-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).users.revokeSessions({',
      '          userId: otherUser.id,',
      '        }),',
      "      ).rejects.toMatchObject({ code: 'NOT_FOUND' });",
      '    });',
      '',
      "    it('users.revokeSessions com userId inexistente também é NOT_FOUND, mesma resposta (AD-5, anti-enumeração)', async () => {",
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).users.revokeSessions({',
      "          userId: 'id-que-nunca-existiu',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'NOT_FOUND' });",
      '    });',
      '',
      "    it('users.revokeSessions revoga de verdade — um refresh token real emitido antes passa a reportar isRevoked (AC #4, efeito real não spy)', async () => {",
      '      const user = await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `revoke-real-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '      const ctx = makeAdminCtx();',
      '      const rawRefreshToken = await ctx.tokenRevocationStore.issue(',
      '        { userId: user.id, tenantId },',
      '        new Date(Date.now() + 1000 * 60 * 60),',
      '      );',
      '      expect(await ctx.tokenRevocationStore.isRevoked(rawRefreshToken)).toBe(',
      '        false,',
      '      );',
      '',
      '      await adminRouter.createCaller(ctx).users.revokeSessions({',
      '        userId: user.id,',
      '      });',
      '',
      '      expect(await ctx.tokenRevocationStore.isRevoked(rawRefreshToken)).toBe(',
      '        true,',
      '      );',
      '    });',
      '',
      "    it('users.revokeSessions nunca afeta outro User do MESMO tenant — só o userId pedido é revogado (achado do code review)', async () => {",
      '      const userA = await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `revoke-a-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '      const userB = await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `revoke-b-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '      const ctx = makeAdminCtx();',
      '      const tokenA = await ctx.tokenRevocationStore.issue(',
      '        { userId: userA.id, tenantId },',
      '        new Date(Date.now() + 1000 * 60 * 60),',
      '      );',
      '      const tokenB = await ctx.tokenRevocationStore.issue(',
      '        { userId: userB.id, tenantId },',
      '        new Date(Date.now() + 1000 * 60 * 60),',
      '      );',
      '',
      '      await adminRouter.createCaller(ctx).users.revokeSessions({',
      '        userId: userA.id,',
      '      });',
      '',
      '      expect(await ctx.tokenRevocationStore.isRevoked(tokenA)).toBe(true);',
      '      expect(await ctx.tokenRevocationStore.isRevoked(tokenB)).toBe(false);',
      '    });',
      '',
      "    it('users.revokeSessions bloqueia auto-revogação do próprio admin (BAD_REQUEST, decisão do Boss no code review)', async () => {",
      '      const ctx = makeAdminCtx();',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).users.revokeSessions({',
      "          userId: 'admin-user',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'BAD_REQUEST' });",
      '    });',
      '',
      "    it('groups.list rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).groups.list(),',
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('groups.create rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      "        adminRouter.createCaller(ctx).groups.create({ name: 'novo' }),",
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('groups.update rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const group = await prisma.group.create({',
      '        data: { tenantId, name: `grupo-forbidden-update-${Date.now()}` },',
      '      });',
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).groups.update({',
      '          groupId: group.id,',
      "          name: 'editado',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('groups.delete rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const group = await prisma.group.create({',
      '        data: { tenantId, name: `grupo-forbidden-delete-${Date.now()}` },',
      '      });',
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).groups.delete({',
      '          groupId: group.id,',
      '        }),',
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('groups.list retorna só os Groups do próprio tenant do admin, nunca cross-tenant (AD-5)', async () => {",
      '      await prisma.group.create({',
      '        data: { tenantId, name: `grupo-a-${Date.now()}` },',
      '      });',
      '      const otherTenant = await prisma.tenant.create({',
      '        data: { name: `tenant-e-${Date.now()}-${Math.random()}` },',
      '      });',
      '      createdTenantIds.push(otherTenant.id);',
      '      await prisma.group.create({',
      '        data: { tenantId: otherTenant.id, name: `grupo-b-${Date.now()}` },',
      '      });',
      '',
      '      const result = await adminRouter',
      '        .createCaller(makeAdminCtx())',
      '        .groups.list();',
      '',
      '      expect(result).toHaveLength(1);',
      "      expect(result[0]?.name.startsWith('grupo-a-')).toBe(true);",
      '    });',
      '',
      "    it('groups.create cria de verdade um Group no tenant do admin', async () => {",
      '      await adminRouter.createCaller(makeAdminCtx()).groups.create({',
      "        name: 'Suporte',",
      '      });',
      '',
      '      const created = await prisma.group.findFirst({',
      "        where: { tenantId, name: 'Suporte' },",
      '      });',
      '      expect(created).not.toBeNull();',
      '    });',
      '',
      "    it('groups.update edita o name de um Group do próprio tenant', async () => {",
      '      const group = await prisma.group.create({',
      '        data: { tenantId, name: `grupo-old-${Date.now()}` },',
      '      });',
      '',
      '      await adminRouter.createCaller(makeAdminCtx()).groups.update({',
      '        groupId: group.id,',
      "        name: 'Grupo Renomeado',",
      '      });',
      '',
      '      const updated = await prisma.group.findUnique({',
      '        where: { id: group.id },',
      '      });',
      "      expect(updated?.name).toBe('Grupo Renomeado');",
      '    });',
      '',
      "    it('groups.update/groups.delete nunca cruzam tenant — NOT_FOUND uniforme pra outro tenant E pra groupId inexistente (AD-5)', async () => {",
      '      const otherTenant = await prisma.tenant.create({',
      '        data: { name: `tenant-f-${Date.now()}-${Math.random()}` },',
      '      });',
      '      createdTenantIds.push(otherTenant.id);',
      '      const otherGroup = await prisma.group.create({',
      '        data: { tenantId: otherTenant.id, name: `grupo-f-${Date.now()}` },',
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).groups.update({',
      '          groupId: otherGroup.id,',
      "          name: 'hacked',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'NOT_FOUND' });",
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).groups.delete({',
      '          groupId: otherGroup.id,',
      '        }),',
      "      ).rejects.toMatchObject({ code: 'NOT_FOUND' });",
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).groups.update({',
      "          groupId: 'id-que-nunca-existiu',",
      "          name: 'hacked',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'NOT_FOUND' });",
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).groups.delete({',
      "          groupId: 'id-que-nunca-existiu',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'NOT_FOUND' });",
      '    });',
      '',
      "    it('groups.delete remove de verdade um Group vazio do próprio tenant', async () => {",
      '      const group = await prisma.group.create({',
      '        data: { tenantId, name: `grupo-del-${Date.now()}` },',
      '      });',
      '',
      '      await adminRouter.createCaller(makeAdminCtx()).groups.delete({',
      '        groupId: group.id,',
      '      });',
      '',
      '      expect(',
      '        await prisma.group.findUnique({ where: { id: group.id } }),',
      '      ).toBeNull();',
      '    });',
      '',
      "    it('groups.delete limpa RoleAssignment e associação User↔Group via CASCADE — sem este código tocar nelas (AC #6, efeito real não suposição)', async () => {",
      '      const module = await prisma.module.create({',
      '        data: {',
      '          slug: `modulo-cascade-${Date.now()}`,',
      "          name: 'Módulo de teste do CASCADE',",
      '        },',
      '      });',
      '      const role = await prisma.role.create({',
      '        data: { tenantId, name: `role-cascade-${Date.now()}` },',
      '      });',
      '      const user = await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `membro-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '      const group = await prisma.group.create({',
      '        data: {',
      '          tenantId,',
      '          name: `grupo-cascade-${Date.now()}`,',
      '          users: { connect: { id: user.id } },',
      '        },',
      '      });',
      '      const roleAssignment = await prisma.roleAssignment.create({',
      '        data: {',
      '          tenantId,',
      '          groupId: group.id,',
      '          roleId: role.id,',
      '          targetModuleId: module.id,',
      '        },',
      '      });',
      '',
      '      try {',
      '        await adminRouter.createCaller(makeAdminCtx()).groups.delete({',
      '          groupId: group.id,',
      '        });',
      '',
      '        expect(',
      '          await prisma.group.findUnique({ where: { id: group.id } }),',
      '        ).toBeNull();',
      '        expect(',
      '          await prisma.roleAssignment.findUnique({',
      '            where: { id: roleAssignment.id },',
      '          }),',
      '        ).toBeNull();',
      '        const userAfter = await prisma.user.findUnique({',
      '          where: { id: user.id },',
      '          include: { groups: true },',
      '        });',
      '        expect(userAfter).not.toBeNull();',
      '        expect(userAfter?.groups).toHaveLength(0);',
      '      } finally {',
      '        // try/finally (achado do code review) — Module é GLOBAL (sem',
      '        // tenantId), nunca tocado pelo cleanupTenant/afterEach; sem isso,',
      '        // uma asserção falhando antes daqui vazaria a linha pra sempre.',
      '        // `role` NÃO precisa de limpeza manual — cleanupTenant já tem',
      '        // `role.deleteMany({ where: { tenantId } })` desde este mesmo diff.',
      '        await prisma.module',
      '          .delete({ where: { id: module.id } })',
      '          .catch(() => undefined);',
      '      }',
      '    });',
      '',
      "    it('roles.list rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).roles.list(),',
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('roles.create rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      "        adminRouter.createCaller(ctx).roles.create({ name: 'novo' }),",
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('roles.update rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const role = await prisma.role.create({',
      '        data: { tenantId, name: `role-forbidden-update-${Date.now()}` },',
      '      });',
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).roles.update({',
      '          roleId: role.id,',
      "          name: 'editado',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('roles.delete rejeita sem isAdmin (FORBIDDEN)', async () => {",
      '      const role = await prisma.role.create({',
      '        data: { tenantId, name: `role-forbidden-delete-${Date.now()}` },',
      '      });',
      '      const ctx = createTestContext({',
      "        user: { userId: 'user-1', tenantId, isAdmin: false },",
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(ctx).roles.delete({',
      '          roleId: role.id,',
      '        }),',
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('roles.list retorna só os Roles do próprio tenant do admin, nunca cross-tenant (AD-5)', async () => {",
      '      await prisma.role.create({',
      '        data: { tenantId, name: `role-a-${Date.now()}` },',
      '      });',
      '      const otherTenant = await prisma.tenant.create({',
      '        data: { name: `tenant-g-${Date.now()}-${Math.random()}` },',
      '      });',
      '      createdTenantIds.push(otherTenant.id);',
      '      await prisma.role.create({',
      '        data: { tenantId: otherTenant.id, name: `role-b-${Date.now()}` },',
      '      });',
      '',
      '      const result = await adminRouter',
      '        .createCaller(makeAdminCtx())',
      '        .roles.list();',
      '',
      '      expect(result).toHaveLength(1);',
      "      expect(result[0]?.name.startsWith('role-a-')).toBe(true);",
      '    });',
      '',
      "    it('roles.create cria de verdade um Role no tenant do admin', async () => {",
      '      await adminRouter.createCaller(makeAdminCtx()).roles.create({',
      "        name: 'Gerente',",
      '      });',
      '',
      '      const created = await prisma.role.findFirst({',
      "        where: { tenantId, name: 'Gerente' },",
      '      });',
      '      expect(created).not.toBeNull();',
      '    });',
      '',
      "    it('roles.update edita o name de um Role do próprio tenant', async () => {",
      '      const role = await prisma.role.create({',
      '        data: { tenantId, name: `role-old-${Date.now()}` },',
      '      });',
      '',
      '      await adminRouter.createCaller(makeAdminCtx()).roles.update({',
      '        roleId: role.id,',
      "        name: 'Papel Renomeado',",
      '      });',
      '',
      '      const updated = await prisma.role.findUnique({',
      '        where: { id: role.id },',
      '      });',
      "      expect(updated?.name).toBe('Papel Renomeado');",
      '    });',
      '',
      "    it('roles.update/roles.delete nunca cruzam tenant — NOT_FOUND uniforme pra outro tenant E pra roleId inexistente (AD-5)', async () => {",
      '      const otherTenant = await prisma.tenant.create({',
      '        data: { name: `tenant-h-${Date.now()}-${Math.random()}` },',
      '      });',
      '      createdTenantIds.push(otherTenant.id);',
      '      const otherRole = await prisma.role.create({',
      '        data: { tenantId: otherTenant.id, name: `role-h-${Date.now()}` },',
      '      });',
      '',
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).roles.update({',
      '          roleId: otherRole.id,',
      "          name: 'hacked',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'NOT_FOUND' });",
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).roles.delete({',
      '          roleId: otherRole.id,',
      '        }),',
      "      ).rejects.toMatchObject({ code: 'NOT_FOUND' });",
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).roles.update({',
      "          roleId: 'id-que-nunca-existiu',",
      "          name: 'hacked',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'NOT_FOUND' });",
      '      await expect(',
      '        adminRouter.createCaller(makeAdminCtx()).roles.delete({',
      "          roleId: 'id-que-nunca-existiu',",
      '        }),',
      "      ).rejects.toMatchObject({ code: 'NOT_FOUND' });",
      '    });',
      '',
      "    it('roles.delete remove de verdade um Role sem atribuições', async () => {",
      '      const role = await prisma.role.create({',
      '        data: { tenantId, name: `role-del-${Date.now()}` },',
      '      });',
      '',
      '      await adminRouter.createCaller(makeAdminCtx()).roles.delete({',
      '        roleId: role.id,',
      '      });',
      '',
      '      expect(',
      '        await prisma.role.findUnique({ where: { id: role.id } }),',
      '      ).toBeNull();',
      '    });',
      '',
      "    it('roles.delete remove um Role associado a um Resource via CASCADE — associação M2M não bloqueia (AC #6, efeito real)', async () => {",
      '      const module = await prisma.module.create({',
      '        data: {',
      '          slug: `modulo-role-cascade-${Date.now()}`,',
      "          name: 'Módulo de teste do CASCADE de Role',",
      '        },',
      '      });',
      '      const resource = await prisma.resource.create({',
      '        data: { moduleId: module.id, name: `recurso-cascade-${Date.now()}` },',
      '      });',
      '      const role = await prisma.role.create({',
      '        data: {',
      '          tenantId,',
      '          name: `role-cascade-${Date.now()}`,',
      '          resources: { connect: { id: resource.id } },',
      '        },',
      '      });',
      '',
      '      try {',
      '        await adminRouter.createCaller(makeAdminCtx()).roles.delete({',
      '          roleId: role.id,',
      '        });',
      '',
      '        expect(',
      '          await prisma.role.findUnique({ where: { id: role.id } }),',
      '        ).toBeNull();',
      '        const resourceAfter = await prisma.resource.findUnique({',
      '          where: { id: resource.id },',
      '          include: { roles: true },',
      '        });',
      '        expect(resourceAfter).not.toBeNull();',
      '        expect(resourceAfter?.roles).toHaveLength(0);',
      '      } finally {',
      '        await prisma.resource',
      '          .delete({ where: { id: resource.id } })',
      '          .catch(() => undefined);',
      '        await prisma.module',
      '          .delete({ where: { id: module.id } })',
      '          .catch(() => undefined);',
      '      }',
      '    });',
      '',
      "    it('roles.delete responde CONFLICT (nunca erro bruto) se o Role ainda está atribuído a alguém via RoleAssignment — e o Role continua existindo depois (AC #5, RESTRICT real)', async () => {",
      '      const module = await prisma.module.create({',
      '        data: {',
      '          slug: `modulo-role-restrict-${Date.now()}`,',
      "          name: 'Módulo de teste do RESTRICT de Role',",
      '        },',
      '      });',
      '      const role = await prisma.role.create({',
      '        data: { tenantId, name: `role-restrict-${Date.now()}` },',
      '      });',
      '      const user = await prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `atribuido-${Date.now()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '      const roleAssignment = await prisma.roleAssignment.create({',
      '        data: {',
      '          tenantId,',
      '          userId: user.id,',
      '          roleId: role.id,',
      '          targetModuleId: module.id,',
      '        },',
      '      });',
      '',
      '      try {',
      '        await expect(',
      '          adminRouter.createCaller(makeAdminCtx()).roles.delete({',
      '            roleId: role.id,',
      '          }),',
      '        ).rejects.toMatchObject({',
      "          code: 'CONFLICT',",
      "          message:",
      "            'Papel ainda está atribuído a Usuários/Grupos — remova as atribuições antes de excluir.',",
      '        });',
      '',
      '        expect(',
      '          await prisma.role.findUnique({ where: { id: role.id } }),',
      '        ).not.toBeNull();',
      '      } finally {',
      '        await prisma.roleAssignment',
      '          .delete({ where: { id: roleAssignment.id } })',
      '          .catch(() => undefined);',
      '        await prisma.module',
      '          .delete({ where: { id: module.id } })',
      '          .catch(() => undefined);',
      '      }',
      '    });',
      '  },',
      ');',
      '',
    ].join('\n'),
  };
}
