export function buildApiFiles(): Record<string, string> {
  return {
    'package.json':
      JSON.stringify(
        {
          name: 'api',
          version: '0.0.1',
          private: true,
          type: 'module',
          // Único ponto que apps/web tem permissão de importar de apps/api (AD-3) — só o
          // tipo AppRouter, via pacote workspace (evita violação de rootDir do TS ao
          // importar caminho relativo cru pra dentro de outro projeto composite).
          exports: {
            './router': './src/root-router.ts',
          },
          scripts: {
            // --env-file (nativo do Node, processado ANTES de qualquer import ser
            // avaliado) — não `loadEnvFile()` em runtime dentro de server.ts: import
            // ESM estático resolve o grafo de dependências inteiro (context.ts ->
            // providers.ts -> db/client.ts, que lê DATABASE_URL no top-level do módulo)
            // ANTES do corpo do próprio server.ts rodar, então um `loadEnvFile()`
            // chamado lá dentro chega tarde demais pro Prisma Client já construído
            // (achado do code review da Story 2.1).
            dev: 'tsx watch --env-file=../../.env.development src/server.ts',
          },
          dependencies: {
            fastify: '5.12.1',
            '@trpc/server': '11.18.0',
            zod: '4.4.3',
            pino: '10.3.1',
            argon2: '0.45.1',
            jose: '6.2.10',
            '@fastify/cookie': '11.1.2',
            nodemailer: '10.0.13',
            shared: 'workspace:*',
            db: 'workspace:*',
          },
          devDependencies: {
            typescript: '5.9.3',
            tsx: '4.19.2',
            vitest: '4.1.11',
            '@types/node': '24.0.0',
          },
        },
        null,
        2,
      ) + '\n',

    'tsconfig.json':
      JSON.stringify(
        {
          extends: '../../tsconfig.base.json',
          compilerOptions: {
            composite: true,
            outDir: 'dist',
            rootDir: 'src',
          },
          include: ['src/**/*.ts'],
          references: [
            { path: '../../packages/shared' },
            { path: '../../packages/db' },
          ],
        },
        null,
        2,
      ) + '\n',

    'vitest.config.ts': [
      "import { sharedTestConfig } from '../../vitest.shared.js';",
      '',
      'export default sharedTestConfig;',
      '',
    ].join('\n'),

    // --- tRPC init + error formatting (FR-25: RFC 9457, invalid-params em JSON Pointer) ---
    'src/trpc.ts': [
      "import { initTRPC } from '@trpc/server';",
      "import { ZodError } from 'zod';",
      "import type { Context } from './context.js';",
      '',
      '// Formato Problem Details (RFC 9457) — sucesso nunca usa envelope (Consistency Conventions).',
      'export interface ProblemDetails {',
      '  type: string;',
      '  title: string;',
      '  status: number;',
      '  detail: string;',
      '  instance?: string;',
      "  'invalid-params'?: { name: string; reason: string }[];",
      '}',
      '',
      'interface FormatterShape {',
      '  message: string;',
      '  data: { httpStatus: number };',
      '}',
      'interface FormatterError {',
      '  cause?: unknown;',
      '}',
      '',
      '// Exportada separadamente pra ser testável sem montar um router real (Task 9.4).',
      'export function buildProblemDetails(',
      '  shape: FormatterShape,',
      '  error: FormatterError,',
      '): ProblemDetails {',
      '  const isServerError = shape.data.httpStatus >= 500;',
      '  const problem: ProblemDetails = {',
      "    type: 'about:blank',",
      '    // Erro 5xx nunca vaza title/detail internos pro cliente — só mensagens de',
      '    // erro do PRÓPRIO CLIENTE (4xx, ex. Zod) são seguras de ecoar (NFR: nenhuma',
      '    // alegação de segurança sem reforço técnico real — achado do code review).',
      "    title: isServerError ? 'Internal Server Error' : shape.message,",
      '    status: shape.data.httpStatus,',
      "    detail: isServerError ? 'Um erro inesperado ocorreu.' : shape.message,",
      '  };',
      '',
      '  if (error.cause instanceof ZodError) {',
      "    problem['invalid-params'] = error.cause.issues.map((issue) => ({",
      '      // JSON Pointer (RFC 6901) relativo ao input da procedure — nunca dot-notation.',
      "      name: '/' + issue.path.join('/'),",
      '      reason: issue.message,',
      '    }));',
      '  }',
      '',
      '  return problem;',
      '}',
      '',
      'const t = initTRPC.context<Context>().create({',
      '  errorFormatter({ shape, error }) {',
      '    const problem = buildProblemDetails(shape, error);',
      '    return { ...shape, data: { ...shape.data, problem } };',
      '  },',
      '});',
      '',
      'export const router = t.router;',
      'export const publicProcedure = t.procedure;',
      '// Base pra requireResource (core/authz, Story 3.1) — nenhum outro middleware',
      '// central existe ainda além do enforcement de Papel/Recurso.',
      'export const middleware = t.middleware;',
      '',
    ].join('\n'),

    'src/trpc.test.ts': [
      "import { describe, it, expect } from 'vitest';",
      "import { z } from 'zod';",
      "import { buildProblemDetails } from './trpc.js';",
      '',
      "describe('buildProblemDetails', () => {",
      "  it('mascara title/detail em erro 5xx — nunca vaza mensagem interna (AC #11, Task 9.4)', () => {",
      '    // "não derruba o processo" é garantido estruturalmente pelo tRPC — todo erro',
      '    // lançado numa procedure é capturado e passa por este formatter, nunca escapa',
      '    // como exceção não tratada. O que esta story de fato controla — e o que este',
      '    // teste verifica — é a FORMA da resposta RFC 9457 pra esse caso.',
      '    const shape = {',
      "      message: 'ENOENT: /etc/segredo-do-servidor não encontrado',",
      '      data: { httpStatus: 500 },',
      '    };',
      '',
      '    const problem = buildProblemDetails(shape, { cause: undefined });',
      '',
      '    expect(problem.status).toBe(500);',
      "    expect(problem.title).toBe('Internal Server Error');",
      "    expect(problem.detail).toBe('Um erro inesperado ocorreu.');",
      "    expect(problem.detail).not.toContain('segredo');",
      '  });',
      '',
      "  it('preserva a mensagem original em erro 4xx (erro do cliente, não é vazamento)', () => {",
      "    const shape = { message: 'Não autorizado', data: { httpStatus: 401 } };",
      '',
      '    const problem = buildProblemDetails(shape, { cause: undefined });',
      '',
      "    expect(problem.title).toBe('Não autorizado');",
      "    expect(problem.detail).toBe('Não autorizado');",
      '  });',
      '',
      "  it('inclui invalid-params em formato JSON Pointer quando a causa é ZodError (Task 9.2)', () => {",
      "    const shape = { message: 'Bad Request', data: { httpStatus: 400 } };",
      '    // Deriva um ZodError real de uma validação de verdade — construir o objeto',
      '    // de issue à mão é frágil entre versões do Zod (shape interna muda).',
      '    const result = z',
      "      .object({ name: z.string().min(1, 'muito curto') })",
      "      .safeParse({ name: '' });",
      '',
      '    const problem = buildProblemDetails(shape, { cause: result.error });',
      '',
      "    expect(problem['invalid-params']).toEqual([",
      "      { name: '/name', reason: 'muito curto' },",
      '    ]);',
      '  });',
      '});',
      '',
    ].join('\n'),

    // W3C Trace Context — arquivo próprio (não dentro de server.ts) pra ser importável em',
    // teste sem disparar o bootstrap do Fastify (server.ts tem `server.listen()` no top-level).',
    'src/traceparent.ts': [
      '// Formato W3C Trace Context: 00-<32 hex>-<16 hex>-<2 hex>.',
      'const TRACEPARENT_FORMAT = /^[0-9a-f]{2}-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$/;',
      '',
      '/**',
      ' * Gera um traceparent se o cliente não enviar um, ou enviar um valor que não',
      ' * bate o formato W3C — nunca confia cru numa string vinda do cliente antes de',
      ' * jogar pro log estruturado (achado do code review).',
      ' */',
      'export function ensureTraceparent(headerValue: unknown): string {',
      "  if (typeof headerValue === 'string' && TRACEPARENT_FORMAT.test(headerValue)) {",
      '    return headerValue;',
      '  }',
      "  const traceId = crypto.randomUUID().replace(/-/g, '');",
      "  const parentId = crypto.randomUUID().replace(/-/g, '').slice(0, 16);",
      '  return `00-${traceId}-${parentId}-01`;',
      '}',
      '',
    ].join('\n'),

    'src/traceparent.test.ts': [
      "import { describe, it, expect } from 'vitest';",
      "import { ensureTraceparent } from './traceparent.js';",
      '',
      'const VALID_FORMAT = /^[0-9a-f]{2}-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$/;',
      '',
      "describe('ensureTraceparent', () => {",
      "  it('gera um traceparent em formato W3C válido quando não há header (AC #10, Task 9.5)', () => {",
      '    const result = ensureTraceparent(undefined);',
      '',
      '    expect(result).toMatch(VALID_FORMAT);',
      '  });',
      '',
      "  it('repassa um traceparent de cliente já válido, sem trocar', () => {",
      '    const clientValue =',
      "      '00-fd907ddd6ff14cfcab44d9bed76188ba-c8d5923ae80e4b39-01';",
      '',
      '    expect(ensureTraceparent(clientValue)).toBe(clientValue);',
      '  });',
      '',
      "  it('descarta e gera um novo quando o header do cliente não bate o formato W3C', () => {",
      "    const result = ensureTraceparent('não-sou-um-traceparent-de-verdade');",
      '',
      '    expect(result).toMatch(VALID_FORMAT);',
      "    expect(result).not.toBe('não-sou-um-traceparent-de-verdade');",
      '  });',
      '',
      "  it('gera um novo para string vazia', () => {",
      "    expect(ensureTraceparent('')).toMatch(VALID_FORMAT);",
      '  });',
      '});',
      '',
    ].join('\n'),

    'src/context.ts': [
      "import type { CreateFastifyContextOptions } from '@trpc/server/adapters/fastify';",
      "import type { FastifyRequest } from 'fastify';",
      'import {',
      '  authProvider,',
      '  secretsProvider,',
      '  tokenRevocationStore,',
      '  rateLimiter,',
      '  emailProvider,',
      "} from './core/providers.js';",
      '',
      '// Access token nunca em cookie (Story 2.1, AC #6) — chega via header',
      '// `Authorization: Bearer <token>`. Ausência/token inválido não lança aqui —',
      '// ctx.user fica undefined, e é o `requireResource` (Story 3.1) quem decide',
      '// rejeitar; isso deixa publicProcedures (login, system.hello) funcionando sem',
      '// token normalmente.',
      'async function resolveUser(req: FastifyRequest) {',
      '  const header = req.headers.authorization;',
      '  // Esquema é case-insensitive por RFC 6750 — achado do code review, o match',
      "  // original só aceitava 'Bearer ' com B maiúsculo exato. O token em si (depois",
      '  // do espaço) NUNCA é normalizado — só o nome do esquema.',
      "  if (!header?.toLowerCase().startsWith('bearer ')) {",
      '    return undefined;',
      '  }',
      "  const token = header.slice(header.indexOf(' ') + 1);",
      '  const verified = await authProvider.verifyToken(token);',
      '  return verified ?? undefined;',
      '}',
      '',
      '// req/res (Fastify) expostos desde a Story 2.1 — o adapter Fastify do tRPC passa o',
      '// FastifyReply real via ctx.res, então `ctx.res.setCookie(...)` funciona de dentro',
      '// de uma procedure (ver Dev Notes da Story 2.1).',
      'export async function createContext({ req, res }: CreateFastifyContextOptions) {',
      '  const user = await resolveUser(req);',
      '  return {',
      '    req,',
      '    res,',
      '    user,',
      '    authProvider,',
      '    secretsProvider,',
      '    tokenRevocationStore,',
      '    rateLimiter,',
      '    emailProvider,',
      '  };',
      '}',
      '',
      'export type Context = Awaited<ReturnType<typeof createContext>>;',
      '',
    ].join('\n'),

    // Helper reaproveitável pra testes que precisam de um Context válido via
    // router.createCaller (Story 2.1) — sem isso, `createCaller({})` (padrão da Story 1.1)
    // quebra assim que Context ganha req/res/providers. req/res são fakes mínimos o
    // suficiente pra exercitar setCookie/cookies sem precisar de um Fastify real.
    'src/test-utils.ts': [
      "import { vi } from 'vitest';",
      "import type { FastifyRequest, FastifyReply } from 'fastify';",
      "import type { Context } from './context.js';",
      "import type { RateLimiter } from './core/auth/rate-limiter.js';",
      'import {',
      '  authProvider,',
      '  secretsProvider,',
      '  tokenRevocationStore,',
      '  emailProvider,',
      "} from './core/providers.js';",
      '',
      '// Fake default nunca bloqueia — cada teste que precisa exercitar o bloqueio',
      '// (Story 2.2) sobrescreve via `overrides.rateLimiter`, mesmo padrão de',
      '// `makeFakeStore`/`makeFakeAuthProvider` em router.test.ts.',
      'function makeDefaultRateLimiter(): RateLimiter {',
      '  return {',
      '    // `() => Promise.resolve(...)`, não `async () => ...` — sem `await` interno,',
      '    // `async` dispararia @typescript-eslint/require-await aqui (o override que',
      '    // desliga essa regra só cobre **/*.test.ts, e este arquivo não é um).',
      '    isBlocked: vi.fn(() => Promise.resolve(false)),',
      '    recordFailure: vi.fn(() => Promise.resolve(undefined)),',
      '  };',
      '}',
      '',
      'export function createTestContext(overrides: Partial<Context> = {}): Context {',
      '  const cookieJar: Record<string, string> = {};',
      '',
      '  // ip fixo — testes que precisam verificar o identificador `ip:<ip>` (Story 2.2)',
      "  // sobrescrevem via `overrides` ou lêem esse valor conhecido ('127.0.0.1').",
      '  const req = {',
      '    cookies: cookieJar,',
      "    ip: '127.0.0.1',",
      '    // Fastify sempre anexa um logger por requisição — o fake precisa de um',
      '    // stub mínimo, senão `ctx.req.log.error(...)` (Story 2.2, fail-closed do',
      '    // rate limiter) quebra em teste com um TypeError real, não simulado.',
      '    log: { error: vi.fn() },',
      '  } as unknown as FastifyRequest;',
      '  // vi.fn() — não uma função crua — pra os testes de login (AC #6) poderem',
      '  // inspecionar COM QUE flags (httpOnly/sameSite/secure/maxAge) o cookie foi',
      '  // setado, não só que o valor chegou no cookie jar (achado do code review).',
      '  const res = {',
      '    // Implementação não declara o 3º parâmetro (`options`) — não usado pelo',
      '    // corpo do fake, mas ainda chega em `vi.fn()` como argumento de chamada',
      '    // real, disponível pra `toHaveBeenCalledWith(...)` inspecionar.',
      '    setCookie: vi.fn((name: string, value: string) => {',
      '      cookieJar[name] = value;',
      '      return res;',
      '    }),',
      '  } as unknown as FastifyReply;',
      '',
      '  return {',
      '    req,',
      '    res,',
      '    // undefined por padrão (mesmo comportamento de requisição sem token) —',
      '    // testes que precisam simular um usuário autenticado sobrescrevem via',
      '    // `overrides.user` (Story 3.1, `core/authz`).',
      '    user: undefined,',
      '    authProvider,',
      '    secretsProvider,',
      '    tokenRevocationStore,',
      '    rateLimiter: makeDefaultRateLimiter(),',
      '    emailProvider,',
      '    ...overrides,',
      '  };',
      '}',
      '',
    ].join('\n'),

    'src/root-router.ts': [
      "import { router } from './trpc.js';",
      "import { systemRouter } from './modules/system/router.js';",
      "import { authRouter } from './core/auth/router.js';",
      '',
      'export const appRouter = router({',
      '  system: systemRouter,',
      '  auth: authRouter,',
      '});',
      '',
      'export type AppRouter = typeof appRouter;',
      '',
    ].join('\n'),

    // --- Fastify bootstrap: Pino + traceparent correlation (FR-24) + tRPC plugin ---
    'src/server.ts': [
      "import Fastify, { type FastifyError } from 'fastify';",
      "import fastifyCookie from '@fastify/cookie';",
      "import { fastifyTRPCPlugin, type FastifyTRPCPluginOptions } from '@trpc/server/adapters/fastify';",
      "import { appRouter, type AppRouter } from './root-router.js';",
      "import { createContext } from './context.js';",
      "import { ensureTraceparent } from './traceparent.js';",
      '',
      '// .env.development (raiz do monorepo) é carregado via `--env-file` no script `dev`',
      '// (package.json), NÃO aqui em runtime — import ESM estático avalia todo o grafo',
      '// de dependências deste módulo (context.ts -> providers.ts -> db/client.ts, que lê',
      '// DATABASE_URL no top-level) ANTES do corpo deste arquivo executar; um',
      '// `loadEnvFile()` chamado aqui chegaria tarde demais pro Prisma Client já',
      '// construído com a connection string vazia (achado do code review da Story 2.1).',
      '',
      'const server = Fastify({',
      '  // logger:true é obrigatório — sem ele, server.log é um no-op e o processo',
      '  // pode sair silenciosamente (sem nenhuma linha impressa) se listen() falhar,',
      '  // além de quebrar o requisito de log estruturado por requisição (FR-24).',
      '  logger: true,',
      '  // Sem isso, atrás de um proxy reverso (ex.: o Laboratório Integrit',
      '  // compartilhado tem HAProxy + nginx-proxy na frente) `req.ip` sempre resolve',
      '  // pro IP do proxy, não do cliente real — o rate limit por IP (Story 2.2, AC #3)',
      '  // ficaria inútil nesse ambiente. Não muda nada em `pnpm dev` local sem proxy',
      '  // (Fastify só usa X-Forwarded-For/X-Real-IP se o header existir).',
      '  trustProxy: true,',
      '  routerOptions: { maxParamLength: 5000 },',
      '  childLoggerFactory(logger, bindings, opts, rawReq) {',
      '    const traceparent = ensureTraceparent(rawReq.headers.traceparent);',
      '    return logger.child({ ...bindings, traceparent }, opts);',
      '  },',
      '});',
      '',
      '// Tratamento de erro global (FR-25) — erro não tratado não derruba o processo.',
      '// Respeita error.statusCode quando o próprio Fastify já classificou o erro (ex.:',
      '// payload grande, content-type inválido) — antes isso virava sempre 500 genérico',
      '// mesmo pra erro do cliente (achado do code review). Só mascara detail em 5xx.',
      'server.setErrorHandler((error: FastifyError, request, reply) => {',
      "  request.log.error({ err: error }, 'unhandled error');",
      "  const status = typeof error.statusCode === 'number' ? error.statusCode : 500;",
      '  const isServerError = status >= 500;',
      '  reply.status(status).send({',
      "    type: 'about:blank',",
      "    title: isServerError ? 'Internal Server Error' : error.message,",
      '    status,',
      "    detail: isServerError ? 'Um erro inesperado ocorreu.' : error.message,",
      '  });',
      '});',
      '',
      '// Registra ANTES do plugin de tRPC — sem isso, ctx.res.setCookie(...) (Story 2.1,',
      '// procedure login) não existe em runtime.',
      'server.register(fastifyCookie);',
      '',
      'server.register(fastifyTRPCPlugin, {',
      "  prefix: '/trpc',",
      '  trpcOptions: {',
      '    router: appRouter,',
      '    createContext,',
      '    onError({ path, error }) {',
      "      server.log.error({ path, error }, 'tRPC error');",
      '    },',
      "  } satisfies FastifyTRPCPluginOptions<AppRouter>['trpcOptions'],",
      '});',
      '',
      'const port = Number(process.env.API_PORT ?? 3001);',
      '// Default 127.0.0.1 preserva o comportamento de sempre no `pnpm dev` local.',
      '// Containers (docker-compose.dev.yml, deploy de lab) setam HOST=0.0.0.0 —',
      '// sem ler isso aqui, o server só aceita conexão de dentro do próprio',
      '// container (127.0.0.1 no namespace de rede do container não é alcançável',
      '// de fora, nem por outro container na mesma rede Docker nem por porta',
      '// publicada do host) — achado real durante a validação da Story 2.2.',
      "// || (não ??) -- HOST='' (string vazia) também deve cair no default seguro,",
      '// não só ausência (null/undefined) da env var (achado do code review).',
      '// eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing -- string vazia é um valor "ausente" aqui, não um valor válido a preservar',
      "const host = process.env.HOST || '127.0.0.1';",
      '',
      'server',
      '  .listen({ port, host })',
      '  .then(() => server.log.info(`api listening on :${port}`))',
      '  .catch((err: unknown) => {',
      '    server.log.error(err);',
      '    process.exitCode = 1;',
      '  });',
      '',
      'export { server };',
      '',
    ].join('\n'),

    // --- Módulo `system` — stub Hexagonal (AD-1), sem enforcement/tree ainda (ver Dev Notes Story 1.1) ---
    'src/modules/system/domain/.gitkeep': '',

    'src/modules/system/schema.ts': [
      'export {',
      '  systemHelloInputSchema,',
      '  systemHelloOutputSchema,',
      "} from 'shared/schemas/system';",
      '',
    ].join('\n'),

    'src/modules/system/resources.ts': [
      '// Nenhum Recurso declarado ainda nesta story — o módulo `system` desta story não é',
      '// registrado na árvore de identidade (ver Dev Notes Story 1.1, restrição de escopo).',
      '// Recursos reais chegam quando a Epic 3 rodar `generate module` de verdade.',
      'export const systemResources: string[] = [];',
      '',
    ].join('\n'),

    'src/modules/system/repository.ts': [
      '// Stub — sem tabela de negócio nesta story (ver Dev Notes Story 1.1). Não importa',
      '// @prisma/client. Fica pronto pra Epic 2/3 adicionarem uma implementação real aqui.',
      'export {};',
      '',
    ].join('\n'),

    'src/modules/system/router.ts': [
      "import { publicProcedure, router } from '../../trpc.js';",
      "import { systemHelloInputSchema, systemHelloOutputSchema } from './schema.js';",
      '',
      '// TODO(Epic 3): habilitar enforcement default-deny (AD-7) quando core/authz existir —',
      '// esta procedure NÃO usa .use(requireResource(...)) ainda (ver Dev Notes Story 1.1).',
      'export const systemRouter = router({',
      '  hello: publicProcedure',
      '    .input(systemHelloInputSchema)',
      '    .output(systemHelloOutputSchema)',
      '    .query(({ input }) => {',
      "      return { message: input?.name ? `Hello, ${input.name}!` : 'Hello World!' };",
      '    }),',
      '});',
      '',
    ].join('\n'),

    'src/modules/system/router.test.ts': [
      "import { describe, it, expect } from 'vitest';",
      "import { ZodError } from 'zod';",
      "import { systemRouter } from './router.js';",
      "import { createTestContext } from '../../test-utils.js';",
      '',
      "describe('systemRouter.hello', () => {",
      "  it('retorna Hello World! sem input (AC #3 — sem tocar Prisma/banco)', async () => {",
      '    const caller = systemRouter.createCaller(createTestContext());',
      '',
      '    const result = await caller.hello();',
      '',
      "    expect(result).toEqual({ message: 'Hello World!' });",
      '  });',
      '',
      "  it('personaliza a mensagem quando um nome válido é passado', async () => {",
      '    const caller = systemRouter.createCaller(createTestContext());',
      '',
      "    const result = await caller.hello({ name: 'Ada' });",
      '',
      "    expect(result).toEqual({ message: 'Hello, Ada!' });",
      '  });',
      '',
      "  it('rejeita input inválido com erro de validação Zod (AC #11, invalid-params)', async () => {",
      '    const caller = systemRouter.createCaller(createTestContext());',
      '',
      '    // string vazia passa no tipo (é um `string` válido) mas falha em runtime no',
      '    // `.min(1)` do schema Zod — é exatamente esse caminho que o formatter cobre.',
      "    await expect(caller.hello({ name: '' })).rejects.toMatchObject({",
      "      code: 'BAD_REQUEST',",
      '      // expect.any() do Vitest é tipado `any` por design — coberto pelo override',
      "      // de '@typescript-eslint/no-unsafe-assignment' pra **/*.test.ts (eslint.config.js).",
      '      cause: expect.any(ZodError),',
      '    });',
      '  });',
      '});',
      '',
    ].join('\n'),
  };
}
