export function buildApiFiles(): Record<string, string> {
  return {
    'package.json':
      JSON.stringify(
        {
          name: 'api',
          version: '0.0.1',
          private: true,
          type: 'module',
          // Único ponto que apps/web tem permissão de importar de apps/api (AD-3) — só o
          // tipo AppRouter, via pacote workspace (evita violação de rootDir do TS ao
          // importar caminho relativo cru pra dentro de outro projeto composite).
          exports: {
            './router': './src/root-router.ts',
          },
          scripts: {
            dev: 'tsx watch src/server.ts',
          },
          dependencies: {
            fastify: '5.12.1',
            '@trpc/server': '11.18.0',
            zod: '4.4.3',
            pino: '10.3.1',
            shared: 'workspace:*',
            db: 'workspace:*',
          },
          devDependencies: {
            typescript: '5.9.3',
            tsx: '4.19.2',
            vitest: '4.1.11',
            '@types/node': '24.0.0',
          },
        },
        null,
        2,
      ) + '\n',

    'tsconfig.json':
      JSON.stringify(
        {
          extends: '../../tsconfig.base.json',
          compilerOptions: {
            composite: true,
            outDir: 'dist',
            rootDir: 'src',
          },
          include: ['src/**/*.ts'],
          references: [
            { path: '../../packages/shared' },
            { path: '../../packages/db' },
          ],
        },
        null,
        2,
      ) + '\n',

    'vitest.config.ts': [
      "import { sharedTestConfig } from '../../vitest.shared.js';",
      '',
      'export default sharedTestConfig;',
      '',
    ].join('\n'),

    // --- tRPC init + error formatting (FR-25: RFC 9457, invalid-params em JSON Pointer) ---
    'src/trpc.ts': [
      "import { initTRPC } from '@trpc/server';",
      "import { ZodError } from 'zod';",
      "import type { Context } from './context.js';",
      '',
      '// Formato Problem Details (RFC 9457) — sucesso nunca usa envelope (Consistency Conventions).',
      'export interface ProblemDetails {',
      '  type: string;',
      '  title: string;',
      '  status: number;',
      '  detail: string;',
      '  instance?: string;',
      "  'invalid-params'?: { name: string; reason: string }[];",
      '}',
      '',
      'interface FormatterShape {',
      '  message: string;',
      '  data: { httpStatus: number };',
      '}',
      'interface FormatterError {',
      '  cause?: unknown;',
      '}',
      '',
      '// Exportada separadamente pra ser testável sem montar um router real (Task 9.4).',
      'export function buildProblemDetails(',
      '  shape: FormatterShape,',
      '  error: FormatterError,',
      '): ProblemDetails {',
      '  const isServerError = shape.data.httpStatus >= 500;',
      '  const problem: ProblemDetails = {',
      "    type: 'about:blank',",
      '    // Erro 5xx nunca vaza title/detail internos pro cliente — só mensagens de',
      '    // erro do PRÓPRIO CLIENTE (4xx, ex. Zod) são seguras de ecoar (NFR: nenhuma',
      '    // alegação de segurança sem reforço técnico real — achado do code review).',
      "    title: isServerError ? 'Internal Server Error' : shape.message,",
      '    status: shape.data.httpStatus,',
      "    detail: isServerError ? 'Um erro inesperado ocorreu.' : shape.message,",
      '  };',
      '',
      '  if (error.cause instanceof ZodError) {',
      "    problem['invalid-params'] = error.cause.issues.map((issue) => ({",
      '      // JSON Pointer (RFC 6901) relativo ao input da procedure — nunca dot-notation.',
      "      name: '/' + issue.path.join('/'),",
      '      reason: issue.message,',
      '    }));',
      '  }',
      '',
      '  return problem;',
      '}',
      '',
      'const t = initTRPC.context<Context>().create({',
      '  errorFormatter({ shape, error }) {',
      '    const problem = buildProblemDetails(shape, error);',
      '    return { ...shape, data: { ...shape.data, problem } };',
      '  },',
      '});',
      '',
      'export const router = t.router;',
      'export const publicProcedure = t.procedure;',
      '',
    ].join('\n'),

    'src/trpc.test.ts': [
      "import { describe, it, expect } from 'vitest';",
      "import { z } from 'zod';",
      "import { buildProblemDetails } from './trpc.js';",
      '',
      "describe('buildProblemDetails', () => {",
      "  it('mascara title/detail em erro 5xx — nunca vaza mensagem interna (AC #11, Task 9.4)', () => {",
      '    // "não derruba o processo" é garantido estruturalmente pelo tRPC — todo erro',
      '    // lançado numa procedure é capturado e passa por este formatter, nunca escapa',
      '    // como exceção não tratada. O que esta story de fato controla — e o que este',
      '    // teste verifica — é a FORMA da resposta RFC 9457 pra esse caso.',
      '    const shape = {',
      "      message: 'ENOENT: /etc/segredo-do-servidor não encontrado',",
      '      data: { httpStatus: 500 },',
      '    };',
      '',
      '    const problem = buildProblemDetails(shape, { cause: undefined });',
      '',
      '    expect(problem.status).toBe(500);',
      "    expect(problem.title).toBe('Internal Server Error');",
      "    expect(problem.detail).toBe('Um erro inesperado ocorreu.');",
      "    expect(problem.detail).not.toContain('segredo');",
      '  });',
      '',
      "  it('preserva a mensagem original em erro 4xx (erro do cliente, não é vazamento)', () => {",
      "    const shape = { message: 'Não autorizado', data: { httpStatus: 401 } };",
      '',
      '    const problem = buildProblemDetails(shape, { cause: undefined });',
      '',
      "    expect(problem.title).toBe('Não autorizado');",
      "    expect(problem.detail).toBe('Não autorizado');",
      '  });',
      '',
      "  it('inclui invalid-params em formato JSON Pointer quando a causa é ZodError (Task 9.2)', () => {",
      "    const shape = { message: 'Bad Request', data: { httpStatus: 400 } };",
      '    // Deriva um ZodError real de uma validação de verdade — construir o objeto',
      '    // de issue à mão é frágil entre versões do Zod (shape interna muda).',
      '    const result = z',
      "      .object({ name: z.string().min(1, 'muito curto') })",
      "      .safeParse({ name: '' });",
      '',
      '    const problem = buildProblemDetails(shape, { cause: result.error });',
      '',
      "    expect(problem['invalid-params']).toEqual([",
      "      { name: '/name', reason: 'muito curto' },",
      '    ]);',
      '  });',
      '});',
      '',
    ].join('\n'),

    // W3C Trace Context — arquivo próprio (não dentro de server.ts) pra ser importável em',
    // teste sem disparar o bootstrap do Fastify (server.ts tem `server.listen()` no top-level).',
    'src/traceparent.ts': [
      '// Formato W3C Trace Context: 00-<32 hex>-<16 hex>-<2 hex>.',
      'const TRACEPARENT_FORMAT = /^[0-9a-f]{2}-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$/;',
      '',
      '/**',
      ' * Gera um traceparent se o cliente não enviar um, ou enviar um valor que não',
      ' * bate o formato W3C — nunca confia cru numa string vinda do cliente antes de',
      ' * jogar pro log estruturado (achado do code review).',
      ' */',
      'export function ensureTraceparent(headerValue: unknown): string {',
      "  if (typeof headerValue === 'string' && TRACEPARENT_FORMAT.test(headerValue)) {",
      '    return headerValue;',
      '  }',
      "  const traceId = crypto.randomUUID().replace(/-/g, '');",
      "  const parentId = crypto.randomUUID().replace(/-/g, '').slice(0, 16);",
      '  return `00-${traceId}-${parentId}-01`;',
      '}',
      '',
    ].join('\n'),

    'src/traceparent.test.ts': [
      "import { describe, it, expect } from 'vitest';",
      "import { ensureTraceparent } from './traceparent.js';",
      '',
      'const VALID_FORMAT = /^[0-9a-f]{2}-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$/;',
      '',
      "describe('ensureTraceparent', () => {",
      "  it('gera um traceparent em formato W3C válido quando não há header (AC #10, Task 9.5)', () => {",
      '    const result = ensureTraceparent(undefined);',
      '',
      '    expect(result).toMatch(VALID_FORMAT);',
      '  });',
      '',
      "  it('repassa um traceparent de cliente já válido, sem trocar', () => {",
      '    const clientValue =',
      "      '00-fd907ddd6ff14cfcab44d9bed76188ba-c8d5923ae80e4b39-01';",
      '',
      '    expect(ensureTraceparent(clientValue)).toBe(clientValue);',
      '  });',
      '',
      "  it('descarta e gera um novo quando o header do cliente não bate o formato W3C', () => {",
      "    const result = ensureTraceparent('não-sou-um-traceparent-de-verdade');",
      '',
      '    expect(result).toMatch(VALID_FORMAT);',
      "    expect(result).not.toBe('não-sou-um-traceparent-de-verdade');",
      '  });',
      '',
      "  it('gera um novo para string vazia', () => {",
      "    expect(ensureTraceparent('')).toMatch(VALID_FORMAT);",
      '  });',
      '});',
      '',
    ].join('\n'),

    'src/context.ts': [
      "import type { CreateFastifyContextOptions } from '@trpc/server/adapters/fastify';",
      '',
      '// Sem AuthProvider/tenant ainda nesta story (chegam nas Epics 2/3) — ctx mínimo.',
      '// eslint-disable-next-line @typescript-eslint/no-unused-vars',
      'export function createContext({ req, res }: CreateFastifyContextOptions) {',
      '  return {};',
      '}',
      '',
      'export type Context = Awaited<ReturnType<typeof createContext>>;',
      '',
    ].join('\n'),

    'src/root-router.ts': [
      "import { router } from './trpc.js';",
      "import { systemRouter } from './modules/system/router.js';",
      '',
      'export const appRouter = router({',
      '  system: systemRouter,',
      '});',
      '',
      'export type AppRouter = typeof appRouter;',
      '',
    ].join('\n'),

    // --- Fastify bootstrap: Pino + traceparent correlation (FR-24) + tRPC plugin ---
    'src/server.ts': [
      "import { loadEnvFile } from 'node:process';",
      "import Fastify, { type FastifyError } from 'fastify';",
      "import { fastifyTRPCPlugin, type FastifyTRPCPluginOptions } from '@trpc/server/adapters/fastify';",
      "import { appRouter, type AppRouter } from './root-router.js';",
      "import { createContext } from './context.js';",
      "import { ensureTraceparent } from './traceparent.js';",
      '',
      '// Carrega .env.development (raiz do monorepo) pra process.env — sem isso, FR-6',
      '// (config externalizada) era só decorativo: o arquivo existia mas nada o lia de',
      '// verdade (achado do code review). Silencioso se o arquivo não existir ainda.',
      'try {',
      "  loadEnvFile(new URL('../../.env.development', import.meta.url));",
      '} catch {',
      '  // ok não existir em todo contexto (ex.: alguns runners de teste)',
      '}',
      '',
      'const server = Fastify({',
      '  // logger:true é obrigatório — sem ele, server.log é um no-op e o processo',
      '  // pode sair silenciosamente (sem nenhuma linha impressa) se listen() falhar,',
      '  // além de quebrar o requisito de log estruturado por requisição (FR-24).',
      '  logger: true,',
      '  routerOptions: { maxParamLength: 5000 },',
      '  childLoggerFactory(logger, bindings, opts, rawReq) {',
      '    const traceparent = ensureTraceparent(rawReq.headers.traceparent);',
      '    return logger.child({ ...bindings, traceparent }, opts);',
      '  },',
      '});',
      '',
      '// Tratamento de erro global (FR-25) — erro não tratado não derruba o processo.',
      '// Respeita error.statusCode quando o próprio Fastify já classificou o erro (ex.:',
      '// payload grande, content-type inválido) — antes isso virava sempre 500 genérico',
      '// mesmo pra erro do cliente (achado do code review). Só mascara detail em 5xx.',
      'server.setErrorHandler((error: FastifyError, request, reply) => {',
      "  request.log.error({ err: error }, 'unhandled error');",
      "  const status = typeof error.statusCode === 'number' ? error.statusCode : 500;",
      '  const isServerError = status >= 500;',
      '  reply.status(status).send({',
      "    type: 'about:blank',",
      "    title: isServerError ? 'Internal Server Error' : error.message,",
      '    status,',
      "    detail: isServerError ? 'Um erro inesperado ocorreu.' : error.message,",
      '  });',
      '});',
      '',
      'server.register(fastifyTRPCPlugin, {',
      "  prefix: '/trpc',",
      '  trpcOptions: {',
      '    router: appRouter,',
      '    createContext,',
      '    onError({ path, error }) {',
      "      server.log.error({ path, error }, 'tRPC error');",
      '    },',
      "  } satisfies FastifyTRPCPluginOptions<AppRouter>['trpcOptions'],",
      '});',
      '',
      'const port = Number(process.env.API_PORT ?? 3001);',
      '',
      'server',
      '  .listen({ port })',
      '  .then(() => server.log.info(`api listening on :${port}`))',
      '  .catch((err: unknown) => {',
      '    server.log.error(err);',
      '    process.exitCode = 1;',
      '  });',
      '',
      'export { server };',
      '',
    ].join('\n'),

    // --- Módulo `system` — stub Hexagonal (AD-1), sem enforcement/tree ainda (ver Dev Notes Story 1.1) ---
    'src/modules/system/domain/.gitkeep': '',

    'src/modules/system/schema.ts': [
      'export {',
      '  systemHelloInputSchema,',
      '  systemHelloOutputSchema,',
      "} from 'shared/schemas/system';",
      '',
    ].join('\n'),

    'src/modules/system/resources.ts': [
      '// Nenhum Recurso declarado ainda nesta story — o módulo `system` desta story não é',
      '// registrado na árvore de identidade (ver Dev Notes Story 1.1, restrição de escopo).',
      '// Recursos reais chegam quando a Epic 3 rodar `generate module` de verdade.',
      'export const systemResources: string[] = [];',
      '',
    ].join('\n'),

    'src/modules/system/repository.ts': [
      '// Stub — sem tabela de negócio nesta story (ver Dev Notes Story 1.1). Não importa',
      '// @prisma/client. Fica pronto pra Epic 2/3 adicionarem uma implementação real aqui.',
      'export {};',
      '',
    ].join('\n'),

    'src/modules/system/router.ts': [
      "import { publicProcedure, router } from '../../trpc.js';",
      "import { systemHelloInputSchema, systemHelloOutputSchema } from './schema.js';",
      '',
      '// TODO(Epic 3): habilitar enforcement default-deny (AD-7) quando core/authz existir —',
      '// esta procedure NÃO usa .use(requireResource(...)) ainda (ver Dev Notes Story 1.1).',
      'export const systemRouter = router({',
      '  hello: publicProcedure',
      '    .input(systemHelloInputSchema)',
      '    .output(systemHelloOutputSchema)',
      '    .query(({ input }) => {',
      "      return { message: input?.name ? `Hello, ${input.name}!` : 'Hello World!' };",
      '    }),',
      '});',
      '',
    ].join('\n'),

    'src/modules/system/router.test.ts': [
      "import { describe, it, expect } from 'vitest';",
      "import { ZodError } from 'zod';",
      "import { systemRouter } from './router.js';",
      '',
      "describe('systemRouter.hello', () => {",
      "  it('retorna Hello World! sem input (AC #3 — sem tocar Prisma/banco)', async () => {",
      '    const caller = systemRouter.createCaller({});',
      '',
      '    const result = await caller.hello();',
      '',
      "    expect(result).toEqual({ message: 'Hello World!' });",
      '  });',
      '',
      "  it('personaliza a mensagem quando um nome válido é passado', async () => {",
      '    const caller = systemRouter.createCaller({});',
      '',
      "    const result = await caller.hello({ name: 'Ada' });",
      '',
      "    expect(result).toEqual({ message: 'Hello, Ada!' });",
      '  });',
      '',
      "  it('rejeita input inválido com erro de validação Zod (AC #11, invalid-params)', async () => {",
      '    const caller = systemRouter.createCaller({});',
      '',
      '    // string vazia passa no tipo (é um `string` válido) mas falha em runtime no',
      '    // `.min(1)` do schema Zod — é exatamente esse caminho que o formatter cobre.',
      "    await expect(caller.hello({ name: '' })).rejects.toMatchObject({",
      "      code: 'BAD_REQUEST',",
      '      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment -- expect.any() do Vitest é tipado como `any` por design',
      '      cause: expect.any(ZodError),',
      '    });',
      '  });',
      '});',
      '',
    ].join('\n'),
  };
}
