export function buildAuthzFiles(): Record<string, string> {
  return {
    // --- requireResource (FR-27, AD-7/AD-8) — middleware único e central de ---
    // enforcement. Fecha a AC #10 da Story 2.1 (Zero Trust) sendo o primeiro
    // consumidor real de ctx.user. Ver Dev Notes da Story 3.1 pra reconciliação do
    // gap real de Resource.moduleId no ERD original da Architecture Spine.
    'src/core/authz/require-resource.ts': [
      "import { TRPCError } from '@trpc/server';",
      "import { prisma } from 'db/client';",
      "import { forTenant } from 'db/extensions/tenant';",
      "import { middleware } from '../../trpc.js';",
      '',
      '// resourceId é sempre `<module-slug>.<ação>` (AD-7) — nunca uma string livre',
      '// escolhida ad-hoc; gerado automaticamente por `generate module` (Story 3.2).',
      'export function requireResource(resourceId: string) {',
      '  return middleware(async ({ ctx, next }) => {',
      '    if (!ctx.user) {',
      "      throw new TRPCError({ code: 'UNAUTHORIZED' });",
      '    }',
      '',
      '    // Resource e Module são globais (estrutura de código compartilhada por toda a',
      '    // instalação, não dado de tenant — reconciliação pós-review da Story 3.1) —',
      '    // busca direta no client cru, não pela extensão tenant-aware (que só cobre',
      '    // Group/RoleAssignment de propósito, ver Dev Notes).',
      '    const resource = await prisma.resource.findUnique({',
      '      where: { name: resourceId },',
      '      select: { id: true, moduleId: true },',
      '    });',
      '    if (!resource) {',
      '      // Erro de configuração — só `generate module` (Story 3.2) cria Resources,',
      '      // isso só acontece por um bug do próprio gerador, nunca por ação do',
      '      // usuário (não é FORBIDDEN).',
      "      throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR' });",
      '    }',
      '',
      '    // Dois round-trips no total (resource.findUnique acima + este), não um só —',
      '    // achado do code review, comentário anterior dizia "uma única query" e estava',
      '    // impreciso. A query de COBERTURA em si (esta) é que é única e sem N+1: a',
      '    // subida pela ModuleClosure acontece dentro dela via o relacionamento',
      '    // (descendantClosures), não em código (AD-8). Cobertura = existe RoleAssignment',
      '    // (direta no usuário OU via Group de que o usuário é membro) cujo Role concede',
      '    // o Resource, com targetModule igual ou ancestral do módulo do Resource',
      '    // (herança aditiva, FR-12). Latência real medida ponta a ponta (Task 5) já',
      '    // inclui os dois round-trips.',
      '    const db = forTenant(ctx.user.tenantId);',
      '    const coverage = await db.roleAssignment.findFirst({',
      '      select: { id: true },',
      '      where: {',
      '        role: { resources: { some: { id: resource.id } } },',
      '        targetModule: {',
      '          descendantClosures: { some: { descendantId: resource.moduleId } },',
      '        },',
      '        OR: [',
      '          { userId: ctx.user.userId },',
      '          { group: { users: { some: { id: ctx.user.userId } } } },',
      '        ],',
      '      },',
      '    });',
      '',
      '    if (!coverage) {',
      "      throw new TRPCError({ code: 'FORBIDDEN' });",
      '    }',
      '',
      '    return next({ ctx: { ...ctx, user: ctx.user } });',
      '  });',
      '}',
      '',
    ].join('\n'),

    // Testes de integração reais contra Postgres — a lógica de cobertura É a query
    // relacional (ModuleClosure/RoleAssignment/Role/Resource); um fake não provaria
    // nada sobre o comportamento real do Prisma aqui (diferente de
    // extensions/tenant.test.ts, Story 3.1, onde a lógica de merge era extraível
    // como função pura — aqui não tem como extrair sem perder o que se quer testar).
    // Roda só quando DATABASE_URL está setado — skip gracioso sem banco, não quebra
    // `pnpm test` em ambiente sem Postgres (mesmo espírito das outras stories).
    // Cobertura de múltiplos níveis de ancestralidade exigida pela própria nota de
    // implementação do Epic 3 em epics.md.
    'src/core/authz/require-resource.test.ts': [
      "import { describe, it, expect, beforeEach, afterEach } from 'vitest';",
      "import { prisma } from 'db/client';",
      "import { requireResource } from './require-resource.js';",
      "import { router, publicProcedure } from '../../trpc.js';",
      "import { createTestContext } from '../../test-utils.js';",
      "import type { Context } from '../../context.js';",
      '',
      '// Fixtures reais via Prisma direto (mesmo padrão de User na Story 2.1) — não é',
      '// seed de produto, é infraestrutura de teste. Cada teste monta sua própria',
      '// árvore mínima, sempre com nomes únicos (Date.now()/Math.random()) pra não',
      '// colidir entre execuções.',
      'describe.skipIf(!process.env.DATABASE_URL)(',
      "  'requireResource (integração real, precisa de DATABASE_URL)',",
      '  () => {',
      '    let tenantId: string;',
      '    // Todo Tenant/Module criado durante o teste (inclusive o `tenantB` dos',
      '    // cenários de isolamento) — limpos no afterEach pra não acumular linhas',
      '    // órfãs no Postgres compartilhado do Laboratório Integrit (achado do retro',
      '    // do Épico 3: Module/Resource são globais, então cada rodada desta suíte',
      '    // sem limpeza deixava um Module novo pra sempre na árvore).',
      '    let createdTenantIds: string[];',
      '    let createdModuleIds: string[];',
      '',
      '    beforeEach(async () => {',
      '      const tenant = await prisma.tenant.create({',
      '        data: { name: `tenant-${Date.now()}-${Math.random()}` },',
      '      });',
      '      tenantId = tenant.id;',
      '      createdTenantIds = [tenantId];',
      '      createdModuleIds = [];',
      '    });',
      '',
      '    afterEach(async () => {',
      '      // Ordem importa: RoleAssignment/Role/Group/User referenciam Tenant sem',
      '      // onDelete: Cascade, e Resource/ModuleClosure referenciam Module — apagar',
      '      // Tenant/Module direto violaria a FK.',
      '      for (const id of createdTenantIds) {',
      '        await prisma.roleAssignment.deleteMany({ where: { tenantId: id } });',
      '        await prisma.role.deleteMany({ where: { tenantId: id } });',
      '        await prisma.group.deleteMany({ where: { tenantId: id } });',
      '        await prisma.user.deleteMany({ where: { tenantId: id } });',
      '      }',
      '      for (const id of createdModuleIds) {',
      '        await prisma.resource.deleteMany({ where: { moduleId: id } });',
      '        await prisma.moduleClosure.deleteMany({',
      '          where: { OR: [{ ancestorId: id }, { descendantId: id }] },',
      '        });',
      '      }',
      '      for (const id of createdModuleIds) {',
      '        await prisma.module.delete({ where: { id } });',
      '      }',
      '      for (const id of createdTenantIds) {',
      '        await prisma.tenant.delete({ where: { id } });',
      '      }',
      '    });',
      '',
      '    // Module é global (não leva tenantId) — reconciliação pós-review da Story 3.1.',
      '    async function makeModule(slug: string) {',
      '      const mod = await prisma.module.create({ data: { slug, name: slug } });',
      '      createdModuleIds.push(mod.id);',
      '      return mod;',
      '    }',
      '',
      '    // generate module (Story 3.2) faz isso de verdade, atômico com o codegen',
      '    // (AD-6); aqui é só fixture de teste.',
      '    async function closeSelf(moduleId: string) {',
      '      await prisma.moduleClosure.create({',
      '        data: { ancestorId: moduleId, descendantId: moduleId, depth: 0 },',
      '      });',
      '    }',
      '',
      '    async function closeAncestor(',
      '      ancestorId: string,',
      '      descendantId: string,',
      '      depth: number,',
      '    ) {',
      '      await prisma.moduleClosure.create({',
      '        data: { ancestorId, descendantId, depth },',
      '      });',
      '    }',
      '',
      '    async function makeResource(moduleId: string) {',
      '      return prisma.resource.create({',
      '        data: { moduleId, name: `resource-${Date.now()}-${Math.random()}` },',
      '      });',
      '    }',
      '',
      '    async function makeRole(resourceIds: string[]) {',
      '      return prisma.role.create({',
      '        data: {',
      '          tenantId,',
      "          name: 'test-role',",
      '          resources: { connect: resourceIds.map((id) => ({ id })) },',
      '        },',
      '      });',
      '    }',
      '',
      '    async function makeUser() {',
      '      return prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `user-${Date.now()}-${Math.random()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '    }',
      '',
      '    // Mesmo padrão de router.createCaller já usado em auth/router.test.ts',
      '    // (Stories 2.1/2.2) — não reimplementa a chamada do middleware, exercita',
      '    // a coisa real através do jeito real de invocar tRPC.',
      '    function callWithResource(resourceId: string, ctx: Context) {',
      '      const testRouter = router({',
      '        check: publicProcedure',
      '          .use(requireResource(resourceId))',
      "          .query(() => 'ok' as const),",
      '      });',
      '      return testRouter.createCaller(ctx).check();',
      '    }',
      '',
      "    it('usuário com RoleAssignment direto no módulo do recurso é permitido', async () => {",
      '      const mod = await makeModule(`orders-${Date.now()}`);',
      '      await closeSelf(mod.id);',
      '      const resource = await makeResource(mod.id);',
      '      const role = await makeRole([resource.id]);',
      '      const user = await makeUser();',
      '      await prisma.roleAssignment.create({',
      '        data: {',
      '          tenantId,',
      '          userId: user.id,',
      '          roleId: role.id,',
      '          targetModuleId: mod.id,',
      '        },',
      '      });',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId },',
      '      });',
      '',
      '      await expect(callWithResource(resource.name, ctx)).resolves.toBe(',
      "        'ok',",
      '      );',
      '    });',
      '',
      "    it('usuário com RoleAssignment num módulo ancestral é permitido (herança, FR-12)', async () => {",
      '      const parent = await makeModule(`parent-${Date.now()}`);',
      '      const child = await makeModule(`child-${Date.now()}`);',
      '      await closeSelf(parent.id);',
      '      await closeSelf(child.id);',
      '      await closeAncestor(parent.id, child.id, 1);',
      '      const resource = await makeResource(child.id);',
      '      const role = await makeRole([resource.id]);',
      '      const user = await makeUser();',
      '      await prisma.roleAssignment.create({',
      '        data: {',
      '          tenantId,',
      '          userId: user.id,',
      '          roleId: role.id,',
      '          targetModuleId: parent.id,',
      '        },',
      '      });',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId },',
      '      });',
      '',
      '      await expect(callWithResource(resource.name, ctx)).resolves.toBe(',
      "        'ok',",
      '      );',
      '    });',
      '',
      "    it('usuário com RoleAssignment num módulo descendente é negado (herança só desce, nunca sobe)', async () => {",
      '      const parent = await makeModule(`parent-${Date.now()}`);',
      '      const child = await makeModule(`child-${Date.now()}`);',
      '      await closeSelf(parent.id);',
      '      await closeSelf(child.id);',
      '      await closeAncestor(parent.id, child.id, 1);',
      '      // Resource no PAI, atribuição no FILHO — não deve cobrir.',
      '      const resource = await makeResource(parent.id);',
      '      const role = await makeRole([resource.id]);',
      '      const user = await makeUser();',
      '      await prisma.roleAssignment.create({',
      '        data: {',
      '          tenantId,',
      '          userId: user.id,',
      '          roleId: role.id,',
      '          targetModuleId: child.id,',
      '        },',
      '      });',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId },',
      '      });',
      '',
      '      await expect(callWithResource(resource.name, ctx)).rejects.toMatchObject(',
      "        { code: 'FORBIDDEN' },",
      '      );',
      '    });',
      '',
      "    it('usuário com RoleAssignment num módulo irmão é negado (não atravessa a árvore)', async () => {",
      '      const parent = await makeModule(`parent-${Date.now()}`);',
      '      const childA = await makeModule(`child-a-${Date.now()}`);',
      '      const childB = await makeModule(`child-b-${Date.now()}`);',
      '      await closeSelf(parent.id);',
      '      await closeSelf(childA.id);',
      '      await closeSelf(childB.id);',
      '      await closeAncestor(parent.id, childA.id, 1);',
      '      await closeAncestor(parent.id, childB.id, 1);',
      '      const resource = await makeResource(childA.id);',
      '      const role = await makeRole([resource.id]);',
      '      const user = await makeUser();',
      '      await prisma.roleAssignment.create({',
      '        data: {',
      '          tenantId,',
      '          userId: user.id,',
      '          roleId: role.id,',
      '          targetModuleId: childB.id,',
      '        },',
      '      });',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId },',
      '      });',
      '',
      '      await expect(callWithResource(resource.name, ctx)).rejects.toMatchObject(',
      "        { code: 'FORBIDDEN' },",
      '      );',
      '    });',
      '',
      "    it('usuário sem nenhuma atribuição é negado', async () => {",
      '      const mod = await makeModule(`orders-${Date.now()}`);',
      '      await closeSelf(mod.id);',
      '      const resource = await makeResource(mod.id);',
      '      const user = await makeUser();',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId },',
      '      });',
      '',
      '      await expect(callWithResource(resource.name, ctx)).rejects.toMatchObject(',
      "        { code: 'FORBIDDEN' },",
      '      );',
      '    });',
      '',
      "    it('atribuição via Group (não direta no usuário) é permitida', async () => {",
      '      const mod = await makeModule(`orders-${Date.now()}`);',
      '      await closeSelf(mod.id);',
      '      const resource = await makeResource(mod.id);',
      '      const role = await makeRole([resource.id]);',
      '      const user = await makeUser();',
      '      const group = await prisma.group.create({',
      "        data: { tenantId, name: 'test-group', users: { connect: { id: user.id } } },",
      '      });',
      '      await prisma.roleAssignment.create({',
      '        data: {',
      '          tenantId,',
      '          groupId: group.id,',
      '          roleId: role.id,',
      '          targetModuleId: mod.id,',
      '        },',
      '      });',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId },',
      '      });',
      '',
      '      await expect(callWithResource(resource.name, ctx)).resolves.toBe(',
      "        'ok',",
      '      );',
      '    });',
      '',
      "    it('resourceId sem Resource correspondente é erro de configuração (INTERNAL_SERVER_ERROR)', async () => {",
      '      const user = await makeUser();',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId },',
      '      });',
      '',
      '      await expect(',
      "        callWithResource('nunca-existiu.acao', ctx),",
      "      ).rejects.toMatchObject({ code: 'INTERNAL_SERVER_ERROR' });",
      '    });',
      '',
      "    it('sem ctx.user é UNAUTHORIZED', async () => {",
      '      const mod = await makeModule(`orders-${Date.now()}`);',
      '      await closeSelf(mod.id);',
      '      const resource = await makeResource(mod.id);',
      '      const ctx = createTestContext();',
      '',
      '      await expect(callWithResource(resource.name, ctx)).rejects.toMatchObject(',
      "        { code: 'UNAUTHORIZED' },",
      '      );',
      '    });',
      '',
      "    it('Module/Resource compartilhados entre 2 tenants — RoleAssignment de um tenant nunca cobre usuário de outro, e cada tenant concede acesso de forma independente (isolamento multi-tenant real, achado do code review)', async () => {",
      '      const mod = await makeModule(`shared-${Date.now()}`);',
      '      await closeSelf(mod.id);',
      '      const resource = await makeResource(mod.id);',
      '',
      '      // Tenant A (o da beforeEach): RoleAssignment real, deve permitir.',
      '      const roleA = await makeRole([resource.id]);',
      '      const userA = await makeUser();',
      '      await prisma.roleAssignment.create({',
      '        data: {',
      '          tenantId,',
      '          userId: userA.id,',
      '          roleId: roleA.id,',
      '          targetModuleId: mod.id,',
      '        },',
      '      });',
      '',
      '      // Tenant B: instância inteira separada, usando o MESMO Module/Resource',
      '      // globais, ainda sem nenhuma RoleAssignment própria — deve ser negado mesmo',
      '      // com o recurso já liberado pro Tenant A.',
      '      const tenantB = await prisma.tenant.create({',
      '        data: { name: `tenant-b-${Date.now()}-${Math.random()}` },',
      '      });',
      '      createdTenantIds.push(tenantB.id);',
      '      const userB = await prisma.user.create({',
      '        data: {',
      '          tenantId: tenantB.id,',
      '          email: `user-b-${Date.now()}-${Math.random()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '      const ctxA = createTestContext({ user: { userId: userA.id, tenantId } });',
      '      const ctxBSemAcesso = createTestContext({',
      '        user: { userId: userB.id, tenantId: tenantB.id },',
      '      });',
      '',
      "      await expect(callWithResource(resource.name, ctxA)).resolves.toBe('ok');",
      '      await expect(',
      '        callWithResource(resource.name, ctxBSemAcesso),',
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '',
      '      // Tenant B concede acesso ao MESMO Resource global via a SUA PRÓPRIA Role —',
      '      // prova que o modelo global de Module/Resource funciona de verdade pra',
      '      // múltiplos tenants (o motivo real da reconciliação pós-review), não só que',
      '      // o isolamento nega por padrão.',
      '      const roleB = await prisma.role.create({',
      '        data: {',
      '          tenantId: tenantB.id,',
      "          name: 'test-role-b',",
      '          resources: { connect: { id: resource.id } },',
      '        },',
      '      });',
      '      await prisma.roleAssignment.create({',
      '        data: {',
      '          tenantId: tenantB.id,',
      '          userId: userB.id,',
      '          roleId: roleB.id,',
      '          targetModuleId: mod.id,',
      '        },',
      '      });',
      '      const ctxBComAcesso = createTestContext({',
      '        user: { userId: userB.id, tenantId: tenantB.id },',
      '      });',
      '',
      '      await expect(callWithResource(resource.name, ctxBComAcesso)).resolves.toBe(',
      "        'ok',",
      '      );',
      '    });',
      '  },',
      ');',
      '',
    ].join('\n'),
  };
}
