export function buildAuthFiles(): Record<string, string> {
  return {
    // --- SecretsProvider (FR-26, AC #2) — porta + adapter local. Pepper do Argon2id ---
    // (FR-8) e chave de assinatura JWT (jose) são lidos exclusivamente por aqui.
    'src/core/secrets/secrets-provider.ts': [
      'export interface SecretsProvider {',
      '  getSecret(key: string): string;',
      '}',
      '',
    ].join('\n'),

    'src/core/secrets/env-secrets-provider.ts': [
      "import type { SecretsProvider } from './secrets-provider.js';",
      '',
      '// Erro explícito se a chave não existir — nunca retorna undefined silenciosamente',
      '// (um segredo ausente tem que quebrar o boot do servidor, não virar `undefined`',
      '// silenciosamente propagado até o Argon2id/jose em runtime).',
      'export class EnvSecretsProvider implements SecretsProvider {',
      '  getSecret(key: string): string {',
      '    const value = process.env[key];',
      "    if (value === undefined || value === '') {",
      '      throw new Error(',
      '        `Missing required secret: ${key} (set it via environment variable)`,',
      '      );',
      '    }',
      '    return value;',
      '  }',
      '}',
      '',
    ].join('\n'),

    // --- AuthProvider (FR-10, AC #1/#4) — porta + adapter local Argon2id ---
    'src/core/auth/auth-provider.ts': [
      'export interface AuthenticatedUser {',
      '  id: string;',
      '  tenantId: string;',
      '  email: string;',
      '  // Escopado ao próprio tenant — nunca um superusuário cross-tenant (Story 5.1).',
      '  isAdmin: boolean;',
      '}',
      '',
      '// Payload de um access token já verificado — mesmo shape assinado por',
      '// signAccessToken (core/auth/router.ts): sub (userId) + tenantId + isAdmin.',
      'export interface VerifiedToken {',
      '  userId: string;',
      '  tenantId: string;',
      '  isAdmin: boolean;',
      '}',
      '',
      'export interface AuthProvider {',
      '  hash(password: string): Promise<string>;',
      '  // Retorna null tanto pra "usuário não existe" quanto pra "senha errada" — nunca',
      '  // diferencia os dois casos (defesa contra enumeração de usuário, AC #9). A decisão',
      '  // de qual mensagem de erro genérica mostrar fica na procedure `login`, não aqui.',
      '  authenticate(',
      '    email: string,',
      '    password: string,',
      '    tenantId: string,',
      '  ): Promise<AuthenticatedUser | null>;',
      '  // Zero Trust interno (NFR2/§8.1, Story 2.1 AC #10) — todo consumo de access token',
      '  // passa por aqui, `algorithms` sempre fixado explicitamente, nunca confiando no',
      '  // `alg` do próprio token. Retorna null pra qualquer token inválido/expirado/',
      '  // malformado — nunca lança (mesmo formato uniforme dos outros métodos).',
      '  verifyToken(token: string): Promise<VerifiedToken | null>;',
      '  // Story 4.2 — usado por requestPasswordReset pra checar se o email existe,',
      '  // SEM autenticar (nenhuma senha envolvida aqui). Nunca expõe passwordHash.',
      '  findUserByEmail(',
      '    tenantId: string,',
      '    email: string,',
      '  ): Promise<AuthenticatedUser | null>;',
      '  // Story 5.1 — usado por `refresh` pra RE-DERIVAR `isAdmin` fresco do banco a',
      '  // cada novo access token, nunca confiando num claim antigo (o refresh token',
      '  // em si não carrega `isAdmin` — sem isso, revogar admin de alguém só teria',
      '  // efeito quando o refresh token expirasse, até 30 dias depois).',
      '  findUserById(userId: string): Promise<AuthenticatedUser | null>;',
      '  // Hasheia E persiste atomicamente — nunca expõe hash() + um update separado',
      '  // pro caller, pra manter a lógica de pepper/Argon2id inteira dentro do',
      '  // provider (Story 4.2, usado por resetPassword).',
      '  setPassword(userId: string, newPassword: string): Promise<void>;',
      '}',
      '',
    ].join('\n'),

    'src/core/auth/user-lookup.ts': [
      '// Estrutural, não o PrismaClient inteiro — Argon2AuthProvider só precisa deste',
      '// recorte (AD-5: pré-autenticação usa o Prisma Client direto, filtrado por',
      '// tenantId explícito). Evita apps/api depender do tipo completo de @prisma/client',
      '// só pra isso, e deixa o adapter trivial de testar com um stub.',
      'export interface UserRecord {',
      '  id: string;',
      '  tenantId: string;',
      '  email: string;',
      '  passwordHash: string;',
      '  isAdmin: boolean;',
      '}',
      '',
      'export interface UserLookup {',
      '  user: {',
      '    // Story 5.1 — `{ id }` adicionado pra `findUserById` (usado por `refresh`',
      '    // pra re-derivar `isAdmin` fresco); `{ tenantId_email }` continua servindo',
      '    // `authenticate`/`findUserByEmail`.',
      '    findUnique(args: {',
      '      where:',
      '        | { tenantId_email: { tenantId: string; email: string } }',
      '        | { id: string };',
      '    }): Promise<UserRecord | null>;',
      '    // Story 4.2 — usado por AuthProvider.setPassword(), nunca chamado direto',
      '    // por router.ts (mesmo princípio de findUnique acima).',
      '    update(args: {',
      '      where: { id: string };',
      '      data: { passwordHash: string };',
      '    }): Promise<UserRecord>;',
      '  };',
      '}',
      '',
    ].join('\n'),

    'src/core/auth/argon2-auth-provider.ts': [
      "import * as argon2 from 'argon2';",
      "import { jwtVerify } from 'jose';",
      "import type { SecretsProvider } from '../secrets/secrets-provider.js';",
      'import type {',
      '  AuthProvider,',
      '  AuthenticatedUser,',
      '  VerifiedToken,',
      "} from './auth-provider.js';",
      "import type { UserLookup } from './user-lookup.js';",
      '',
      '// Baseline OWASP "opção 2" pra Argon2id — os defaults da própria lib NÃO são isso',
      '// (default real: memoryCost:65536, timeCost:3, parallelism:4), por isso sempre',
      '// explícitos aqui, nunca confiando no default (AC #4).',
      'const ARGON2_OPTIONS = {',
      '  type: argon2.argon2id,',
      '  memoryCost: 19456,',
      '  timeCost: 2,',
      '  parallelism: 1,',
      '} as const;',
      '',
      '// Hash "isca" com o MESMO custo de ARGON2_OPTIONS, calculado uma única vez e',
      '// cacheado — usado só pra pagar o custo de um argon2.verify() real quando o',
      '// usuário não existe, mantendo o tempo de resposta equivalente ao caso "senha',
      '// errada". Sem isso, "usuário não existe" retorna rápido demais (sem nenhum',
      '// argon2.verify) e vaza a diferença via timing, apesar do corpo de erro ser',
      '// idêntico nos dois casos — o próprio oráculo que a AC #9 promete fechar.',
      '// Resultado sempre descartado, nunca comparado com nada real.',
      'let dummyHashPromise: Promise<string> | null = null;',
      'function getDummyHash(): Promise<string> {',
      '  dummyHashPromise ??= argon2.hash(',
      "    'dummy-password-constant-time-verify',",
      '    {',
      '      ...ARGON2_OPTIONS,',
      "      secret: Buffer.from('dummy-pepper-constant-time-verify'),",
      '    },',
      '  );',
      '  return dummyHashPromise;',
      '}',
      '',
      'export class Argon2AuthProvider implements AuthProvider {',
      '  constructor(',
      '    private readonly secrets: SecretsProvider,',
      '    private readonly db: UserLookup,',
      '  ) {}',
      '',
      '  async hash(password: string): Promise<string> {',
      "    const pepper = this.secrets.getSecret('ARGON2_PEPPER');",
      '    return argon2.hash(password, {',
      '      ...ARGON2_OPTIONS,',
      '      secret: Buffer.from(pepper),',
      '    });',
      '  }',
      '',
      '  async authenticate(',
      '    email: string,',
      '    password: string,',
      '    tenantId: string,',
      '  ): Promise<AuthenticatedUser | null> {',
      '    const user = await this.db.user.findUnique({',
      '      where: { tenantId_email: { tenantId, email } },',
      '    });',
      '    if (!user) {',
      '      const dummy = await getDummyHash();',
      '      await argon2',
      '        .verify(dummy, password, {',
      "          secret: Buffer.from('dummy-pepper-constant-time-verify'),",
      '        })',
      '        .catch(() => false);',
      '      return null;',
      '    }',
      '',
      "    const pepper = this.secrets.getSecret('ARGON2_PEPPER');",
      '    const ok = await argon2',
      '      .verify(user.passwordHash, password, { secret: Buffer.from(pepper) })',
      '      // Hash corrompido/malformado no banco lança em vez de retornar false —',
      '      // não pode virar um 500 não tratado quebrando a garantia de resposta',
      '      // uniforme da AC #9.',
      '      .catch(() => false);',
      '    if (!ok) {',
      '      return null;',
      '    }',
      '',
      '    return {',
      '      id: user.id,',
      '      tenantId: user.tenantId,',
      '      email: user.email,',
      '      isAdmin: user.isAdmin,',
      '    };',
      '  }',
      '',
      '  async verifyToken(token: string): Promise<VerifiedToken | null> {',
      '    try {',
      '      const key = new TextEncoder().encode(',
      "        this.secrets.getSecret('JWT_SIGNING_KEY'),",
      '      );',
      '      const { payload } = await jwtVerify(token, key, {',
      '        // Nunca confiar no `alg` do próprio token — fixado explicitamente',
      '        // (Zero Trust, NFR2/§8.1, Story 2.1 AC #10).',
      "        algorithms: ['HS256'],",
      '      });',
      '      if (',
      "        typeof payload.sub !== 'string' ||",
      "        typeof payload.tenantId !== 'string' ||",
      "        typeof payload.isAdmin !== 'boolean'",
      '      ) {',
      '        return null;',
      '      }',
      '      return {',
      '        userId: payload.sub,',
      '        tenantId: payload.tenantId,',
      '        isAdmin: payload.isAdmin,',
      '      };',
      '    } catch {',
      '      // Assinatura inválida, token expirado, alg divergente, malformado — tudo',
      '      // cai aqui. Nunca lança, mesmo formato uniforme dos outros métodos.',
      '      return null;',
      '    }',
      '  }',
      '',
      '  async findUserByEmail(',
      '    tenantId: string,',
      '    email: string,',
      '  ): Promise<AuthenticatedUser | null> {',
      '    const user = await this.db.user.findUnique({',
      '      where: { tenantId_email: { tenantId, email } },',
      '    });',
      '    return user',
      '      ? {',
      '          id: user.id,',
      '          tenantId: user.tenantId,',
      '          email: user.email,',
      '          isAdmin: user.isAdmin,',
      '        }',
      '      : null;',
      '  }',
      '',
      '  async findUserById(userId: string): Promise<AuthenticatedUser | null> {',
      '    const user = await this.db.user.findUnique({ where: { id: userId } });',
      '    return user',
      '      ? {',
      '          id: user.id,',
      '          tenantId: user.tenantId,',
      '          email: user.email,',
      '          isAdmin: user.isAdmin,',
      '        }',
      '      : null;',
      '  }',
      '',
      '  async setPassword(userId: string, newPassword: string): Promise<void> {',
      '    const passwordHash = await this.hash(newPassword);',
      '    await this.db.user.update({ where: { id: userId }, data: { passwordHash } });',
      '  }',
      '}',
      '',
    ].join('\n'),

    'src/core/auth/argon2-auth-provider.test.ts': [
      "import { describe, it, expect, vi, afterEach, beforeEach } from 'vitest';",
      "import { SignJWT } from 'jose';",
      "import { EnvSecretsProvider } from '../secrets/env-secrets-provider.js';",
      "import { Argon2AuthProvider } from './argon2-auth-provider.js';",
      "import type { UserRecord } from './user-lookup.js';",
      '',
      "const PEPPER_KEY = 'ARGON2_PEPPER';",
      '',
      'afterEach(() => {',
      '  delete process.env[PEPPER_KEY];',
      '});',
      '',
      'function makeProvider(',
      '  users: UserRecord[],',
      "  pepper = 'test-pepper-not-for-real-use',",
      ') {',
      '  process.env[PEPPER_KEY] = pepper;',
      '  const secrets = new EnvSecretsProvider();',
      '  const db = {',
      '    user: {',
      '      findUnique: vi.fn(',
      '        async ({',
      '          where,',
      '        }: {',
      '          where:',
      '            | { tenantId_email: { tenantId: string; email: string } }',
      '            | { id: string };',
      '        }) => {',
      "          if ('id' in where) {",
      '            return users.find((u) => u.id === where.id) ?? null;',
      '          }',
      '          return (',
      '            users.find(',
      '              (u) =>',
      '                u.tenantId === where.tenantId_email.tenantId &&',
      '                u.email === where.tenantId_email.email,',
      '            ) ?? null',
      '          );',
      '        },',
      '      ),',
      '      update: vi.fn(',
      '        async ({',
      '          where,',
      '          data,',
      '        }: {',
      '          where: { id: string };',
      '          data: { passwordHash: string };',
      '        }) => {',
      '          const user = users.find((u) => u.id === where.id);',
      '          if (!user) {',
      "            throw new Error('not found');",
      '          }',
      '          user.passwordHash = data.passwordHash;',
      '          return user;',
      '        },',
      '      ),',
      '    },',
      '  };',
      '  return new Argon2AuthProvider(secrets, db);',
      '}',
      '',
      "describe('Argon2AuthProvider', () => {",
      "  it('hash+authenticate: credenciais corretas retornam o usuário (AC #1, #4)', async () => {",
      '    const provider = makeProvider([]);',
      "    const passwordHash = await provider.hash('correct-horse-battery-staple');",
      '    const db2 = makeProvider([',
      '      {',
      "        id: 'user-1',",
      "        tenantId: 'tenant-1',",
      "        email: 'ada@example.com',",
      '        passwordHash,',
      '        isAdmin: false,',
      '      },',
      '    ]);',
      '',
      '    const result = await db2.authenticate(',
      "      'ada@example.com',",
      "      'correct-horse-battery-staple',",
      "      'tenant-1',",
      '    );',
      '',
      '    expect(result).toEqual({',
      "      id: 'user-1',",
      "      tenantId: 'tenant-1',",
      "      email: 'ada@example.com',",
      '      isAdmin: false,',
      '    });',
      '  });',
      '',
      "  it('senha errada retorna null (AC #9 — mesmo formato do usuário inexistente)', async () => {",
      '    const provider = makeProvider([]);',
      "    const passwordHash = await provider.hash('correct-horse-battery-staple');",
      '    const db2 = makeProvider([',
      '      {',
      "        id: 'user-1',",
      "        tenantId: 'tenant-1',",
      "        email: 'ada@example.com',",
      '        passwordHash,',
      '        isAdmin: false,',
      '      },',
      '    ]);',
      '',
      '    const result = await db2.authenticate(',
      "      'ada@example.com',",
      "      'wrong-password',",
      "      'tenant-1',",
      '    );',
      '',
      '    expect(result).toBeNull();',
      '  });',
      '',
      "  it('usuário inexistente retorna null, mesmo formato de senha errada (AC #9)', async () => {",
      '    const provider = makeProvider([]);',
      '',
      '    const result = await provider.authenticate(',
      "      'ninguem@example.com',",
      "      'qualquer-senha',",
      "      'tenant-1',",
      '    );',
      '',
      '    expect(result).toBeNull();',
      '  });',
      '',
      "  it('nunca gera o mesmo hash duas vezes pra mesma senha (salt aleatório)', async () => {",
      '    const provider = makeProvider([]);',
      '',
      "    const hash1 = await provider.hash('same-password');",
      "    const hash2 = await provider.hash('same-password');",
      '',
      '    expect(hash1).not.toBe(hash2);',
      '  });',
      '',
      "  it('pepper participa de verdade do hash — authenticate falha se o pepper mudar (AC #4)', async () => {",
      '    // `hash.not.toContain(pepper)` (versão anterior deste teste) passaria mesmo',
      '    // que a opção `secret:` fosse silenciosamente removida da chamada a',
      '    // argon2.hash() — um encoded hash do Argon2id nunca contém o pepper como',
      '    // substring de qualquer forma. Prova de verdade: gerar o hash com um pepper,',
      '    // trocar o pepper (SecretsProvider ainda injetado, nunca hardcoded) e',
      '    // confirmar que a MESMA senha deixa de autenticar (achado do code review).',
      "    const originalPepperProvider = makeProvider([], 'pepper-original');",
      '    const passwordHash = await originalPepperProvider.hash(',
      "      'correct-horse-battery-staple',",
      '    );',
      '    const user: UserRecord = {',
      "      id: 'user-1',",
      "      tenantId: 'tenant-1',",
      "      email: 'ada@example.com',",
      '      passwordHash,',
      '      isAdmin: false,',
      '    };',
      '',
      "    const differentPepperProvider = makeProvider([user], 'pepper-diferente');",
      '    const result = await differentPepperProvider.authenticate(',
      "      'ada@example.com',",
      "      'correct-horse-battery-staple',",
      "      'tenant-1',",
      '    );',
      '',
      '    expect(result).toBeNull();',
      '  });',
      '});',
      '',
      "describe('Argon2AuthProvider.verifyToken (Story 3.1, AC #1 — fecha a AC #10 da Story 2.1)', () => {",
      "  const SIGNING_KEY = 'test-signing-key-not-for-real-use';",
      '',
      '  beforeEach(() => {',
      '    process.env.JWT_SIGNING_KEY = SIGNING_KEY;',
      '  });',
      '',
      '  afterEach(() => {',
      '    delete process.env.JWT_SIGNING_KEY;',
      '  });',
      '',
      "  it('token válido retorna userId/tenantId/isAdmin', async () => {",
      '    const provider = makeProvider([]);',
      '    const key = new TextEncoder().encode(SIGNING_KEY);',
      '    const token = await new SignJWT({',
      "      sub: 'user-1',",
      "      tenantId: 'tenant-1',",
      '      isAdmin: true,',
      '    })',
      "      .setProtectedHeader({ alg: 'HS256' })",
      '      .setIssuedAt()',
      "      .setExpirationTime('15m')",
      '      .sign(key);',
      '',
      '    const result = await provider.verifyToken(token);',
      '',
      '    expect(result).toEqual({',
      "      userId: 'user-1',",
      "      tenantId: 'tenant-1',",
      '      isAdmin: true,',
      '    });',
      '  });',
      '',
      "  it('token válido sem claim isAdmin (formato antigo/incompatível) retorna null', async () => {",
      '    const provider = makeProvider([]);',
      '    const key = new TextEncoder().encode(SIGNING_KEY);',
      "    const token = await new SignJWT({ sub: 'user-1', tenantId: 'tenant-1' })",
      "      .setProtectedHeader({ alg: 'HS256' })",
      '      .setIssuedAt()',
      "      .setExpirationTime('15m')",
      '      .sign(key);',
      '',
      '    expect(await provider.verifyToken(token)).toBeNull();',
      '  });',
      '',
      "  it('token expirado retorna null', async () => {",
      '    const provider = makeProvider([]);',
      '    const key = new TextEncoder().encode(SIGNING_KEY);',
      '    const now = Math.floor(Date.now() / 1000);',
      "    const token = await new SignJWT({ sub: 'user-1', tenantId: 'tenant-1' })",
      "      .setProtectedHeader({ alg: 'HS256' })",
      '      .setIssuedAt(now - 3600)',
      '      .setExpirationTime(now - 1)',
      '      .sign(key);',
      '',
      '    expect(await provider.verifyToken(token)).toBeNull();',
      '  });',
      '',
      "  it('token assinado com chave diferente retorna null', async () => {",
      '    const provider = makeProvider([]);',
      '    const wrongKey = new TextEncoder().encode(',
      "      'uma-chave-completamente-diferente-da-configurada',",
      '    );',
      "    const token = await new SignJWT({ sub: 'user-1', tenantId: 'tenant-1' })",
      "      .setProtectedHeader({ alg: 'HS256' })",
      '      .setIssuedAt()',
      "      .setExpirationTime('15m')",
      '      .sign(wrongKey);',
      '',
      '    expect(await provider.verifyToken(token)).toBeNull();',
      '  });',
      '',
      "  it('token assinado com alg diferente de HS256 é rejeitado mesmo com a chave certa (nunca confiar no alg do próprio token)', async () => {",
      '    const provider = makeProvider([]);',
      '    const key = new TextEncoder().encode(SIGNING_KEY);',
      "    const token = await new SignJWT({ sub: 'user-1', tenantId: 'tenant-1' })",
      "      .setProtectedHeader({ alg: 'HS384' })",
      '      .setIssuedAt()',
      "      .setExpirationTime('15m')",
      '      .sign(key);',
      '',
      '    expect(await provider.verifyToken(token)).toBeNull();',
      '  });',
      '',
      "  it('token malformado retorna null', async () => {",
      '    const provider = makeProvider([]);',
      '',
      "    expect(await provider.verifyToken('not-a-real-jwt')).toBeNull();",
      '  });',
      '',
      "  it('findUserByEmail: retorna o usuário sem passwordHash quando existe (Story 4.2)', async () => {",
      '    const provider = makeProvider([',
      '      {',
      "        id: 'user-1',",
      "        tenantId: 'tenant-1',",
      "        email: 'ada@example.com',",
      "        passwordHash: 'irrelevante-aqui',",
      '        isAdmin: false,',
      '      },',
      '    ]);',
      '',
      '    const user = await provider.findUserByEmail(',
      "      'tenant-1',",
      "      'ada@example.com',",
      '    );',
      '',
      '    expect(user).toEqual({',
      "      id: 'user-1',",
      "      tenantId: 'tenant-1',",
      "      email: 'ada@example.com',",
      '      isAdmin: false,',
      '    });',
      "    expect(user).not.toHaveProperty('passwordHash');",
      '  });',
      '',
      "  it('findUserByEmail: retorna null quando não existe (Story 4.2, mesma defesa de enumeração)', async () => {",
      '    const provider = makeProvider([]);',
      '',
      '    expect(',
      "      await provider.findUserByEmail('tenant-1', 'ninguem@example.com'),",
      '    ).toBeNull();',
      '  });',
      '',
      "  it('setPassword: hasheia com o pepper e persiste — authenticate com a senha nova funciona depois (Story 4.2)', async () => {",
      '    const provider = makeProvider([',
      '      {',
      "        id: 'user-1',",
      "        tenantId: 'tenant-1',",
      "        email: 'ada@example.com',",
      "        passwordHash: 'hash-antigo-irrelevante',",
      '        isAdmin: false,',
      '      },',
      '    ]);',
      '',
      "    await provider.setPassword('user-1', 'nova-senha-forte');",
      '',
      '    const authenticated = await provider.authenticate(',
      "      'ada@example.com',",
      "      'nova-senha-forte',",
      "      'tenant-1',",
      '    );',
      "    expect(authenticated?.id).toBe('user-1');",
      '  });',
      '',
      "  it('findUserById: retorna o usuário com isAdmin correto, sem passwordHash (Story 5.1)', async () => {",
      '    const provider = makeProvider([',
      '      {',
      "        id: 'user-1',",
      "        tenantId: 'tenant-1',",
      "        email: 'ada@example.com',",
      "        passwordHash: 'irrelevante-aqui',",
      '        isAdmin: true,',
      '      },',
      '    ]);',
      '',
      "    const user = await provider.findUserById('user-1');",
      '',
      '    expect(user).toEqual({',
      "      id: 'user-1',",
      "      tenantId: 'tenant-1',",
      "      email: 'ada@example.com',",
      '      isAdmin: true,',
      '    });',
      "    expect(user).not.toHaveProperty('passwordHash');",
      '  });',
      '',
      "  it('findUserById: retorna null quando o usuário não existe (Story 5.1)', async () => {",
      '    const provider = makeProvider([]);',
      '',
      "    expect(await provider.findUserById('user-inexistente')).toBeNull();",
      '  });',
      '});',
      '',
    ].join('\n'),

    // Compartilhado entre PrismaTokenRevocationStore e PrismaPasswordResetTokenStore
    // (Story 4.2) — extraído daqui em vez de duplicado, mesmo SHA-256-de-alta-entropia
    // pros dois casos (refresh token opaco E token de reset, ambos
    // crypto.randomBytes(32), nunca o pepper do Argon2id — ver comentário original).
    'src/core/auth/hash-token.ts': [
      '// SHA-256 puro do token bruto — determinístico (permite lookup por igualdade),',
      '// nunca o valor bruto persistido. NÃO é o mesmo mecanismo do pepper do Argon2id:',
      '// não tem HMAC/segredo nenhum, e só é seguro aqui porque a entrada já tem 256',
      '// bits de entropia própria (randomBytes(32), gerado por quem chama) — um SHA-256',
      '// puro seria inaceitável pra uma senha humana de baixa entropia, que é',
      '// exatamente o que o pepper protege.',
      "import { createHash } from 'node:crypto';",
      '',
      'export function hashToken(rawToken: string): string {',
      "  return createHash('sha256').update(rawToken).digest('base64url');",
      '}',
      '',
    ].join('\n'),

    // --- TokenRevocationStore (FR-9, AC #7) — mecanismo completo: tabela + issue + check + ---
    // revoke. Acionar revoke() a partir de um humano (logout, admin) fica pra story futura;
    // o mecanismo em si é pré-requisito estrutural do refresh funcionar (ver Dev Notes).
    'src/core/auth/token-revocation-store.ts': [
      '// Assinatura de um token válido — tudo que a procedure `refresh` (AC #8) precisa',
      '// pra emitir um novo access token sem uma segunda consulta.',
      'export interface TokenSubject {',
      '  userId: string;',
      '  tenantId: string;',
      '}',
      '',
      'export interface TokenRevocationStore {',
      '  // Gera um refresh token opaco novo (crypto.randomBytes(32) base64url) e persiste',
      '  // seu hash — nunca o valor bruto (Task 4.3). Retorna o valor bruto pro caller',
      '  // setar no cookie; depois disso, só o hash é conhecido pelo store.',
      '  issue(subject: TokenSubject, expiresAt: Date): Promise<string>;',
      '  // true quando revogado, expirado, OU desconhecido — a procedure `refresh` (AC #8)',
      '  // trata os três casos de forma idêntica (rejeita, sem diferenciar o motivo).',
      '  isRevoked(rawToken: string): Promise<boolean>;',
      '  revoke(rawToken: string): Promise<void>;',
      '  // Adição pragmática além do que a AC #7 nomeia literalmente (isRevoked/revoke) —',
      '  // a procedure `refresh` (AC #8) precisa saber PRA QUEM (userId) e de QUAL tenant',
      '  // emitir o novo access token; sem isso o mecanismo não fecha. tenantId é',
      '  // denormalizado no próprio RefreshToken (evita uma segunda consulta por User —',
      '  // achado durante a implementação da Task 6). Retorna null se o token for',
      '  // desconhecido, revogado OU expirado — MESMA checagem de `isRevoked`, feita',
      '  // aqui de novo (não só "depois de confirmar !isRevoked") pra `refresh` poder',
      '  // chamar só este método, numa única consulta, sem janela de TOCTOU entre duas',
      '  // chamadas separadas (achado do code review da Story 2.1).',
      '  getSubject(rawToken: string): Promise<TokenSubject | null>;',
      '  // "Acionar revoke() a partir de um humano (logout, admin)" — o gap que o',
      '  // comentário original desta interface já previa como story futura (ver',
      '  // cabeçalho do arquivo). Fechado pela Story 4.2: redefinição de senha invalida',
      '  // TODAS as sessões ativas do usuário de uma vez, não uma por uma via revoke().',
      '  // Idempotente — não reescreve revokedAt de tokens já revogados antes.',
      '  revokeAllForUser(userId: string): Promise<void>;',
      '}',
      '',
    ].join('\n'),

    'src/core/auth/refresh-token-store.ts': [
      '// Estrutural (mesmo racional de user-lookup.ts) — só o recorte que',
      '// PrismaTokenRevocationStore precisa do Prisma Client.',
      'export interface RefreshTokenRecord {',
      '  jti: string;',
      '  userId: string;',
      '  tenantId: string;',
      '  expiresAt: Date;',
      '  revokedAt: Date | null;',
      '}',
      '',
      'export interface RefreshTokenStore {',
      '  refreshToken: {',
      '    create(args: {',
      '      data: {',
      '        jti: string;',
      '        userId: string;',
      '        tenantId: string;',
      '        expiresAt: Date;',
      '      };',
      '    }): Promise<RefreshTokenRecord>;',
      '    findUnique(args: {',
      '      where: { jti: string };',
      '    }): Promise<RefreshTokenRecord | null>;',
      '    update(args: {',
      '      where: { jti: string };',
      '      data: { revokedAt: Date };',
      '    }): Promise<RefreshTokenRecord>;',
      '    // Story 4.2 — revogação em massa (revokeAllForUser), não token-a-token.',
      '    updateMany(args: {',
      '      where: { userId: string; revokedAt: null };',
      '      data: { revokedAt: Date };',
      '    }): Promise<{ count: number }>;',
      '  };',
      '}',
      '',
    ].join('\n'),

    'src/core/auth/prisma-token-revocation-store.ts': [
      "import { randomBytes } from 'node:crypto';",
      "import { hashToken } from './hash-token.js';",
      'import type {',
      '  TokenRevocationStore,',
      '  TokenSubject,',
      "} from './token-revocation-store.js';",
      "import type { RefreshTokenStore } from './refresh-token-store.js';",
      '',
      'export class PrismaTokenRevocationStore implements TokenRevocationStore {',
      '  constructor(private readonly db: RefreshTokenStore) {}',
      '',
      '  async issue(subject: TokenSubject, expiresAt: Date): Promise<string> {',
      "    const rawToken = randomBytes(32).toString('base64url');",
      '    await this.db.refreshToken.create({',
      '      data: {',
      '        jti: hashToken(rawToken),',
      '        userId: subject.userId,',
      '        tenantId: subject.tenantId,',
      '        expiresAt,',
      '      },',
      '    });',
      '    return rawToken;',
      '  }',
      '',
      '  async isRevoked(rawToken: string): Promise<boolean> {',
      '    const record = await this.db.refreshToken.findUnique({',
      '      where: { jti: hashToken(rawToken) },',
      '    });',
      '    if (!record) {',
      '      return true;',
      '    }',
      '    if (record.revokedAt !== null) {',
      '      return true;',
      '    }',
      '    return record.expiresAt.getTime() <= Date.now();',
      '  }',
      '',
      '  async revoke(rawToken: string): Promise<void> {',
      '    await this.db.refreshToken.update({',
      '      where: { jti: hashToken(rawToken) },',
      '      data: { revokedAt: new Date() },',
      '    });',
      '  }',
      '',
      '  async getSubject(rawToken: string): Promise<TokenSubject | null> {',
      '    const record = await this.db.refreshToken.findUnique({',
      '      where: { jti: hashToken(rawToken) },',
      '    });',
      '    if (!record) {',
      '      return null;',
      '    }',
      '    // Mesma checagem de revogado/expirado que isRevoked() faz — feita de novo',
      '    // aqui (não confiando num isRevoked() chamado antes, numa consulta',
      '    // separada) pra fechar a janela de TOCTOU entre as duas chamadas.',
      '    if (',
      '      record.revokedAt !== null ||',
      '      record.expiresAt.getTime() <= Date.now()',
      '    ) {',
      '      return null;',
      '    }',
      '    return { userId: record.userId, tenantId: record.tenantId };',
      '  }',
      '',
      '  async revokeAllForUser(userId: string): Promise<void> {',
      '    await this.db.refreshToken.updateMany({',
      '      where: { userId, revokedAt: null },',
      '      data: { revokedAt: new Date() },',
      '    });',
      '  }',
      '}',
      '',
    ].join('\n'),

    'src/core/auth/prisma-token-revocation-store.test.ts': [
      "import { describe, it, expect } from 'vitest';",
      "import { PrismaTokenRevocationStore } from './prisma-token-revocation-store.js';",
      'import type {',
      '  RefreshTokenStore,',
      '  RefreshTokenRecord,',
      "} from './refresh-token-store.js';",
      '',
      '// Expõe `rows` além da interface RefreshTokenStore (que os testes normais',
      '// consomem) — só o teste de "nunca persiste o valor bruto" (abaixo) precisa',
      '// inspecionar o que de fato foi gravado, sem reimplementar hashToken().',
      'function makeInMemoryStore(): RefreshTokenStore & {',
      '  rows: Map<string, RefreshTokenRecord>;',
      '} {',
      '  const rows = new Map<string, RefreshTokenRecord>();',
      '  return {',
      '    rows,',
      '    refreshToken: {',
      '      async create({ data }) {',
      '        const record: RefreshTokenRecord = { ...data, revokedAt: null };',
      '        rows.set(data.jti, record);',
      '        return record;',
      '      },',
      '      async findUnique({ where }) {',
      '        return rows.get(where.jti) ?? null;',
      '      },',
      '      async update({ where, data }) {',
      '        const existing = rows.get(where.jti);',
      '        if (!existing) {',
      "          throw new Error('not found');",
      '        }',
      '        const updated = { ...existing, ...data };',
      '        rows.set(where.jti, updated);',
      '        return updated;',
      '      },',
      '      async updateMany({ where, data }) {',
      '        let count = 0;',
      '        for (const [jti, record] of rows) {',
      '          if (record.userId === where.userId && record.revokedAt === null) {',
      '            rows.set(jti, { ...record, ...data });',
      '            count++;',
      '          }',
      '        }',
      '        return { count };',
      '      },',
      '    },',
      '  };',
      '}',
      '',
      "const SUBJECT = { userId: 'user-1', tenantId: 'tenant-1' };",
      '',
      "describe('PrismaTokenRevocationStore', () => {",
      "  it('issue+isRevoked: token recém-emitido não está revogado (AC #7)', async () => {",
      '    const store = new PrismaTokenRevocationStore(makeInMemoryStore());',
      '    const expiresAt = new Date(Date.now() + 60_000);',
      '',
      '    const rawToken = await store.issue(SUBJECT, expiresAt);',
      '',
      '    expect(await store.isRevoked(rawToken)).toBe(false);',
      '    expect(await store.getSubject(rawToken)).toEqual(SUBJECT);',
      '  });',
      '',
      "  it('nunca persiste o valor bruto do token (Task 4.3)', async () => {",
      '    const db = makeInMemoryStore();',
      '    const store = new PrismaTokenRevocationStore(db);',
      '',
      '    const rawToken = await store.issue(',
      '      SUBJECT,',
      '      new Date(Date.now() + 60_000),',
      '    );',
      '',
      '    // Busca por `jti: rawToken` sempre retorna null por construção (jti é',
      '    // SEMPRE hashToken(rawToken), nunca o valor bruto) — não prova nada sobre',
      '    // o que foi persistido. Inspeciona a linha de verdade em vez disso: seu',
      '    // `jti` não pode ser igual ao valor bruto devolvido ao caller (achado do',
      '    // code review — o teste anterior era vazio).',
      '    expect(db.rows.size).toBe(1);',
      '    for (const record of db.rows.values()) {',
      '      expect(record.jti).not.toBe(rawToken);',
      '    }',
      '  });',
      '',
      "  it('revoke: token revogado passa a reportar isRevoked=true e getSubject=null (AC #7, #8)', async () => {",
      '    const store = new PrismaTokenRevocationStore(makeInMemoryStore());',
      '    const rawToken = await store.issue(',
      '      SUBJECT,',
      '      new Date(Date.now() + 60_000),',
      '    );',
      '',
      '    await store.revoke(rawToken);',
      '',
      '    expect(await store.isRevoked(rawToken)).toBe(true);',
      '    // getSubject precisa revalidar revogado/expirado por conta própria — não',
      '    // só existência do registro — pra `refresh` poder chamar só este método',
      '    // sem depender de um isRevoked() prévio (evita TOCTOU, code review).',
      '    expect(await store.getSubject(rawToken)).toBeNull();',
      '  });',
      '',
      "  it('token expirado reporta isRevoked=true e getSubject=null mesmo sem revoke() explícito (AC #7, #8)', async () => {",
      '    const store = new PrismaTokenRevocationStore(makeInMemoryStore());',
      '    const rawToken = await store.issue(SUBJECT, new Date(Date.now() - 1000));',
      '',
      '    expect(await store.isRevoked(rawToken)).toBe(true);',
      '    expect(await store.getSubject(rawToken)).toBeNull();',
      '  });',
      '',
      "  it('token desconhecido reporta isRevoked=true (nunca foi emitido)', async () => {",
      '    const store = new PrismaTokenRevocationStore(makeInMemoryStore());',
      '',
      "    expect(await store.isRevoked('never-issued-token')).toBe(true);",
      "    expect(await store.getSubject('never-issued-token')).toBeNull();",
      '  });',
      '',
      "  it('revokeAllForUser invalida todos os tokens ativos do usuário, mas não toca em tokens de outro usuário (Story 4.2, FR-9)', async () => {",
      '    const db = makeInMemoryStore();',
      '    const store = new PrismaTokenRevocationStore(db);',
      '    const expiresAt = new Date(Date.now() + 60_000);',
      '    const tokenA1 = await store.issue(SUBJECT, expiresAt);',
      '    const tokenA2 = await store.issue(SUBJECT, expiresAt);',
      "    const otherUser = { userId: 'user-2', tenantId: 'tenant-1' };",
      '    const tokenB = await store.issue(otherUser, expiresAt);',
      '',
      '    await store.revokeAllForUser(SUBJECT.userId);',
      '',
      '    expect(await store.isRevoked(tokenA1)).toBe(true);',
      '    expect(await store.isRevoked(tokenA2)).toBe(true);',
      '    expect(await store.isRevoked(tokenB)).toBe(false);',
      '  });',
      '',
      "  it('revokeAllForUser é idempotente — não lança nem reescreve tokens já revogados antes', async () => {",
      '    const store = new PrismaTokenRevocationStore(makeInMemoryStore());',
      '    const rawToken = await store.issue(SUBJECT, new Date(Date.now() + 60_000));',
      '    await store.revoke(rawToken);',
      '',
      '    await expect(',
      '      store.revokeAllForUser(SUBJECT.userId),',
      '    ).resolves.toBeUndefined();',
      '    expect(await store.isRevoked(rawToken)).toBe(true);',
      '  });',
      '});',
      '',
    ].join('\n'),

    // --- PasswordResetTokenStore (FR-19, FR-9) — porta neutra (não amarrada a ---
    // "esqueci minha senha" especificamente), desenhada pra Epic 5 (FR-15, senha
    // inicial no import em lote) poder reaproveitar o mesmo mecanismo depois.
    'src/core/auth/password-reset-token-store.ts': [
      'export interface PasswordResetTokenStore {',
      '  // Gera um token opaco novo (crypto.randomBytes(32) base64url) e persiste só',
      '  // seu hash — nunca o valor bruto (mesmo padrão de RefreshToken). Retorna o',
      '  // valor bruto pro caller montar o link de email.',
      '  issue(userId: string, tenantId: string, expiresAt: Date): Promise<string>;',
      '  // Resolve E consome atomicamente — retorna o userId se o token era válido',
      '  // (existia, não expirado, não usado antes) e ACABOU de ser marcado como',
      '  // usado; null em qualquer outro caso (desconhecido, expirado, ou já usado),',
      '  // sem diferenciar o motivo (mesma defesa de erro genérico de AC #4).',
      '  consume(rawToken: string): Promise<string | null>;',
      '}',
      '',
    ].join('\n'),

    // Estrutural (mesmo racional de refresh-token-store.ts) — só o recorte que
    // PrismaPasswordResetTokenStore precisa do Prisma Client. Nome "Repository",
    // não "Store", pra não colidir com o nome da interface pública acima (diferente',
    // de RefreshTokenStore/TokenRevocationStore, que não colidem por acaso).
    'src/core/auth/password-reset-token-repository.ts': [
      'export interface PasswordResetTokenRecord {',
      '  id: string;',
      '  userId: string;',
      '  tenantId: string;',
      '  tokenHash: string;',
      '  expiresAt: Date;',
      '  usedAt: Date | null;',
      '  createdAt: Date;',
      '}',
      '',
      'export interface PasswordResetTokenRepository {',
      '  passwordResetToken: {',
      '    create(args: {',
      '      data: {',
      '        userId: string;',
      '        tenantId: string;',
      '        tokenHash: string;',
      '        expiresAt: Date;',
      '      };',
      '    }): Promise<PasswordResetTokenRecord>;',
      '    updateMany(args: {',
      '      where: {',
      '        tokenHash: string;',
      '        usedAt: null;',
      '        expiresAt: { gt: Date };',
      '      };',
      '      data: { usedAt: Date };',
      '    }): Promise<{ count: number }>;',
      '    findUnique(args: {',
      '      where: { tokenHash: string };',
      '    }): Promise<PasswordResetTokenRecord | null>;',
      '  };',
      '}',
      '',
    ].join('\n'),

    'src/core/auth/prisma-password-reset-token-store.ts': [
      "import { randomBytes } from 'node:crypto';",
      "import { hashToken } from './hash-token.js';",
      "import type { PasswordResetTokenStore } from './password-reset-token-store.js';",
      "import type { PasswordResetTokenRepository } from './password-reset-token-repository.js';",
      '',
      'export class PrismaPasswordResetTokenStore',
      '  implements PasswordResetTokenStore',
      '{',
      '  constructor(private readonly db: PasswordResetTokenRepository) {}',
      '',
      '  async issue(',
      '    userId: string,',
      '    tenantId: string,',
      '    expiresAt: Date,',
      '  ): Promise<string> {',
      "    const rawToken = randomBytes(32).toString('base64url');",
      '    await this.db.passwordResetToken.create({',
      '      data: { userId, tenantId, tokenHash: hashToken(rawToken), expiresAt },',
      '    });',
      '    return rawToken;',
      '  }',
      '',
      '  async consume(rawToken: string): Promise<string | null> {',
      '    const tokenHash = hashToken(rawToken);',
      '    // Atômico: UPDATE ... WHERE usedAt IS NULL AND expiresAt > now() é uma',
      '    // única operação no banco — duas chamadas concorrentes com o MESMO token',
      '    // nunca conseguem count===1 as duas (Postgres serializa updates na mesma',
      '    // linha; a segunda vê usedAt já setado pela primeira e não casa o WHERE',
      '    // depois que a primeira commita). Sem essa atomicidade, "checa depois usa"',
      '    // em dois passos abriria uma janela de TOCTOU (mesma classe de achado já',
      '    // corrigido em getSubject, Story 2.1).',
      '    const result = await this.db.passwordResetToken.updateMany({',
      '      where: { tokenHash, usedAt: null, expiresAt: { gt: new Date() } },',
      '      data: { usedAt: new Date() },',
      '    });',
      '    if (result.count !== 1) {',
      '      return null;',
      '    }',
      '    // Seguro: só chega aqui se o NOSSO updateMany venceu a corrida — este',
      '    // findUnique lê o estado que NÓS acabamos de commitar, nunca o de outra',
      '    // chamada concorrente (não há mais nenhuma condição de corrida a partir',
      '    // daqui, o token já está marcado como usado de verdade).',
      '    const record = await this.db.passwordResetToken.findUnique({',
      '      where: { tokenHash },',
      '    });',
      '    return record?.userId ?? null;',
      '  }',
      '}',
      '',
    ].join('\n'),

    'src/core/auth/prisma-password-reset-token-store.test.ts': [
      "import { describe, it, expect } from 'vitest';",
      "import { PrismaPasswordResetTokenStore } from './prisma-password-reset-token-store.js';",
      'import type {',
      '  PasswordResetTokenRepository,',
      '  PasswordResetTokenRecord,',
      "} from './password-reset-token-repository.js';",
      '',
      'function makeInMemoryStore(): PasswordResetTokenRepository & {',
      '  rows: Map<string, PasswordResetTokenRecord>;',
      '} {',
      '  const rows = new Map<string, PasswordResetTokenRecord>();',
      '  let nextId = 0;',
      '  return {',
      '    rows,',
      '    passwordResetToken: {',
      '      async create({ data }) {',
      '        const record: PasswordResetTokenRecord = {',
      '          id: `token-${(nextId++).toString()}`,',
      '          ...data,',
      '          usedAt: null,',
      '          createdAt: new Date(),',
      '        };',
      '        rows.set(data.tokenHash, record);',
      '        return record;',
      '      },',
      '      async updateMany({ where, data }) {',
      '        const existing = rows.get(where.tokenHash);',
      '        if (!existing) {',
      '          return { count: 0 };',
      '        }',
      '        const stillValid =',
      '          existing.usedAt === null &&',
      '          existing.expiresAt.getTime() > where.expiresAt.gt.getTime();',
      '        if (!stillValid) {',
      '          return { count: 0 };',
      '        }',
      '        rows.set(where.tokenHash, { ...existing, ...data });',
      '        return { count: 1 };',
      '      },',
      '      async findUnique({ where }) {',
      '        return rows.get(where.tokenHash) ?? null;',
      '      },',
      '    },',
      '  };',
      '}',
      '',
      "describe('PrismaPasswordResetTokenStore', () => {",
      "  it('issue+consume: token recém-emitido é consumido com sucesso, retornando o userId (AC #2, #5)', async () => {",
      '    const store = new PrismaPasswordResetTokenStore(makeInMemoryStore());',
      '    const rawToken = await store.issue(',
      "      'user-1',",
      "      'tenant-1',",
      '      new Date(Date.now() + 60_000),',
      '    );',
      '',
      "    expect(await store.consume(rawToken)).toBe('user-1');",
      '  });',
      '',
      "  it('consumir o mesmo token duas vezes falha na segunda (uso único de verdade, AC #5)', async () => {",
      '    const store = new PrismaPasswordResetTokenStore(makeInMemoryStore());',
      '    const rawToken = await store.issue(',
      "      'user-1',",
      "      'tenant-1',",
      '      new Date(Date.now() + 60_000),',
      '    );',
      '',
      '    await store.consume(rawToken);',
      '',
      '    expect(await store.consume(rawToken)).toBeNull();',
      '  });',
      '',
      "  it('token expirado não é consumido (AC #4)', async () => {",
      '    const store = new PrismaPasswordResetTokenStore(makeInMemoryStore());',
      '    const rawToken = await store.issue(',
      "      'user-1',",
      "      'tenant-1',",
      '      new Date(Date.now() - 1000),',
      '    );',
      '',
      '    expect(await store.consume(rawToken)).toBeNull();',
      '  });',
      '',
      "  it('token desconhecido não é consumido (AC #4)', async () => {",
      '    const store = new PrismaPasswordResetTokenStore(makeInMemoryStore());',
      '',
      "    expect(await store.consume('never-issued-token')).toBeNull();",
      '  });',
      '',
      "  it('nunca persiste o valor bruto do token, só o hash (AC #8)', async () => {",
      '    const db = makeInMemoryStore();',
      '    const store = new PrismaPasswordResetTokenStore(db);',
      '    const rawToken = await store.issue(',
      "      'user-1',",
      "      'tenant-1',",
      '      new Date(Date.now() + 60_000),',
      '    );',
      '',
      '    const persisted = [...db.rows.values()];',
      '    expect(persisted).toHaveLength(1);',
      '    expect(persisted[0]?.tokenHash).not.toBe(rawToken);',
      '  });',
      '});',
      '',
    ].join('\n'),

    // --- Composição única (AD-4, AC #3) — só este arquivo instancia as classes concretas ---
    'src/core/providers.ts': [
      "import { prisma } from 'db/client';",
      "import { EnvSecretsProvider } from './secrets/env-secrets-provider.js';",
      "import { Argon2AuthProvider } from './auth/argon2-auth-provider.js';",
      "import { PrismaTokenRevocationStore } from './auth/prisma-token-revocation-store.js';",
      "import { PrismaRateLimiter } from './auth/prisma-rate-limiter.js';",
      "import { SmtpEmailProvider } from './notifications/smtp-email-provider.js';",
      "import { PrismaPasswordResetTokenStore } from './auth/prisma-password-reset-token-store.js';",
      "import type { SecretsProvider } from './secrets/secrets-provider.js';",
      "import type { AuthProvider } from './auth/auth-provider.js';",
      "import type { TokenRevocationStore } from './auth/token-revocation-store.js';",
      "import type { RateLimiter } from './auth/rate-limiter.js';",
      "import type { EmailProvider } from './notifications/email-provider.js';",
      "import type { PasswordResetTokenStore } from './auth/password-reset-token-store.js';",
      '',
      '// Único arquivo que instancia as classes concretas (AD-4) — código consumidor',
      '// (router.ts, etc.) só importa o TIPO da interface, a instância chega via ctx.',
      'export const secretsProvider: SecretsProvider = new EnvSecretsProvider();',
      'export const authProvider: AuthProvider = new Argon2AuthProvider(',
      '  secretsProvider,',
      '  prisma,',
      ');',
      'export const tokenRevocationStore: TokenRevocationStore =',
      '  new PrismaTokenRevocationStore(prisma);',
      '// Mesma instância reaproveitada por login (Story 2.2) e, no futuro, redefinição',
      '// de senha (Epic 4) — nunca uma segunda implementação paralela (AD-10).',
      'export const rateLimiter: RateLimiter = new PrismaRateLimiter(prisma);',
      '// Única implementação do MVP (FR-18) — em dev aponta pro Mailpit (Story 1.1,',
      '// docker-compose.dev.yml) via as mesmas env vars. Um relay SMTP real de',
      '// produção (fora do escopo do MVP, AD-9) reaproveitaria host/port/from, mas',
      '// `SmtpEmailProviderOptions` hoje não tem TLS/autenticação — adotar um relay',
      '// real exigiria estender a classe, não só mudar valores aqui (achado real',
      '// do code review desta story).',
      'export const emailProvider: EmailProvider = new SmtpEmailProvider({',
      "  host: process.env.SMTP_HOST ?? 'localhost',",
      '  port: Number(process.env.MAILPIT_SMTP_PORT ?? 1025),',
      "  from: process.env.EMAIL_FROM ?? 'no-reply@aether.local',",
      '});',
      '// Porta neutra (não amarrada a "esqueci minha senha") — Epic 5 (FR-15)',
      '// reaproveita a mesma instância pra senha inicial do import em lote.',
      'export const passwordResetTokenStore: PasswordResetTokenStore =',
      '  new PrismaPasswordResetTokenStore(prisma);',
      '',
    ].join('\n'),

    // --- Procedures login/refresh (AC #6, #8, #9, #10) — core/auth/router.ts NÃO é um ---
    // módulo Hexagonal (AD-1 não se aplica a core/), ver Dev Notes.
    'src/core/auth/router.ts': [
      "import { SignJWT } from 'jose';",
      "import { TRPCError } from '@trpc/server';",
      'import {',
      '  loginInputSchema,',
      '  loginOutputSchema,',
      '  refreshOutputSchema,',
      '  requestPasswordResetInputSchema,',
      '  resetPasswordInputSchema,',
      "} from 'shared/schemas/auth';",
      "import { publicProcedure, router } from '../../trpc.js';",
      "import type { SecretsProvider } from '../secrets/secrets-provider.js';",
      '',
      "const ACCESS_TOKEN_TTL = '15m';",
      '// 30 dias — mesmo valor do `maxAge` do cookie (server.ts registra @fastify/cookie;',
      '// o valor de fato é setado aqui, na procedure login, não lá).',
      'const REFRESH_TOKEN_TTL_MS = 30 * 24 * 60 * 60 * 1000;',
      '// Expiração "configurável" (FR-19) — constante nomeada, não mágica, mesmo',
      '// padrão de ACCESS_TOKEN_TTL/REFRESH_TOKEN_TTL_MS acima (não env-configurável,',
      '// mesma decisão de design já tomada pros outros dois).',
      'const PASSWORD_RESET_TOKEN_TTL_MS = 60 * 60 * 1000;',
      '',
      '// AC #9: usuário inexistente e senha errada produzem O MESMO erro — não são dois',
      '// `throw` com mensagens parecidas, é literalmente o mesmo objeto pros dois casos',
      '// (AuthProvider.authenticate já retorna null uniformemente pra ambos — a decisão',
      '// de não diferenciar foi tomada lá, não aqui).',
      "const INVALID_CREDENTIALS_MESSAGE = 'Email ou senha inválidos.';",
      '',
      'async function signAccessToken(',
      '  secretsProvider: SecretsProvider,',
      '  userId: string,',
      '  tenantId: string,',
      '  isAdmin: boolean,',
      '): Promise<string> {',
      '  const key = new TextEncoder().encode(',
      "    secretsProvider.getSecret('JWT_SIGNING_KEY'),",
      '  );',
      '  return new SignJWT({ sub: userId, tenantId, isAdmin })',
      "    .setProtectedHeader({ alg: 'HS256' })",
      '    .setIssuedAt()',
      '    .setExpirationTime(ACCESS_TOKEN_TTL)',
      '    .sign(key);',
      '}',
      '',
      'export const authRouter = router({',
      '  login: publicProcedure',
      '    .input(loginInputSchema)',
      '    .output(loginOutputSchema)',
      '    .mutation(async ({ input, ctx }) => {',
      '      const identity = {',
      '        tenantId: input.tenantId,',
      '        email: input.email,',
      '        ip: ctx.req.ip,',
      '      };',
      '',
      '      // Checa ANTES de autenticar (Story 2.2, AC #4) — não desperdiça um Argon2id',
      '      // inteiro num identificador já bloqueado. RateLimiter.isBlocked() nunca',
      '      // diferencia se o email existe ou não — só opera sobre a string do',
      '      // identificador (AC #6, mesma defesa contra enumeração da AC #9).',
      '      let blocked: boolean;',
      '      try {',
      '        blocked = await ctx.rateLimiter.isBlocked(identity);',
      '      } catch (err) {',
      '        // Fail-closed: se não dá pra confirmar que o identificador NÃO está',
      '        // bloqueado (RateLimitHit/Postgres indisponível), trata como bloqueado —',
      '        // protege contra força bruta mesmo com o rate limiter fora do ar, em vez',
      '        // de deixar a exceção crua propagar como um 500 não estruturado (achado do',
      '        // code review). Mesma mensagem genérica do bloqueio normal — não',
      "        // diferenciar 'bloqueado de verdade' de 'rate limiter indisponível' evita",
      '        // vazar informação sobre o estado interno da infraestrutura.',
      '        ctx.req.log.error(',
      '          { err },',
      "          'rate limiter indisponível — login fail-closed',",
      '        );',
      '        blocked = true;',
      '      }',
      '      if (blocked) {',
      '        throw new TRPCError({',
      "          code: 'TOO_MANY_REQUESTS',",
      "          message: 'Muitas tentativas. Tente novamente mais tarde.',",
      '        });',
      '      }',
      '',
      '      const user = await ctx.authProvider.authenticate(',
      '        input.email,',
      '        input.password,',
      '        input.tenantId,',
      '      );',
      '      if (!user) {',
      '        // Só credenciais inválidas contam pro limite (Story 2.2, AC #5) — nunca',
      '        // chamado no caminho de sucesso, abaixo. Falha ao registrar (`.catch`)',
      '        // não pode mascarar o 401 pretendido com um 500 -- a decisão de',
      '        // segurança (credenciais inválidas) já foi tomada; o registro é',
      '        // housekeeping, não deveria mudar a resposta que o cliente recebe.',
      '        await ctx.rateLimiter.recordFailure(identity).catch((err: unknown) => {',
      '          ctx.req.log.error(',
      '            { err },',
      "            'falha ao registrar tentativa no rate limiter',",
      '          );',
      '        });',
      '        throw new TRPCError({',
      "          code: 'UNAUTHORIZED',",
      '          message: INVALID_CREDENTIALS_MESSAGE,',
      '        });',
      '      }',
      '',
      '      const accessToken = await signAccessToken(',
      '        ctx.secretsProvider,',
      '        user.id,',
      '        user.tenantId,',
      '        user.isAdmin,',
      '      );',
      '      const refreshToken = await ctx.tokenRevocationStore.issue(',
      '        { userId: user.id, tenantId: user.tenantId },',
      '        new Date(Date.now() + REFRESH_TOKEN_TTL_MS),',
      '      );',
      '',
      "      ctx.res.setCookie('refresh_token', refreshToken, {",
      '        httpOnly: true,',
      "        sameSite: 'strict',",
      '        // pnpm dev local não tem TLS — hardcoded `true` quebraria login no único',
      '        // ambiente que este MVP alvo (AD-9). Ver AC #6.',
      "        secure: process.env.NODE_ENV === 'production',",
      "        path: '/',",
      '        maxAge: REFRESH_TOKEN_TTL_MS / 1000,',
      '      });',
      '',
      '      return { accessToken };',
      '    }),',
      '',
      '  refresh: publicProcedure',
      '    .output(refreshOutputSchema)',
      '    .mutation(async ({ ctx }) => {',
      '      const rawToken = ctx.req.cookies.refresh_token;',
      '      // Uma única consulta (getSubject já valida revogado/expirado por conta',
      '      // própria) — não isRevoked() seguido de getSubject() em duas chamadas',
      '      // separadas, que abriria uma janela de TOCTOU entre elas (achado do code',
      '      // review da Story 2.1).',
      '      const subject = rawToken',
      '        ? await ctx.tokenRevocationStore.getSubject(rawToken)',
      '        : null;',
      '      if (!subject) {',
      '        throw new TRPCError({',
      "          code: 'UNAUTHORIZED',",
      "          message: 'Refresh token inválido ou expirado.',",
      '        });',
      '      }',
      '',
      '      // RE-DERIVA isAdmin de uma consulta fresca ao User — nunca confia num',
      "      // claim antigo (o refresh token em si, via `subject`, não carrega",
      '      // `isAdmin`). Sem isso, revogar admin de alguém só teria efeito quando o',
      '      // refresh token expirasse, até 30 dias depois (Story 5.1, achado real).',
      '      const user = await ctx.authProvider.findUserById(subject.userId);',
      '      if (!user) {',
      '        throw new TRPCError({',
      "          code: 'UNAUTHORIZED',",
      "          message: 'Refresh token inválido ou expirado.',",
      '        });',
      '      }',
      '',
      '      const accessToken = await signAccessToken(',
      '        ctx.secretsProvider,',
      '        user.id,',
      '        user.tenantId,',
      '        user.isAdmin,',
      '      );',
      '',
      '      return { accessToken };',
      '    }),',
      '',
      '  // FR-19/FR-18 (Story 4.2) — resposta SEMPRE a mesma, email existindo ou não',
      '  // (AC #1, mesma defesa de enumeração da AC #9 do login acima). Mesmo',
      '  // RateLimiter/RateLimitIdentity de login (AD-10) — toda chamada processada',
      '  // conta pro limite, não só "falhas" (não existe esse conceito aqui).',
      '  requestPasswordReset: publicProcedure',
      '    .input(requestPasswordResetInputSchema)',
      '    .mutation(async ({ input, ctx }) => {',
      '      const identity = {',
      '        tenantId: input.tenantId,',
      '        email: input.email,',
      '        ip: ctx.req.ip,',
      '      };',
      '',
      '      let blocked: boolean;',
      '      try {',
      '        blocked = await ctx.rateLimiter.isBlocked(identity);',
      '      } catch (err) {',
      '        // Fail-closed — mesmo racional do login acima.',
      '        ctx.req.log.error(',
      '          { err },',
      "          'rate limiter indisponível — requestPasswordReset fail-closed',",
      '        );',
      '        blocked = true;',
      '      }',
      '      if (blocked) {',
      '        throw new TRPCError({',
      "          code: 'TOO_MANY_REQUESTS',",
      "          message: 'Muitas tentativas. Tente novamente mais tarde.',",
      '        });',
      '      }',
      '',
      '      const user = await ctx.authProvider.findUserByEmail(',
      '        input.tenantId,',
      '        input.email,',
      '      );',
      '      if (user) {',
      '        // Nunca deixar propagar — sem isso, um Mailpit/SMTP fora do ar faria o',
      '        // caminho "email existe" responder 500 enquanto "email não existe"',
      '        // responde sucesso, um sinal de enumeração muito mais forte que a',
      '        // diferença de timing (já aceita como risco residual, ver Dev Notes) —',
      '        // achado real do code review desta story.',
      '        try {',
      '          const rawToken = await ctx.passwordResetTokenStore.issue(',
      '            user.id,',
      '            user.tenantId,',
      '            new Date(Date.now() + PASSWORD_RESET_TOKEN_TTL_MS),',
      '          );',
      "          const resetLink = `${process.env.WEB_PUBLIC_URL ?? 'http://localhost:5173'}/reset-password?token=${rawToken}`;",
      '          await ctx.emailProvider.send({',
      "            template: 'password-reset',",
      '            to: user.email,',
      '            data: {',
      '              resetLink,',
      '              expiresInMinutes: PASSWORD_RESET_TOKEN_TTL_MS / 60_000,',
      '            },',
      '          });',
      '        } catch (err) {',
      '          ctx.req.log.error(',
      '            { err },',
      "            'falha ao emitir token ou enviar email de redefinição de senha',",
      '          );',
      '        }',
      '      }',
      '',
      '      // Toda chamada conta pro limite (AC #3) — nunca só quando o email existe,',
      '      // senão a própria resposta (rápida vs. com envio de email) vazaria a',
      '      // informação que a AC #1 promete esconder.',
      '      await ctx.rateLimiter.recordFailure(identity).catch((err: unknown) => {',
      '        ctx.req.log.error(',
      '          { err },',
      "          'falha ao registrar tentativa no rate limiter',",
      '        );',
      '      });',
      '    }),',
      '',
      '  // FR-19/FR-9 (Story 4.2) — token inválido/expirado/usado produz o MESMO erro',
      '  // genérico (AC #4), sem diferenciar o motivo.',
      '  resetPassword: publicProcedure',
      '    .input(resetPasswordInputSchema)',
      '    .mutation(async ({ input, ctx }) => {',
      '      const userId = await ctx.passwordResetTokenStore.consume(input.token);',
      '      if (!userId) {',
      '        throw new TRPCError({',
      "          code: 'BAD_REQUEST',",
      "          message: 'Link de redefinição inválido, expirado ou já utilizado.',",
      '        });',
      '      }',
      '',
      '      // Hash+persistência ANTES de revogar (AC #6, #7) — nunca invalidar sessões',
      '      // sem a senha nova já estar de fato salva.',
      '      await ctx.authProvider.setPassword(userId, input.newPassword);',
      '      await ctx.tokenRevocationStore.revokeAllForUser(userId);',
      '    }),',
      '});',
      '',
    ].join('\n'),

    'src/core/auth/router.test.ts': [
      "import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';",
      "import { TRPCError } from '@trpc/server';",
      "import { jwtVerify } from 'jose';",
      "import { getHTTPStatusCodeFromError } from '@trpc/server/http';",
      "import { authRouter } from './router.js';",
      "import { createTestContext } from '../../test-utils.js';",
      "import { buildProblemDetails } from '../../trpc.js';",
      "import { PrismaRateLimiter } from './prisma-rate-limiter.js';",
      "import type { AuthProvider } from './auth-provider.js';",
      "import type { TokenRevocationStore } from './token-revocation-store.js';",
      "import type { RateLimitStore, RateLimitHitRecord } from './rate-limit-store.js';",
      "import type { PasswordResetTokenStore } from './password-reset-token-store.js';",
      "import type { EmailProvider } from '../notifications/email-provider.js';",
      "import { PrismaTokenRevocationStore } from './prisma-token-revocation-store.js';",
      'import type {',
      '  RefreshTokenStore,',
      '  RefreshTokenRecord,',
      "} from './refresh-token-store.js';",
      '',
      '// Reproduz o que o errorFormatter real (src/trpc.ts) faria com este erro — mesma',
      '// função de mapeamento de status que o adapter tRPC usa de verdade — pra poder',
      '// comparar o envelope RFC 9457 final, não só `TRPCError.code`/`.message` cru.',
      'function toProblemDetails(error: TRPCError) {',
      '  return buildProblemDetails(',
      '    { message: error.message, data: { httpStatus: getHTTPStatusCodeFromError(error) } },',
      '    { cause: error.cause },',
      '  );',
      '}',
      '',
      'function makeFakeAuthProvider(',
      '  overrides: Partial<AuthProvider> = {},',
      '): AuthProvider {',
      '  return {',
      '    hash: vi.fn(async (p: string) => `hashed:${p}`),',
      '    authenticate: vi.fn(async () => null),',
      '    // default null — testes de core/authz (Story 3.1) que precisam de um',
      '    // usuário autenticado sobrescrevem via overrides.verifyToken.',
      '    verifyToken: vi.fn(async () => null),',
      '    // default null (email desconhecido) — Story 4.2 sobrescreve via',
      '    // overrides.findUserByEmail quando precisa simular um usuário real.',
      '    findUserByEmail: vi.fn(async () => null),',
      '    // default retorna um usuário não-admin com o MESMO userId que',
      "    // `makeFakeStore().getSubject()` usa ('user-1') — sem isso, `refresh`",
      '    // (que agora chama findUserById) quebraria em todo teste existente que',
      '    // nunca pensou em sobrescrever isso (Story 5.1).',
      '    findUserById: vi.fn(async () => ({',
      "      id: 'user-1',",
      "      tenantId: 'tenant-1',",
      "      email: 'ada@example.com',",
      '      isAdmin: false,',
      '    })),',
      '    setPassword: vi.fn(async () => undefined),',
      '    ...overrides,',
      '  };',
      '}',
      '',
      'function makeFakeStore(',
      '  overrides: Partial<TokenRevocationStore> = {},',
      '): TokenRevocationStore {',
      '  return {',
      "    issue: vi.fn(async () => 'raw-refresh-token'),",
      '    isRevoked: vi.fn(async () => false),',
      '    revoke: vi.fn(async () => undefined),',
      '    getSubject: vi.fn(async () => ({',
      "      userId: 'user-1',",
      "      tenantId: 'tenant-1',",
      '    })),',
      '    revokeAllForUser: vi.fn(async () => undefined),',
      '    ...overrides,',
      '  };',
      '}',
      '',
      '// Stateful, não um spy — usado só pelo teste de AC #7 que precisa provar o',
      '// EFEITO real de revokeAllForUser (um token antes válido virar inválido),',
      '// não só que o método foi chamado (achado do code review desta story). Mesma',
      '// forma de `makeInMemoryStore` em prisma-token-revocation-store.test.ts.',
      'function makeStatefulRefreshTokenStore(): RefreshTokenStore {',
      '  const rows = new Map<string, RefreshTokenRecord>();',
      '  return {',
      '    refreshToken: {',
      '      async create({ data }) {',
      '        const record: RefreshTokenRecord = { ...data, revokedAt: null };',
      '        rows.set(data.jti, record);',
      '        return record;',
      '      },',
      '      async findUnique({ where }) {',
      '        return rows.get(where.jti) ?? null;',
      '      },',
      '      async update({ where, data }) {',
      '        const existing = rows.get(where.jti);',
      '        if (!existing) {',
      "          throw new Error('not found');",
      '        }',
      '        const updated = { ...existing, ...data };',
      '        rows.set(where.jti, updated);',
      '        return updated;',
      '      },',
      '      async updateMany({ where, data }) {',
      '        let count = 0;',
      '        for (const [jti, record] of rows) {',
      '          if (record.userId === where.userId && record.revokedAt === null) {',
      '            rows.set(jti, { ...record, ...data });',
      '            count++;',
      '          }',
      '        }',
      '        return { count };',
      '      },',
      '    },',
      '  };',
      '}',
      '',
      '// Story 4.2 — mesmo racional de makeFakeStore acima.',
      'function makeFakePasswordResetTokenStore(',
      '  overrides: Partial<PasswordResetTokenStore> = {},',
      '): PasswordResetTokenStore {',
      '  return {',
      "    issue: vi.fn(async () => 'raw-reset-token'),",
      "    consume: vi.fn(async () => 'user-1'),",
      '    ...overrides,',
      '  };',
      '}',
      '',
      'function makeFakeEmailProvider(',
      '  overrides: Partial<EmailProvider> = {},',
      '): EmailProvider {',
      '  return {',
      '    send: vi.fn(async () => undefined),',
      '    ...overrides,',
      '  };',
      '}',
      '',
      '// `PrismaRateLimiter` real (não um mock manual) contra um fake em memória —',
      '// exercita a lógica de janela/limite de verdade através do router, mesmo',
      '// padrão usado em prisma-rate-limiter.test.ts (Story 2.2).',
      'function makeInMemoryRateLimiter(): PrismaRateLimiter {',
      '  const rows = new Map<string, RateLimitHitRecord>();',
      '  const key = (identifier: string, windowStart: Date) =>',
      '    `${identifier}|${windowStart.getTime()}`;',
      '  const store: RateLimitStore = {',
      '    rateLimitHit: {',
      '      async upsert({ where, update, create }) {',
      '        const { identifier, windowStart } = where.identifier_windowStart;',
      '        const k = key(identifier, windowStart);',
      '        const existing = rows.get(k);',
      '        const record: RateLimitHitRecord = existing',
      '          ? { ...existing, count: existing.count + update.count.increment }',
      '          : { identifier, windowStart, count: create.count };',
      '        rows.set(k, record);',
      '        return record;',
      '      },',
      '      async findUnique({ where }) {',
      '        const { identifier, windowStart } = where.identifier_windowStart;',
      '        return rows.get(key(identifier, windowStart)) ?? null;',
      '      },',
      '    },',
      '  };',
      '  return new PrismaRateLimiter(store);',
      '}',
      '',
      'beforeEach(() => {',
      "  process.env.JWT_SIGNING_KEY = 'test-signing-key-not-for-real-use';",
      '});',
      '',
      'afterEach(() => {',
      '  delete process.env.JWT_SIGNING_KEY;',
      '});',
      '',
      "describe('authRouter.login', () => {",
      "  it('login bem-sucedido retorna accessToken e emite refresh token (AC #6)', async () => {",
      '    const authProvider = makeFakeAuthProvider({',
      '      authenticate: vi.fn(async () => ({',
      "        id: 'user-1',",
      "        tenantId: 'tenant-1',",
      "        email: 'ada@example.com',",
      '        isAdmin: false,',
      '      })),',
      '    });',
      '    const tokenRevocationStore = makeFakeStore();',
      '    const ctx = createTestContext({ authProvider, tokenRevocationStore });',
      '    const caller = authRouter.createCaller(ctx);',
      '',
      '    const result = await caller.login({',
      "      email: 'ada@example.com',",
      "      password: 'correct-horse-battery-staple',",
      "      tenantId: 'tenant-1',",
      '    });',
      '',
      '    expect(result.accessToken).toEqual(expect.any(String));',
      '    expect(tokenRevocationStore.issue).toHaveBeenCalledWith(',
      "      { userId: 'user-1', tenantId: 'tenant-1' },",
      '      expect.any(Date),',
      '    );',
      '    // O mecanismo central da AC #6 é o COOKIE, não só o retorno — sem inspecionar',
      '    // a chamada a setCookie, um regresso que quebrasse httpOnly/sameSite/secure',
      '    // passaria despercebido (achado do code review).',
      '    expect(ctx.res.setCookie).toHaveBeenCalledWith(',
      "      'refresh_token',",
      '      expect.any(String),',
      '      expect.objectContaining({',
      '        httpOnly: true,',
      "        sameSite: 'strict',",
      "        secure: false, // NODE_ENV !== 'production' neste teste",
      "        path: '/',",
      '        maxAge: expect.any(Number),',
      '      }),',
      '    );',
      '  });',
      '',
      "  it('senha errada e usuário inexistente produzem erro byte-idêntico (AC #9)', async () => {",
      '    const wrongPasswordCaller = authRouter.createCaller(',
      '      createTestContext({ authProvider: makeFakeAuthProvider() }),',
      '    );',
      '    const missingUserCaller = authRouter.createCaller(',
      '      createTestContext({ authProvider: makeFakeAuthProvider() }),',
      '    );',
      '',
      '    const wrongPasswordError = await wrongPasswordCaller',
      '      .login({',
      "        email: 'ada@example.com',",
      "        password: 'wrong-password',",
      "        tenantId: 'tenant-1',",
      '      })',
      '      .catch((e: unknown) => e);',
      '    const missingUserError = await missingUserCaller',
      '      .login({',
      "        email: 'ninguem@example.com',",
      "        password: 'qualquer-coisa',",
      "        tenantId: 'tenant-1',",
      '      })',
      '      .catch((e: unknown) => e);',
      '',
      '    expect(wrongPasswordError).toBeInstanceOf(TRPCError);',
      '    expect(missingUserError).toBeInstanceOf(TRPCError);',
      '    // Asserção de igualdade direta entre as duas respostas — não "ambas genéricas"',
      '    // (achado do review de qualidade da story, Task 6.5).',
      '    expect((wrongPasswordError as TRPCError).code).toBe(',
      '      (missingUserError as TRPCError).code,',
      '    );',
      '    expect((wrongPasswordError as TRPCError).message).toBe(',
      '      (missingUserError as TRPCError).message,',
      '    );',
      '    // `router.createCaller` nunca passa pelo errorFormatter real (que só roda no',
      '    // adapter HTTP) — comparar o TRPCError cru não prova que o envelope RFC 9457',
      '    // final (status/title/detail/type) também é byte-idêntico, que é o que a',
      '    // Task 6.5 pede literalmente. Reconstrói os dois via a mesma',
      '    // `buildProblemDetails` que o `errorFormatter` de verdade chama.',
      '    expect(toProblemDetails(wrongPasswordError as TRPCError)).toEqual(',
      '      toProblemDetails(missingUserError as TRPCError),',
      '    );',
      '  });',
      '});',
      '',
      "describe('authRouter.login — rate limiting (Story 2.2, AD-10)', () => {",
      "  it('bloqueia depois de 5 tentativas com senha errada — authenticate não é chamado na 6ª (AC #4)', async () => {",
      '    const authenticate = vi.fn(async () => null);',
      '    const authProvider = makeFakeAuthProvider({ authenticate });',
      '    const rateLimiter = makeInMemoryRateLimiter();',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({ authProvider, rateLimiter }),',
      '    );',
      '    const attempt = () =>',
      '      caller',
      '        .login({',
      "          email: 'ada@example.com',",
      "          password: 'wrong-password',",
      "          tenantId: 'tenant-1',",
      '        })',
      '        .catch((e: unknown) => e);',
      '',
      '    for (let i = 0; i < 5; i++) {',
      '      const error = await attempt();',
      "      expect(error).toMatchObject({ code: 'UNAUTHORIZED' });",
      '    }',
      '    expect(authenticate).toHaveBeenCalledTimes(5);',
      '',
      '    const sixthError = await attempt();',
      '',
      "    expect(sixthError).toMatchObject({ code: 'TOO_MANY_REQUESTS' });",
      '    // Continua em 5 -- a 6ª tentativa nunca chegou a chamar authenticate.',
      '    expect(authenticate).toHaveBeenCalledTimes(5);',
      '  });',
      '',
      "  it('login bem-sucedido repetido nunca bloqueia (AC #5)', async () => {",
      '    const authProvider = makeFakeAuthProvider({',
      '      authenticate: vi.fn(async () => ({',
      "        id: 'user-1',",
      "        tenantId: 'tenant-1',",
      "        email: 'ada@example.com',",
      '        isAdmin: false,',
      '      })),',
      '    });',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({',
      '        authProvider,',
      '        tokenRevocationStore: makeFakeStore(),',
      '        rateLimiter: makeInMemoryRateLimiter(),',
      '      }),',
      '    );',
      '',
      '    for (let i = 0; i < 10; i++) {',
      '      const result = await caller.login({',
      "        email: 'ada@example.com',",
      "        password: 'correct-horse-battery-staple',",
      "        tenantId: 'tenant-1',",
      '      });',
      '      expect(result.accessToken).toEqual(expect.any(String));',
      '    }',
      '  });',
      '',
      "  it('email inexistente é rate-limited igual a email existente, mesmo erro nos dois casos (AC #6)', async () => {",
      '    const wrongPasswordCaller = authRouter.createCaller(',
      '      createTestContext({',
      '        authProvider: makeFakeAuthProvider(),',
      '        rateLimiter: makeInMemoryRateLimiter(),',
      '      }),',
      '    );',
      '    const missingUserCaller = authRouter.createCaller(',
      '      createTestContext({',
      '        authProvider: makeFakeAuthProvider(),',
      '        rateLimiter: makeInMemoryRateLimiter(),',
      '      }),',
      '    );',
      '    const attemptWrongPassword = () =>',
      '      wrongPasswordCaller',
      '        .login({',
      "          email: 'ada@example.com',",
      "          password: 'wrong-password',",
      "          tenantId: 'tenant-1',",
      '        })',
      '        .catch((e: unknown) => e);',
      '    const attemptMissingUser = () =>',
      '      missingUserCaller',
      '        .login({',
      "          email: 'ninguem@example.com',",
      "          password: 'qualquer-coisa',",
      "          tenantId: 'tenant-1',",
      '        })',
      '        .catch((e: unknown) => e);',
      '',
      '    for (let i = 0; i < 5; i++) {',
      '      await attemptWrongPassword();',
      '      await attemptMissingUser();',
      '    }',
      '',
      '    const wrongPasswordError = await attemptWrongPassword();',
      '    const missingUserError = await attemptMissingUser();',
      '',
      "    expect(wrongPasswordError).toMatchObject({ code: 'TOO_MANY_REQUESTS' });",
      "    expect(missingUserError).toMatchObject({ code: 'TOO_MANY_REQUESTS' });",
      '    expect((wrongPasswordError as TRPCError).message).toBe(',
      '      (missingUserError as TRPCError).message,',
      '    );',
      '  });',
      '',
      "  it('input malformado (erro Zod) não conta pro limite de tentativas (AC #5)', async () => {",
      '    const rateLimiter = makeInMemoryRateLimiter();',
      "    const isBlockedSpy = vi.spyOn(rateLimiter, 'isBlocked');",
      "    const recordFailureSpy = vi.spyOn(rateLimiter, 'recordFailure');",
      '    const caller = authRouter.createCaller(createTestContext({ rateLimiter }));',
      '',
      '    await expect(',
      '      caller.login({',
      "        email: 'not-an-email',",
      "        password: '',",
      "        tenantId: 'tenant-1',",
      '      }),',
      "    ).rejects.toMatchObject({ code: 'BAD_REQUEST' });",
      '',
      '    expect(isBlockedSpy).not.toHaveBeenCalled();',
      '    expect(recordFailureSpy).not.toHaveBeenCalled();',
      '  });',
      '',
      "  it('rate limiter indisponível ao checar bloqueio → login falha fail-closed (TOO_MANY_REQUESTS), sem chamar authenticate', async () => {",
      '    const authenticate = vi.fn(async () => null);',
      '    const authProvider = makeFakeAuthProvider({ authenticate });',
      '    const rateLimiter = {',
      '      isBlocked: vi.fn(async () => {',
      "        throw new Error('Postgres indisponível');",
      '      }),',
      '      recordFailure: vi.fn(async () => undefined),',
      '    };',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({ authProvider, rateLimiter }),',
      '    );',
      '',
      '    const error = await caller',
      '      .login({',
      "        email: 'ada@example.com',",
      "        password: 'wrong-password',",
      "        tenantId: 'tenant-1',",
      '      })',
      '      .catch((e: unknown) => e);',
      '',
      "    expect(error).toMatchObject({ code: 'TOO_MANY_REQUESTS' });",
      '    expect(authenticate).not.toHaveBeenCalled();',
      '  });',
      '',
      "  it('falha ao registrar tentativa (recordFailure indisponível) não mascara o 401 pretendido (AC #9)', async () => {",
      '    const rateLimiter = {',
      '      isBlocked: vi.fn(async () => false),',
      '      recordFailure: vi.fn(async () => {',
      "        throw new Error('Postgres indisponível');",
      '      }),',
      '    };',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({ authProvider: makeFakeAuthProvider(), rateLimiter }),',
      '    );',
      '',
      '    const error = await caller',
      '      .login({',
      "        email: 'ada@example.com',",
      "        password: 'wrong-password',",
      "        tenantId: 'tenant-1',",
      '      })',
      '      .catch((e: unknown) => e);',
      '',
      "    expect(error).toMatchObject({ code: 'UNAUTHORIZED' });",
      '  });',
      '});',
      '',
      "describe('authRouter.refresh', () => {",
      "  it('refresh token válido troca por novo access token, sem expor o refresh token (AC #8)', async () => {",
      '    const ctx = createTestContext({',
      '      tokenRevocationStore: makeFakeStore(),',
      '      authProvider: makeFakeAuthProvider(),',
      '    });',
      "    ctx.req.cookies.refresh_token = 'a-valid-raw-refresh-token';",
      '    const caller = authRouter.createCaller(ctx);',
      '',
      '    const result = await caller.refresh();',
      '',
      '    expect(result.accessToken).toEqual(expect.any(String));',
      "    expect(result).not.toHaveProperty('refreshToken');",
      '  });',
      '',
      "  it('refresh token revogado é rejeitado (AC #8)', async () => {",
      '    const ctx = createTestContext({',
      '      // getSubject já valida revogado/expirado por conta própria (refresh',
      '      // não chama isRevoked separadamente — ver token-revocation-store.ts).',
      '      tokenRevocationStore: makeFakeStore({',
      '        getSubject: vi.fn(async () => null),',
      '      }),',
      '    });',
      "    ctx.req.cookies.refresh_token = 'a-revoked-token';",
      '    const caller = authRouter.createCaller(ctx);',
      '',
      '    await expect(caller.refresh()).rejects.toMatchObject({',
      "      code: 'UNAUTHORIZED',",
      '    });',
      '  });',
      '',
      "  it('refresh sem cookie é rejeitado', async () => {",
      '    const caller = authRouter.createCaller(createTestContext());',
      '',
      '    await expect(caller.refresh()).rejects.toMatchObject({',
      "      code: 'UNAUTHORIZED',",
      '    });',
      '  });',
      '',
      "  it('refresh RE-DERIVA isAdmin fresco do banco — revogar admin de alguém reflete no próximo refresh (AC #2, Story 5.1, achado real)', async () => {",
      '    let currentlyAdmin = true;',
      '    const authProvider = makeFakeAuthProvider({',
      '      findUserById: vi.fn(async () => ({',
      "        id: 'user-1',",
      "        tenantId: 'tenant-1',",
      "        email: 'ada@example.com',",
      '        isAdmin: currentlyAdmin,',
      '      })),',
      '    });',
      '    const ctx = createTestContext({',
      '      tokenRevocationStore: makeFakeStore(),',
      '      authProvider,',
      '    });',
      "    ctx.req.cookies.refresh_token = 'a-valid-raw-refresh-token';",
      '    const caller = authRouter.createCaller(ctx);',
      '',
      '    const key = new TextEncoder().encode(',
      "      'test-signing-key-not-for-real-use',",
      '    );',
      '',
      '    const firstResult = await caller.refresh();',
      '    const { payload: firstPayload } = await jwtVerify(',
      '      firstResult.accessToken,',
      '      key,',
      '    );',
      '    expect(firstPayload.isAdmin).toBe(true);',
      '',
      '    // "Revoga" admin de alguém — o PRÓXIMO refresh (mesmo refresh token, nunca',
      '    // reemitido) precisa refletir isso, não continuar achando que é admin.',
      '    currentlyAdmin = false;',
      '    const secondResult = await caller.refresh();',
      '    const { payload: secondPayload } = await jwtVerify(',
      '      secondResult.accessToken,',
      '      key,',
      '    );',
      '    expect(secondPayload.isAdmin).toBe(false);',
      '  });',
      '',
      "  it('refresh falha se o usuário foi deletado (findUserById retorna null)', async () => {",
      '    const authProvider = makeFakeAuthProvider({',
      '      findUserById: vi.fn(async () => null),',
      '    });',
      '    const ctx = createTestContext({',
      '      tokenRevocationStore: makeFakeStore(),',
      '      authProvider,',
      '    });',
      "    ctx.req.cookies.refresh_token = 'a-valid-raw-refresh-token';",
      '    const caller = authRouter.createCaller(ctx);',
      '',
      '    await expect(caller.refresh()).rejects.toMatchObject({',
      "      code: 'UNAUTHORIZED',",
      '    });',
      '  });',
      '});',
      '',
      "describe('authRouter.requestPasswordReset (Story 4.2, FR-18/FR-19)', () => {",
      "  it('email conhecido: emite token e envia o email password-reset com o link (AC #2)', async () => {",
      '    const authProvider = makeFakeAuthProvider({',
      '      findUserByEmail: vi.fn(async () => ({',
      "        id: 'user-1',",
      "        tenantId: 'tenant-1',",
      "        email: 'ada@example.com',",
      '        isAdmin: false,',
      '      })),',
      '    });',
      '    const passwordResetTokenStore = makeFakePasswordResetTokenStore();',
      '    const emailProvider = makeFakeEmailProvider();',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({',
      '        authProvider,',
      '        passwordResetTokenStore,',
      '        emailProvider,',
      '        rateLimiter: makeInMemoryRateLimiter(),',
      '      }),',
      '    );',
      '',
      '    await caller.requestPasswordReset({',
      "      email: 'ada@example.com',",
      "      tenantId: 'tenant-1',",
      '    });',
      '',
      '    expect(passwordResetTokenStore.issue).toHaveBeenCalledWith(',
      "      'user-1',",
      "      'tenant-1',",
      '      expect.any(Date),',
      '    );',
      '    expect(emailProvider.send).toHaveBeenCalledWith({',
      "      template: 'password-reset',",
      "      to: 'ada@example.com',",
      '      data: {',
      '        // Path e nome do query param exatos — `stringContaining` só pelo token',
      '        // deixaria passar um regresso pra `/forgot-password` ou `?rawToken=`',
      '        // (achado real do code review).',
      "        resetLink: 'http://localhost:5173/reset-password?token=raw-reset-token',",
      '        expiresInMinutes: expect.any(Number),',
      '      },',
      '    });',
      '  });',
      '',
      "  it('email desconhecido: NÃO emite token nem envia email, mas não lança erro — mesma resposta de sucesso (AC #1)', async () => {",
      '    const passwordResetTokenStore = makeFakePasswordResetTokenStore();',
      '    const emailProvider = makeFakeEmailProvider();',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({',
      '        authProvider: makeFakeAuthProvider(),',
      '        passwordResetTokenStore,',
      '        emailProvider,',
      '        rateLimiter: makeInMemoryRateLimiter(),',
      '      }),',
      '    );',
      '',
      '    await expect(',
      '      caller.requestPasswordReset({',
      "        email: 'ninguem@example.com',",
      "        tenantId: 'tenant-1',",
      '      }),',
      '    ).resolves.toBeUndefined();',
      '',
      '    expect(passwordResetTokenStore.issue).not.toHaveBeenCalled();',
      '    expect(emailProvider.send).not.toHaveBeenCalled();',
      '  });',
      '',
      "  it('bloqueia depois de 5 tentativas — toda chamada conta pro limite, mesmo com email desconhecido (AC #3)', async () => {",
      '    const rateLimiter = makeInMemoryRateLimiter();',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({',
      '        authProvider: makeFakeAuthProvider(),',
      '        passwordResetTokenStore: makeFakePasswordResetTokenStore(),',
      '        emailProvider: makeFakeEmailProvider(),',
      '        rateLimiter,',
      '      }),',
      '    );',
      '    const attempt = () =>',
      '      caller.requestPasswordReset({',
      "        email: 'ninguem@example.com',",
      "        tenantId: 'tenant-1',",
      '      });',
      '',
      '    for (let i = 0; i < 5; i++) {',
      '      await expect(attempt()).resolves.toBeUndefined();',
      '    }',
      '',
      '    await expect(attempt()).rejects.toMatchObject({',
      "      code: 'TOO_MANY_REQUESTS',",
      '    });',
      '  });',
      '',
      "  it('rate limiter indisponível ao checar bloqueio → falha fail-closed (TOO_MANY_REQUESTS), sem resolver o email (AC #3, mesmo racional do login)', async () => {",
      '    const findUserByEmail = vi.fn(async () => null);',
      '    const authProvider = makeFakeAuthProvider({ findUserByEmail });',
      '    const rateLimiter = {',
      '      isBlocked: vi.fn(async () => {',
      "        throw new Error('Postgres indisponível');",
      '      }),',
      '      recordFailure: vi.fn(async () => undefined),',
      '    };',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({ authProvider, rateLimiter }),',
      '    );',
      '',
      '    await expect(',
      '      caller.requestPasswordReset({',
      "        email: 'ada@example.com',",
      "        tenantId: 'tenant-1',",
      '      }),',
      "    ).rejects.toMatchObject({ code: 'TOO_MANY_REQUESTS' });",
      '    expect(findUserByEmail).not.toHaveBeenCalled();',
      '  });',
      '',
      "  it('falha ao registrar tentativa (recordFailure indisponível) não mascara a resposta de sucesso (AC #1)', async () => {",
      '    const rateLimiter = {',
      '      isBlocked: vi.fn(async () => false),',
      '      recordFailure: vi.fn(async () => {',
      "        throw new Error('Postgres indisponível');",
      '      }),',
      '    };',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({ authProvider: makeFakeAuthProvider(), rateLimiter }),',
      '    );',
      '',
      '    await expect(',
      '      caller.requestPasswordReset({',
      "        email: 'ada@example.com',",
      "        tenantId: 'tenant-1',",
      '      }),',
      '    ).resolves.toBeUndefined();',
      '  });',
      '',
      '  it(\'falha ao emitir token ou enviar email não faz o caminho "email existe" responder diferente do caminho "email não existe" (AC #1, achado do code review)\', async () => {',
      '    const authProvider = makeFakeAuthProvider({',
      '      findUserByEmail: vi.fn(async () => ({',
      "        id: 'user-1',",
      "        tenantId: 'tenant-1',",
      "        email: 'ada@example.com',",
      '        isAdmin: false,',
      '      })),',
      '    });',
      '    const emailProvider = makeFakeEmailProvider({',
      '      send: vi.fn(async () => {',
      "        throw new Error('Mailpit indisponível');",
      '      }),',
      '    });',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({',
      '        authProvider,',
      '        emailProvider,',
      '        passwordResetTokenStore: makeFakePasswordResetTokenStore(),',
      '        rateLimiter: makeInMemoryRateLimiter(),',
      '      }),',
      '    );',
      '',
      '    await expect(',
      '      caller.requestPasswordReset({',
      "        email: 'ada@example.com',",
      "        tenantId: 'tenant-1',",
      '      }),',
      '    ).resolves.toBeUndefined();',
      '  });',
      '});',
      '',
      "describe('authRouter.resetPassword (Story 4.2, FR-19/FR-9)', () => {",
      "  it('token válido: troca a senha e DEPOIS invalida de verdade todas as sessões ativas, nessa ordem (AC #5, #6, #7)', async () => {",
      '    const authProvider = makeFakeAuthProvider();',
      '    // Stateful de verdade (não um spy) — prova o EFEITO real de',
      '    // revokeAllForUser, não só que foi chamado (achado do code review).',
      '    const tokenRevocationStore = new PrismaTokenRevocationStore(',
      '      makeStatefulRefreshTokenStore(),',
      '    );',
      '    const revokeAllForUserSpy = vi.spyOn(',
      '      tokenRevocationStore,',
      "      'revokeAllForUser',",
      '    );',
      '    const oldRefreshToken = await tokenRevocationStore.issue(',
      "      { userId: 'user-1', tenantId: 'tenant-1' },",
      '      new Date(Date.now() + 60_000),',
      '    );',
      '    expect(await tokenRevocationStore.isRevoked(oldRefreshToken)).toBe(',
      '      false,',
      '    );',
      '    const passwordResetTokenStore = makeFakePasswordResetTokenStore({',
      "      consume: vi.fn(async () => 'user-1'),",
      '    });',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({',
      '        authProvider,',
      '        tokenRevocationStore,',
      '        passwordResetTokenStore,',
      '      }),',
      '    );',
      '',
      '    await caller.resetPassword({',
      "      token: 'raw-reset-token',",
      "      newPassword: 'nova-senha-forte',",
      '    });',
      '',
      '    expect(authProvider.setPassword).toHaveBeenCalledWith(',
      "      'user-1',",
      "      'nova-senha-forte',",
      '    );',
      '    // Efeito real: o refresh token emitido ANTES do reset agora está',
      '    // revogado de verdade, não só "o método foi chamado".',
      '    expect(await tokenRevocationStore.isRevoked(oldRefreshToken)).toBe(true);',
      "    expect(revokeAllForUserSpy).toHaveBeenCalledWith('user-1');",
      '    // Ordem: setPassword tem que ter sido chamado ANTES de revokeAllForUser —',
      '    // `invocationCallOrder` do vitest, não um array manual (o spy acima',
      '    // chama a implementação REAL, não substitui por um `vi.fn()` próprio).',
      '    const setPasswordOrder = vi.mocked(authProvider.setPassword).mock',
      '      .invocationCallOrder[0];',
      '    const revokeOrder = revokeAllForUserSpy.mock.invocationCallOrder[0];',
      '    expect(setPasswordOrder).toBeLessThan(revokeOrder);',
      '  });',
      '',
      "  it('token inválido/expirado/já usado: erro genérico, nunca troca senha nem revoga sessões (AC #4)', async () => {",
      '    const authProvider = makeFakeAuthProvider();',
      '    const tokenRevocationStore = makeFakeStore();',
      '    const passwordResetTokenStore = makeFakePasswordResetTokenStore({',
      '      consume: vi.fn(async () => null),',
      '    });',
      '    const caller = authRouter.createCaller(',
      '      createTestContext({',
      '        authProvider,',
      '        tokenRevocationStore,',
      '        passwordResetTokenStore,',
      '      }),',
      '    );',
      '',
      '    await expect(',
      '      caller.resetPassword({',
      "        token: 'token-invalido',",
      "        newPassword: 'nova-senha-forte',",
      '      }),',
      "    ).rejects.toMatchObject({ code: 'BAD_REQUEST' });",
      '',
      '    expect(authProvider.setPassword).not.toHaveBeenCalled();',
      '    expect(tokenRevocationStore.revokeAllForUser).not.toHaveBeenCalled();',
      '  });',
      '});',
      '',
    ].join('\n'),

    'src/core/secrets/env-secrets-provider.test.ts': [
      "import { describe, it, expect, afterEach } from 'vitest';",
      "import { EnvSecretsProvider } from './env-secrets-provider.js';",
      '',
      "const TEST_KEY = 'AETHER_TEST_SECRET_KEY';",
      '',
      'afterEach(() => {',
      '  delete process.env[TEST_KEY];',
      '});',
      '',
      "describe('EnvSecretsProvider', () => {",
      "  it('retorna o valor de uma variável de ambiente existente', () => {",
      "    process.env[TEST_KEY] = 'value123';",
      '    const provider = new EnvSecretsProvider();',
      '',
      "    expect(provider.getSecret(TEST_KEY)).toBe('value123');",
      '  });',
      '',
      "  it('lança erro explícito quando a variável não existe (nunca undefined silencioso)', () => {",
      '    delete process.env[TEST_KEY];',
      '    const provider = new EnvSecretsProvider();',
      '',
      '    expect(() => provider.getSecret(TEST_KEY)).toThrow(/AETHER_TEST_SECRET_KEY/);',
      '  });',
      '',
      "  it('lança erro explícito quando a variável existe mas está vazia', () => {",
      "    process.env[TEST_KEY] = '';",
      '    const provider = new EnvSecretsProvider();',
      '',
      '    expect(() => provider.getSecret(TEST_KEY)).toThrow(/AETHER_TEST_SECRET_KEY/);',
      '  });',
      '});',
      '',
    ].join('\n'),
  };
}
