export function buildDbFiles(): Record<string, string> {
  return {
    // Primeira vez de verdade instalando prisma/@prisma/client/@prisma/adapter-pg —
    // Story 1.1 deixou isso pendente deliberadamente (sem model, nada real pra gerar).
    // `pg` não precisa entrar aqui: já é dependência direta de @prisma/adapter-pg.
    'package.json':
      JSON.stringify(
        {
          name: 'db',
          version: '0.0.1',
          private: true,
          type: 'module',
          exports: {
            './client': './src/client.ts',
            './extensions/tenant': './src/extensions/tenant.ts',
          },
          scripts: {
            generate: 'prisma generate',
            migrate: 'prisma migrate dev',
          },
          dependencies: {
            prisma: '7.10.0',
            '@prisma/client': '7.10.0',
            '@prisma/adapter-pg': '7.10.0',
          },
          devDependencies: {
            typescript: '5.9.3',
          },
        },
        null,
        2,
      ) + '\n',

    // prisma.config.ts fica na raiz do pacote (fora de src/) — convenção do Prisma 7,
    // não pode mover. rootDir continua '.' por causa disso; src/ entra no include também.
    'tsconfig.json':
      JSON.stringify(
        {
          extends: '../../tsconfig.base.json',
          compilerOptions: {
            composite: true,
            outDir: 'dist',
            rootDir: '.',
          },
          include: ['prisma.config.ts', 'src/**/*.ts'],
        },
        null,
        2,
      ) + '\n',

    // Tenant/User (FR-11 parcial, ver Dev Notes da Story 2.1 sobre o corte com a Epic 3) +
    // RefreshToken (FR-9, TokenRevocationStore). Sem `@default` de banco pro id — uuid(7) é
    // gerado pelo próprio Prisma Client antes do INSERT, não uma expressão SQL (confirmado
    // via `prisma migrate diff` real contra este schema — a migration abaixo reflete isso:
    // colunas de id são TEXT NOT NULL, sem DEFAULT).
    'schema.prisma': [
      'generator client {',
      '  provider = "prisma-client-js"',
      '}',
      '',
      'datasource db {',
      '  provider = "postgresql"',
      '}',
      '',
      'model Tenant {',
      '  id        String   @id @default(uuid(7))',
      '  name      String',
      '  createdAt DateTime @default(now()) @map("created_at")',
      '  updatedAt DateTime @updatedAt @map("updated_at")',
      '',
      '  users           User[]',
      '  groups          Group[]',
      '  roles           Role[]',
      '  roleAssignments RoleAssignment[]',
      '',
      '  @@map("tenants")',
      '}',
      '',
      '// Grupo/Papel/Módulo/ModuleClosure e as relações que ligam User a eles (Story 3.1,',
      '// FR-11 parcial) estendem esta tabela — nunca a recriam (achado da Story 2.1).',
      'model User {',
      '  id           String   @id @default(uuid(7))',
      '  tenantId     String   @map("tenant_id")',
      '  email        String',
      '  passwordHash String   @map("password_hash")',
      '  createdAt    DateTime @default(now()) @map("created_at")',
      '  updatedAt    DateTime @updatedAt @map("updated_at")',
      '',
      '  tenant              Tenant               @relation(fields: [tenantId], references: [id])',
      '  refreshTokens       RefreshToken[]',
      '  passwordResetTokens PasswordResetToken[]',
      '  groups              Group[]',
      '  roleAssignments     RoleAssignment[]',
      '',
      '  @@unique([tenantId, email])',
      '  @@map("users")',
      '}',
      '',
      '// jti é o hash do refresh token opaco (crypto.randomBytes(32) base64url), nunca o',
      '// valor bruto — mesmo racional do pepper (Story 2.1, Task 4.3): nunca persistir um',
      '// segredo em texto recuperável. tenantId é denormalizado de User (sem @relation pra',
      '// Tenant — só otimização de leitura pro refresh não precisar de um segundo join;',
      '// consistência garantida na escrita, copiado de user.tenantId em issue()).',
      'model RefreshToken {',
      '  jti       String    @id',
      '  userId    String    @map("user_id")',
      '  tenantId  String    @map("tenant_id")',
      '  issuedAt  DateTime  @default(now()) @map("issued_at")',
      '  expiresAt DateTime  @map("expires_at")',
      '  revokedAt DateTime? @map("revoked_at")',
      '',
      '  user User @relation(fields: [userId], references: [id])',
      '',
      '  @@index([userId])',
      '  @@map("refresh_tokens")',
      '}',
      '',
      '// tokenHash é o hash do token de reset bruto (crypto.randomBytes(32) base64url),',
      '// nunca o valor bruto — mesmo racional de RefreshToken acima. usedAt null = ainda',
      '// válido; setado (não deletado) ao ser consumido, pra consume() poder negar',
      '// reuso explicitamente em vez de só "não encontrado" (Story 4.2). Desenhado de',
      '// forma neutra (não amarrado a "esqueci minha senha" especificamente) pra Epic 5',
      '// (FR-15, senha inicial no import em lote) poder reaproveitar o mesmo mecanismo.',
      'model PasswordResetToken {',
      '  id        String    @id @default(uuid(7))',
      '  userId    String    @map("user_id")',
      '  tenantId  String    @map("tenant_id")',
      '  tokenHash String    @unique @map("token_hash")',
      '  expiresAt DateTime  @map("expires_at")',
      '  usedAt    DateTime? @map("used_at")',
      '  createdAt DateTime  @default(now()) @map("created_at")',
      '',
      '  user User @relation(fields: [userId], references: [id])',
      '',
      '  @@index([userId])',
      '  @@map("password_reset_tokens")',
      '}',
      '',
      '// Física e logicamente separada de RefreshToken (AD-10, Story 2.2) — nunca',
      '// reaproveitar colunas/tabela da revogação de token pro rate limiter. count é',
      '// incrementado via upsert atômico (PrismaRateLimiter) — nunca "ler, somar,',
      '// escrever" em dois passos (mesma classe de TOCTOU corrigida no code review da',
      '// Story 2.1 pro `refresh`).',
      'model RateLimitHit {',
      '  id          String   @id @default(uuid(7))',
      '  identifier  String',
      '  windowStart DateTime @map("window_start")',
      '  count       Int      @default(1)',
      '',
      '  @@unique([identifier, windowStart])',
      '  @@map("rate_limit_hits")',
      '}',
      '',
      '// NAMED_PERMISSION é o único tipo implementado no MVP (FR-13) — BUSINESS_OBJECT',
      '// existe como contrato de tipo, sem nenhum código de produto que crie um Resource',
      '// desse kind ainda.',
      'enum ResourceKind {',
      '  NAMED_PERMISSION',
      '  BUSINESS_OBJECT',
      '}',
      '',
      'model Group {',
      '  id        String   @id @default(uuid(7))',
      '  tenantId  String   @map("tenant_id")',
      '  name      String',
      '  createdAt DateTime @default(now()) @map("created_at")',
      '  updatedAt DateTime @updatedAt @map("updated_at")',
      '',
      '  tenant          Tenant           @relation(fields: [tenantId], references: [id])',
      '  users           User[]',
      '  roleAssignments RoleAssignment[]',
      '',
      '  @@map("groups")',
      '}',
      '',
      'model Role {',
      '  id        String   @id @default(uuid(7))',
      '  tenantId  String   @map("tenant_id")',
      '  name      String',
      '  createdAt DateTime @default(now()) @map("created_at")',
      '  updatedAt DateTime @updatedAt @map("updated_at")',
      '',
      '  tenant          Tenant           @relation(fields: [tenantId], references: [id])',
      '  resources       Resource[]',
      '  roleAssignments RoleAssignment[]',
      '',
      '  @@map("roles")',
      '}',
      '',
      '// Module/ModuleClosure/Resource são GLOBAIS — estrutura de código compartilhada',
      '// por toda a instalação, não dado de tenant (reconciliação pós-review da Story',
      '// 3.1: o ERD original da Architecture Spine tratava Module como tenant-scoped',
      '// (`TENANT ||--o{ MODULE`), o que quebrava RBAC pra qualquer tenant além do',
      '// "dono" do Module de cada Resource — `generate module` roda uma vez por',
      '// instalação e insere uma linha (AD-6, texto literal), nunca uma por tenant.',
      '// Isolamento multi-tenant vive só em RoleAssignment/User/Group/Role — ver Dev',
      '// Notes e a nota de reconciliação na Architecture Spine.',
      '// Todo Module tem o diretório apps/api/src/modules/<slug>/ correspondente (AD-6)',
      "// — não existe 'nó sem módulo de código'. Criação é exclusiva de `generate module`",
      '// (Story 3.2); esta story só define o schema, testes populam via Prisma direto.',
      'model Module {',
      '  id        String   @id @default(uuid(7))',
      '  slug      String',
      '  name      String',
      '  createdAt DateTime @default(now()) @map("created_at")',
      '',
      '  // Nomeadas (não uma FK só) — Module precisa de duas relações distintas pra',
      '  // ModuleClosure (como ancestral E como descendente de outras linhas).',
      '  ancestorClosures   ModuleClosure[]  @relation("ClosureDescendant")',
      '  descendantClosures ModuleClosure[]  @relation("ClosureAncestor")',
      '  roleAssignments    RoleAssignment[]',
      '  resources          Resource[]',
      '',
      '  @@unique([slug])',
      '  @@map("modules")',
      '}',
      '',
      '// Append-only no MVP (AD-6) — sem reparent, nenhum código de produto faz',
      '// DELETE/UPDATE aqui. depth=0 é a linha self-referencial obrigatória',
      '// (ancestorId=descendantId) que todo Module ganha ao ser criado.',
      'model ModuleClosure {',
      '  id           String @id @default(uuid(7))',
      '  ancestorId   String @map("ancestor_id")',
      '  descendantId String @map("descendant_id")',
      '  depth        Int',
      '',
      '  ancestor   Module @relation("ClosureAncestor", fields: [ancestorId], references: [id])',
      '  descendant Module @relation("ClosureDescendant", fields: [descendantId], references: [id])',
      '',
      '  // Cobre o índice ModuleClosure(ancestorId, descendantId) exigido pela AD-8 —',
      '  // @@unique já cria esse índice físico no Postgres, sem precisar de @@index',
      '  // redundante.',
      '  @@unique([ancestorId, descendantId])',
      '  @@map("module_closures")',
      '}',
      '',
      '// moduleId é FK real pra Module — não existe no ERD original da Architecture',
      '// Spine (que só amarra Resource a Module pela convenção de nome da AC #7),',
      '// mas requireResource (Story 3.1) precisa saber de qual módulo subir a',
      '// ModuleClosure sem fazer parsing de string (achado do code review/create-story,',
      '// ver Dev Notes). name continua único globalmente e documenta a convenção',
      '// <module-slug>.<ação> (AD-7) — moduleId é a fonte de verdade que o middleware',
      '// de fato consulta. Module é global (ver comentário acima), então essa FK nunca',
      '// amarra Resource a um tenant específico.',
      'model Resource {',
      '  id       String       @id @default(uuid(7))',
      '  moduleId String       @map("module_id")',
      '  name     String       @unique',
      '  kind     ResourceKind @default(NAMED_PERMISSION)',
      '',
      '  module Module @relation(fields: [moduleId], references: [id])',
      '  roles  Role[]',
      '',
      '  @@map("resources")',
      '}',
      '',
      '// assignee é exatamente User OU Group, nunca os dois (a AD-8 descreve isso como',
      '// um "assigneeId" conceitual único — Prisma não modela FK polimórfica nativamente,',
      '// então são duas colunas nullable; ver Dev Notes pra reconciliação e pra decisão',
      '// sobre @@check vs. validação em código). Os dois índices abaixo, juntos, cobrem',
      '// a mesma necessidade de performance que a AD-8 descreve como um índice só.',
      '// user/group usam onDelete: Cascade explícito (não o default SetNull de FK opcional',
      '// do Prisma) — achado do code review: SetNull produziria (user_id=NULL,',
      '// group_id=NULL) ao deletar o User/Group referenciado, violando a CHECK',
      '// role_assignments_assignee_check abaixo e travando a própria exclusão com um erro',
      '// de banco não mapeado. Nenhuma feature de exclusão de User/Group existe ainda',
      '// (Epic 4/admin) — Cascade é o comportamento sem surpresa até uma delas precisar de',
      '// algo mais específico (soft-delete, reatribuição etc.).',
      'model RoleAssignment {',
      '  id             String   @id @default(uuid(7))',
      '  tenantId       String   @map("tenant_id")',
      '  userId         String?  @map("user_id")',
      '  groupId        String?  @map("group_id")',
      '  roleId         String   @map("role_id")',
      '  targetModuleId String   @map("target_module_id")',
      '  createdAt      DateTime @default(now()) @map("created_at")',
      '',
      '  tenant       Tenant @relation(fields: [tenantId], references: [id])',
      '  user         User?  @relation(fields: [userId], references: [id], onDelete: Cascade)',
      '  group        Group? @relation(fields: [groupId], references: [id], onDelete: Cascade)',
      '  role         Role   @relation(fields: [roleId], references: [id])',
      '  targetModule Module @relation(fields: [targetModuleId], references: [id])',
      '',
      '  @@index([userId, targetModuleId])',
      '  @@index([groupId, targetModuleId])',
      '  @@map("role_assignments")',
      '}',
      '',
    ].join('\n'),

    // Prisma 7: `datasource` no schema.prisma só declara o provider — a connection string
    // real vem daqui (nunca hardcoded no schema). Sem `adapter` aqui — isso é opção do
    // PrismaClient em runtime (ver src/client.ts), não do config file (confirmado nos
    // tipos de @prisma/config 7.10.0: PrismaConfig não tem campo `adapter`).
    //
    // NÃO usa o helper `env()` do @prisma/config — ele LANÇA se a variável não estiver
    // em process.env, e nada carrega .env.development pro processo que roda `prisma
    // generate`/`migrate` (o `--env-file` só está no script `dev` de apps/api, não nos
    // comandos de CLI do Prisma disparados por `aether-admin new`) — achado real da
    // Story 2.1, Task 7: `aether-admin new` quebrava na primeira
    // regeneração porque `prisma generate` roda como parte do próprio `new`, sem
    // servidor nenhum no ar ainda. Fallback pro mesmo valor de dev não-secreto já usado
    // em .env.development/docker-compose.dev.yml (FR-6, zero edição manual) — DATABASE_URL
    // real (produção) sempre tem prioridade se estiver setada.
    'prisma.config.ts': [
      "import { defineConfig } from 'prisma/config';",
      '',
      'export default defineConfig({',
      "  schema: 'schema.prisma',",
      '  datasource: {',
      '    url:',
      '      process.env.DATABASE_URL ??',
      "      'postgresql://aether_dev:aether_dev_password@localhost:5432/aether_dev',",
      '  },',
      '});',
      '',
    ].join('\n'),

    // Migration inicial gerada via `prisma migrate diff --from-empty --to-schema
    // schema.prisma --script` real contra este schema exato (sem precisar de Postgres
    // rodando — só computa o diff local). Nome de pasta segue a convenção de timestamp
    // do Prisma (YYYYMMDDHHMMSS_nome).
    'migrations/migration_lock.toml': [
      '# Please do not edit this file manually',
      '# It should be added in your version-control system (e.g., Git)',
      'provider = "postgresql"',
      '',
    ].join('\n'),

    'migrations/20260901000000_init_auth/migration.sql': [
      '-- CreateSchema',
      'CREATE SCHEMA IF NOT EXISTS "public";',
      '',
      '-- CreateTable',
      'CREATE TABLE "tenants" (',
      '    "id" TEXT NOT NULL,',
      '    "name" TEXT NOT NULL,',
      '    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,',
      '    "updated_at" TIMESTAMP(3) NOT NULL,',
      '',
      '    CONSTRAINT "tenants_pkey" PRIMARY KEY ("id")',
      ');',
      '',
      '-- CreateTable',
      'CREATE TABLE "users" (',
      '    "id" TEXT NOT NULL,',
      '    "tenant_id" TEXT NOT NULL,',
      '    "email" TEXT NOT NULL,',
      '    "password_hash" TEXT NOT NULL,',
      '    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,',
      '    "updated_at" TIMESTAMP(3) NOT NULL,',
      '',
      '    CONSTRAINT "users_pkey" PRIMARY KEY ("id")',
      ');',
      '',
      '-- CreateTable',
      'CREATE TABLE "refresh_tokens" (',
      '    "jti" TEXT NOT NULL,',
      '    "user_id" TEXT NOT NULL,',
      '    "tenant_id" TEXT NOT NULL,',
      '    "issued_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,',
      '    "expires_at" TIMESTAMP(3) NOT NULL,',
      '    "revoked_at" TIMESTAMP(3),',
      '',
      '    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("jti")',
      ');',
      '',
      '-- CreateIndex',
      'CREATE UNIQUE INDEX "users_tenant_id_email_key" ON "users"("tenant_id", "email");',
      '',
      '-- CreateIndex',
      'CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens"("user_id");',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "users" ADD CONSTRAINT "users_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      '',
    ].join('\n'),

    // Migration incremental pra RateLimitHit (Story 2.2, AD-10) — SQL escrito à mão
    // seguindo a MESMA convenção determinística que a migration inicial já usa
    // (`prisma migrate diff --script` não produziu nenhuma saída neste ambiente
    // específico, mesmo pra um schema trivial de um único model — divergente do que
    // funcionou na Story 2.1; não investigado a fundo, provavelmente uma regressão
    // pontual do `migrate diff` no Windows nesta versão do Prisma. A tradução
    // schema→DDL pra um CREATE TABLE simples + índice único é mecânica e já está
    // 100% verificada contra o que o Prisma gerou de verdade nas 3 tabelas
    // anteriores — mesmos tipos de coluna, mesma convenção de nome de índice
    // `<tabela>_<col1>_<col2>_key`, mesma ausência de DEFAULT pro id (uuid(7) é
    // gerado pelo Prisma Client, não pelo banco)).
    'migrations/20260902000000_add_rate_limit_hit/migration.sql': [
      '-- CreateTable',
      'CREATE TABLE "rate_limit_hits" (',
      '    "id" TEXT NOT NULL,',
      '    "identifier" TEXT NOT NULL,',
      '    "window_start" TIMESTAMP(3) NOT NULL,',
      '    "count" INTEGER NOT NULL DEFAULT 1,',
      '',
      '    CONSTRAINT "rate_limit_hits_pkey" PRIMARY KEY ("id")',
      ');',
      '',
      '-- CreateIndex',
      'CREATE UNIQUE INDEX "rate_limit_hits_identifier_window_start_key" ON "rate_limit_hits"("identifier", "window_start");',
      '',
    ].join('\n'),

    // Migration da árvore de identidade (Story 3.1, FR-11/12/13/27, AD-6/7/8) — gerada de
    // verdade via `prisma migrate diff --from-config-datasource --to-schema schema.prisma
    // --script` contra o Postgres real do Laboratório Integrit compartilhado (o comando
    // não funcionou na máquina de desenvolvimento local, mesmo achado das Stories 2.1/2.2
    // — mas funcionou de dentro do container `aether-api` já deployado lá, contra o banco
    // real com as 2 migrations anteriores já aplicadas). Confirma detalhes que não seriam
    // óbvios escrevendo à mão: as tabelas de junção implícitas do Prisma 7 (_GroupToUser,
    // _ResourceToRole) usam PRIMARY KEY composta ("A","B"), não um índice único separado.
    //
    // Revisado À MÃO pós-review (2026-09-04), antes de qualquer deploy real desta
    // migration — Module deixou de ser tenant-scoped (removida a coluna tenant_id, a FK
    // e o índice composto, substituído por unique(slug) só) e as FKs user_id/group_id de
    // role_assignments passaram de ON DELETE SET NULL pra CASCADE (achado do code review:
    // SET NULL colidia com a CHECK assignee abaixo). Ambos os padrões (DROP de coluna+FK+
    // índice, CASCADE explícito) já são idênticos a DDL real emitido pelo Prisma em outras
    // migrations deste mesmo arquivo (_GroupToUser/_ResourceToRole já usam CASCADE;
    // resources_name_key já é um índice único de coluna só) — não voltou pro laboratório
    // pra reconfirmar via `migrate diff` porque a migration ainda não foi aplicada a
    // nenhum dado real em lugar nenhum (ainda é só um artefato desta story, não uma
    // migration já "publicada"); Task 5 desta story reaplica do zero contra o Postgres do
    // lab antes de fechar.
    'migrations/20260904000000_add_identity_tree/migration.sql': [
      '-- CreateEnum',
      "CREATE TYPE \"ResourceKind\" AS ENUM ('NAMED_PERMISSION', 'BUSINESS_OBJECT');",
      '',
      '-- CreateTable',
      'CREATE TABLE "groups" (',
      '    "id" TEXT NOT NULL,',
      '    "tenant_id" TEXT NOT NULL,',
      '    "name" TEXT NOT NULL,',
      '    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,',
      '    "updated_at" TIMESTAMP(3) NOT NULL,',
      '',
      '    CONSTRAINT "groups_pkey" PRIMARY KEY ("id")',
      ');',
      '',
      '-- CreateTable',
      'CREATE TABLE "roles" (',
      '    "id" TEXT NOT NULL,',
      '    "tenant_id" TEXT NOT NULL,',
      '    "name" TEXT NOT NULL,',
      '    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,',
      '    "updated_at" TIMESTAMP(3) NOT NULL,',
      '',
      '    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")',
      ');',
      '',
      '-- CreateTable',
      'CREATE TABLE "modules" (',
      '    "id" TEXT NOT NULL,',
      '    "slug" TEXT NOT NULL,',
      '    "name" TEXT NOT NULL,',
      '    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,',
      '',
      '    CONSTRAINT "modules_pkey" PRIMARY KEY ("id")',
      ');',
      '',
      '-- CreateTable',
      'CREATE TABLE "module_closures" (',
      '    "id" TEXT NOT NULL,',
      '    "ancestor_id" TEXT NOT NULL,',
      '    "descendant_id" TEXT NOT NULL,',
      '    "depth" INTEGER NOT NULL,',
      '',
      '    CONSTRAINT "module_closures_pkey" PRIMARY KEY ("id")',
      ');',
      '',
      '-- CreateTable',
      'CREATE TABLE "resources" (',
      '    "id" TEXT NOT NULL,',
      '    "module_id" TEXT NOT NULL,',
      '    "name" TEXT NOT NULL,',
      '    "kind" "ResourceKind" NOT NULL DEFAULT \'NAMED_PERMISSION\',',
      '',
      '    CONSTRAINT "resources_pkey" PRIMARY KEY ("id")',
      ');',
      '',
      '-- CreateTable',
      'CREATE TABLE "role_assignments" (',
      '    "id" TEXT NOT NULL,',
      '    "tenant_id" TEXT NOT NULL,',
      '    "user_id" TEXT,',
      '    "group_id" TEXT,',
      '    "role_id" TEXT NOT NULL,',
      '    "target_module_id" TEXT NOT NULL,',
      '    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,',
      '',
      '    CONSTRAINT "role_assignments_pkey" PRIMARY KEY ("id")',
      ');',
      '',
      '-- CreateTable',
      'CREATE TABLE "_GroupToUser" (',
      '    "A" TEXT NOT NULL,',
      '    "B" TEXT NOT NULL,',
      '',
      '    CONSTRAINT "_GroupToUser_AB_pkey" PRIMARY KEY ("A","B")',
      ');',
      '',
      '-- CreateTable',
      'CREATE TABLE "_ResourceToRole" (',
      '    "A" TEXT NOT NULL,',
      '    "B" TEXT NOT NULL,',
      '',
      '    CONSTRAINT "_ResourceToRole_AB_pkey" PRIMARY KEY ("A","B")',
      ');',
      '',
      '-- CreateIndex',
      'CREATE UNIQUE INDEX "modules_slug_key" ON "modules"("slug");',
      '',
      '-- CreateIndex',
      'CREATE UNIQUE INDEX "module_closures_ancestor_id_descendant_id_key" ON "module_closures"("ancestor_id", "descendant_id");',
      '',
      '-- CreateIndex',
      'CREATE UNIQUE INDEX "resources_name_key" ON "resources"("name");',
      '',
      '-- CreateIndex',
      'CREATE INDEX "role_assignments_user_id_target_module_id_idx" ON "role_assignments"("user_id", "target_module_id");',
      '',
      '-- CreateIndex',
      'CREATE INDEX "role_assignments_group_id_target_module_id_idx" ON "role_assignments"("group_id", "target_module_id");',
      '',
      '-- CreateIndex',
      'CREATE INDEX "_GroupToUser_B_index" ON "_GroupToUser"("B");',
      '',
      '-- CreateIndex',
      'CREATE INDEX "_ResourceToRole_B_index" ON "_ResourceToRole"("B");',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "groups" ADD CONSTRAINT "groups_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "roles" ADD CONSTRAINT "roles_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "module_closures" ADD CONSTRAINT "module_closures_ancestor_id_fkey" FOREIGN KEY ("ancestor_id") REFERENCES "modules"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "module_closures" ADD CONSTRAINT "module_closures_descendant_id_fkey" FOREIGN KEY ("descendant_id") REFERENCES "modules"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "resources" ADD CONSTRAINT "resources_module_id_fkey" FOREIGN KEY ("module_id") REFERENCES "modules"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "role_assignments" ADD CONSTRAINT "role_assignments_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "role_assignments" ADD CONSTRAINT "role_assignments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "role_assignments" ADD CONSTRAINT "role_assignments_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "role_assignments" ADD CONSTRAINT "role_assignments_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "role_assignments" ADD CONSTRAINT "role_assignments_target_module_id_fkey" FOREIGN KEY ("target_module_id") REFERENCES "modules"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "_GroupToUser" ADD CONSTRAINT "_GroupToUser_A_fkey" FOREIGN KEY ("A") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "_GroupToUser" ADD CONSTRAINT "_GroupToUser_B_fkey" FOREIGN KEY ("B") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "_ResourceToRole" ADD CONSTRAINT "_ResourceToRole_A_fkey" FOREIGN KEY ("A") REFERENCES "resources"("id") ON DELETE CASCADE ON UPDATE CASCADE;',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "_ResourceToRole" ADD CONSTRAINT "_ResourceToRole_B_fkey" FOREIGN KEY ("B") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;',
      '',
      '-- CheckConstraint',
      '-- Prisma 7.10.0 não tem `@@check` no schema.prisma ("Attribute not known: ',
      "-- '@check'.\", verificado contra o pacote real) — adicionado à mão aqui, já que",
      '-- `migrate deploy` roda este arquivo verbatim. Exatamente um de user_id/group_id',
      '-- (nunca os dois, nunca nenhum) — reforço real de banco pro "assignee é User OU',
      '-- Group" que o schema Prisma sozinho não consegue expressar (Story 3.1).',
      'ALTER TABLE "role_assignments" ADD CONSTRAINT "role_assignments_assignee_check" CHECK (("user_id" IS NOT NULL) <> ("group_id" IS NOT NULL));',
      '',
    ].join('\n'),

    // Migration incremental pra PasswordResetToken (Story 4.2, FR-19/FR-9) — mesma
    // convenção DDL determinística já usada pelas migrations anteriores (sem DEFAULT
    // pro id, uuid(7) é gerado pelo Prisma Client; TEXT/TIMESTAMP(3); FK explícita).
    'migrations/20261002000000_add_password_reset_token/migration.sql': [
      '-- CreateTable',
      'CREATE TABLE "password_reset_tokens" (',
      '    "id" TEXT NOT NULL,',
      '    "user_id" TEXT NOT NULL,',
      '    "tenant_id" TEXT NOT NULL,',
      '    "token_hash" TEXT NOT NULL,',
      '    "expires_at" TIMESTAMP(3) NOT NULL,',
      '    "used_at" TIMESTAMP(3),',
      '    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,',
      '',
      '    CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("id")',
      ');',
      '',
      '-- CreateIndex',
      'CREATE UNIQUE INDEX "password_reset_tokens_token_hash_key" ON "password_reset_tokens"("token_hash");',
      '',
      '-- CreateIndex',
      'CREATE INDEX "password_reset_tokens_user_id_idx" ON "password_reset_tokens"("user_id");',
      '',
      '-- AddForeignKey',
      'ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      '',
    ].join('\n'),

    // Instância única do PrismaClient com o driver adapter Postgres (sem engine binário
    // de query — Prisma 7 usa WASM query-compiler + driver adapter). Lida por
    // core/providers.ts e pelo repository.ts de módulos de negócio (Epic 3) — cru, sem
    // escopo de tenant; a extensão tenant-aware (Story 3.1, AD-5) fica em
    // extensions/tenant.ts, construída por request a partir do tenantId já verificado.
    'src/client.ts': [
      "import { PrismaPg } from '@prisma/adapter-pg';",
      "import { PrismaClient } from '@prisma/client';",
      '',
      'const adapter = new PrismaPg({',
      "  connectionString: process.env.DATABASE_URL ?? '',",
      '});',
      '',
      'export const prisma = new PrismaClient({ adapter });',
      '',
    ].join('\n'),

    // Extensão Prisma Client tenant-aware (AD-5, Story 3.1) — injeta tenantId
    // automaticamente nas consultas de TODO model tenant-scoped, incluindo os que
    // `generate module` (Story 3.3) cria em runtime, via `$allModels` (não lista
    // model por model — um model novo nunca fica de fora, achado real da Story 3.3:
    // a versão original só cobria Group/RoleAssignment, deixando módulos gerados sem
    // como passar pela extensão sem violar a AD-5). NUNCA afeta Module/Resource: os
    // dois são globais (estrutura de código compartilhada por toda a instalação, não
    // dado de tenant — reconciliação pós-review da Story 3.1) — mas isso é garantido
    // por quem CHAMA a extensão (core/authz consulta Module/Resource via o client cru,
    // nunca via forTenant), não pelo `$allModels` em si, que intercepta por operação,
    // não por model específico. Cobre toda operação que aceita `where`
    // (findMany/findFirst/findUnique/update/updateMany/delete/deleteMany/upsert) —
    // achado real do retro do Épico 3: a versão original só cobria findMany/findFirst,
    // e a AD-5 promete isolamento pra "todo acesso", sem qualificar como só-leitura; o
    // primeiro `update`/`delete` que um repository.ts editado à mão viesse a usar
    // ficaria sem proteção nenhuma contra acesso cross-tenant. `create` fica de fora de
    // propósito — não tem `where` (o repository.ts gerado já passa `tenantId`
    // explicitamente em `data`, ver module-files.ts). Isso não cobre filtros relacionais aninhados (ex.:
    // `role: {...}`/`group: {...}` dentro de um roleAssignment.findFirst) — só
    // RoleAssignment.tenantId é de fato verificado nesses casos; deferred no code review
    // da Story 3.1 (não explorável hoje, nada escreve RoleAssignment cross-tenant).
    'src/extensions/tenant.ts': [
      "import { prisma } from '../client.js';",
      '',
      '// Testável isoladamente, sem precisar de um PrismaClient real — a única lógica',
      '// que pode ter bug aqui é a ORDEM do merge: tenantId sempre DEPOIS do where do',
      '// caller, nunca antes, pra que um `where` malicioso com seu próprio campo',
      '// "tenantId" nunca vença o valor injetado a partir do contexto autenticado.',
      'export function injectTenant<T extends { where?: Record<string, unknown> }>(',
      '  args: T,',
      '  tenantId: string,',
      "): Omit<T, 'where'> & { where: NonNullable<T['where']> & { tenantId: string } } {",
      '  return { ...args, where: { ...args.where, tenantId } };',
      '}',
      '',
      '// `$allModels` verificado empiricamente contra @prisma/client 7.10.0 real',
      '// (Story 3.3) — cobre qualquer model presente e futuro. `args` dentro do handler',
      '// é uma união de TODOS os tipos de args de TODOS os models (Prisma não consegue',
      '// estreitar pro model específico sendo chamado) — o cast de entrada',
      '// (`as WithWhere`, pra poder chamar `injectTenant` genericamente) é sempre',
      '// necessário. Um segundo cast na SAÍDA (`as typeof args`) só é necessário pra',
      '// `findUnique`/`update`/`updateMany`/`delete`/`upsert` — esses exigem campos',
      '// obrigatórios (`data`, `create`/`update`, `where` com forma `WhereUniqueInput`)',
      '// que o tipo genérico de retorno de `injectTenant` não consegue expressar;',
      '// `findMany`/`findFirst`/`deleteMany` usam `WhereInput` (solto, sem campo',
      '// obrigatório extra) e já tipam certo sem o segundo cast — adicioná-lo ali',
      '// vira erro de lint (`no-unnecessary-type-assertion`), achado real rodando',
      '// `tsc --build`/`eslint` contra um projeto regenerado (retro do Épico 3).',
      '// Nenhum cast vaza pro chamador — confirmado: `db.<model>.findMany(...)`',
      '// continua tipado especificamente pro model real.',
      'interface WithWhere {',
      '  where?: Record<string, unknown>;',
      '}',
      '',
      'export function forTenant(tenantId: string) {',
      '  return prisma.$extends({',
      '    query: {',
      '      $allModels: {',
      '        async findMany({ args, query }) {',
      '          return query(injectTenant(args as WithWhere, tenantId));',
      '        },',
      '        async findFirst({ args, query }) {',
      '          return query(injectTenant(args as WithWhere, tenantId));',
      '        },',
      '        async findUnique({ args, query }) {',
      '          return query(injectTenant(args as WithWhere, tenantId) as typeof args);',
      '        },',
      '        async update({ args, query }) {',
      '          return query(injectTenant(args as WithWhere, tenantId) as typeof args);',
      '        },',
      '        async updateMany({ args, query }) {',
      '          return query(injectTenant(args as WithWhere, tenantId) as typeof args);',
      '        },',
      '        async delete({ args, query }) {',
      '          return query(injectTenant(args as WithWhere, tenantId) as typeof args);',
      '        },',
      '        async deleteMany({ args, query }) {',
      '          return query(injectTenant(args as WithWhere, tenantId));',
      '        },',
      '        async upsert({ args, query }) {',
      '          return query(injectTenant(args as WithWhere, tenantId) as typeof args);',
      '        },',
      '      },',
      '    },',
      '  });',
      '}',
      '',
    ].join('\n'),

    'src/extensions/tenant.test.ts': [
      "import { describe, it, expect } from 'vitest';",
      "import { injectTenant } from './tenant.js';",
      '',
      "describe('injectTenant', () => {",
      "  it('injeta tenantId quando args não tem where nenhum', () => {",
      "    expect(injectTenant({}, 'tenant-1')).toEqual({",
      "      where: { tenantId: 'tenant-1' },",
      '    });',
      '  });',
      '',
      "  it('preserva os outros campos de where do caller', () => {",
      '    const result = injectTenant(',
      "      { where: { slug: 'orders' } },",
      "      'tenant-1',",
      '    );',
      '',
      '    expect(result).toEqual({',
      "      where: { slug: 'orders', tenantId: 'tenant-1' },",
      '    });',
      '  });',
      '',
      "  it('tenantId injetado sempre vence — where malicioso com seu próprio tenantId não consegue sobrescrever (AD-5)', () => {",
      '    const result = injectTenant(',
      "      { where: { tenantId: 'tenant-do-atacante' } },",
      "      'tenant-1',",
      '    );',
      '',
      "    expect(result.where.tenantId).toBe('tenant-1');",
      '  });',
      '',
      "  it('preserva campos fora de where (ex.: select/include)', () => {",
      '    const result = injectTenant(',
      "      { where: { slug: 'orders' }, select: { id: true } },",
      "      'tenant-1',",
      '    );',
      '',
      '    expect(result).toEqual({',
      "      where: { slug: 'orders', tenantId: 'tenant-1' },",
      '      select: { id: true },',
      '    });',
      '  });',
      '});',
      '',
    ].join('\n'),
  };
}
