export function buildDockerFiles(projectName: string): Record<string, string> {
  return {
    'docker-compose.dev.yml': [
      '# Gerado por `aether-admin new` — dependências de dev (FR-23). Credenciais consistentes',
      '# com .env.development (defaults não-secretos, prontos pra rodar).',
      'services:',
      '  postgres:',
      '    image: postgres:17-alpine',
      '    environment:',
      '      POSTGRES_USER: aether_dev',
      '      POSTGRES_PASSWORD: aether_dev_password',
      '      POSTGRES_DB: aether_dev',
      '    ports:',
      '      - "5432:5432"',
      '    volumes:',
      `      - ${projectName}_postgres_data:/var/lib/postgresql/data`,
      '',
      '  mailpit:',
      '    image: axllent/mailpit:latest',
      '    ports:',
      '      - "1025:1025" # SMTP — captura de email em dev (FR-20)',
      '      - "8025:8025" # UI web pra ver os emails capturados',
      '',
      'volumes:',
      `  ${projectName}_postgres_data:`,
      '',
    ].join('\n'),

    'Dockerfile.dev': [
      '# Dev only — SEM hardening. Não é o Dockerfile de produção (AD-9, Fast-follow, fora do MVP).',
      'FROM node:24-slim',
      '',
      'WORKDIR /app',
      '',
      'RUN corepack enable',
      '',
      'COPY . .',
      'RUN pnpm install',
      '',
      'CMD ["pnpm", "run", "dev"]',
      '',
    ].join('\n'),
  };
}
