export function buildNotificationFiles(): Record<string, string> {
  return {
    // --- EmailProvider (FR-18, AD-4) — porta + adapter local SMTP/Mailpit ---
    'src/core/notifications/email-provider.ts': [
      '// Interface unificada de email transacional (FR-18, AD-4) — um único método',
      '// de envio, nunca um método por tipo de email (`sendPasswordReset`,',
      '// `sendWelcome`, ...). Trocar de implementação não exige alterar nenhum',
      '// código consumidor.',
      'export interface EmailProvider {',
      '  send(message: EmailMessage): Promise<void>;',
      '}',
      '',
      '// Union discriminada por `template` — cada template tem seu próprio shape de',
      '// dados (nunca um `Record<string, unknown>` solto). Adicionar um novo',
      '// template é só um novo membro desta union — a assinatura de `send` nunca',
      '// muda (FR-18: "desenhada pra múltiplos templates desde o início"). Prova',
      '// real: `account-setup` (Story 5.1) foi acrescentado exatamente assim, sem',
      '// tocar `EmailProvider`/`SmtpEmailProvider.send()`.',
      'export type EmailMessage = PasswordResetEmail | AccountSetupEmail;',
      '',
      'export interface PasswordResetEmail {',
      "  template: 'password-reset';",
      '  to: string;',
      '  data: {',
      '    resetLink: string;',
      '    expiresInMinutes: number;',
      '  };',
      '}',
      '',
      '// Usuário criado por um admin (Story 5.1, FR-14) — sem senha usável ainda,',
      '// reaproveita o MESMO PasswordResetTokenStore (Epic 4) pra configurar a',
      '// primeira senha de verdade.',
      'export interface AccountSetupEmail {',
      "  template: 'account-setup';",
      '  to: string;',
      '  data: {',
      '    setupLink: string;',
      '    expiresInMinutes: number;',
      '  };',
      '}',
      '',
    ].join('\n'),

    // SmtpEmailProvider — única implementação do MVP (FR-18: "um provedor
    // implementado"). A MESMA classe atende dev (Mailpit, Story 1.1) e um relay
    // SMTP real de produção (fora do MVP, AD-9), diferindo só pela configuração
    // injetada (host/porta) — nunca por um branch `if (dev)` no código.
    'src/core/notifications/smtp-email-provider.ts': [
      "import nodemailer from 'nodemailer';",
      "import type { EmailProvider, EmailMessage } from './email-provider.js';",
      '',
      'export interface SmtpEmailProviderOptions {',
      '  host: string;',
      '  port: number;',
      '  from: string;',
      '}',
      '',
      'interface RenderedEmail {',
      '  subject: string;',
      '  text: string;',
      '  html: string;',
      '}',
      '',
      '// `switch` exaustivo sobre `message.template` — TypeScript obriga tratar todo',
      '// membro da union; adicionar um template novo sem o `case` correspondente',
      '// aqui é erro de compilação, não bug silencioso em runtime. Função pura —',
      '// testável sem transporte SMTP nenhum (mesmo padrão de `injectTenant`/',
      '// `buildModuleMigrationSql`, Épico 3: função pura primeiro, I/O depois).',
      'export function renderTemplate(message: EmailMessage): RenderedEmail {',
      '  switch (message.template) {',
      "    case 'password-reset': {",
      '      const { resetLink, expiresInMinutes } = message.data;',
      '      return {',
      "        subject: 'Redefinição de senha',",
      '        text:',
      '          `Clique no link para redefinir sua senha: ${resetLink}\\n` +',
      '          `Este link expira em ${expiresInMinutes} minutos.`,',
      '        html:',
      '          `<p>Clique no link para redefinir sua senha: ` +',
      '          `<a href="${resetLink}">${resetLink}</a></p>` +',
      '          `<p>Este link expira em ${expiresInMinutes} minutos.</p>`,',
      '      };',
      '    }',
      "    case 'account-setup': {",
      '      const { setupLink, expiresInMinutes } = message.data;',
      '      return {',
      "        subject: 'Configure sua senha',",
      '        text:',
      '          `Clique no link para configurar sua senha: ${setupLink}\\n` +',
      '          `Este link expira em ${expiresInMinutes} minutos.`,',
      '        html:',
      '          `<p>Clique no link para configurar sua senha: ` +',
      '          `<a href="${setupLink}">${setupLink}</a></p>` +',
      '          `<p>Este link expira em ${expiresInMinutes} minutos.</p>`,',
      '      };',
      '    }',
      '  }',
      '}',
      '',
      '// host/porta/from são injetados via construtor, nunca lidos de `process.env`',
      '// aqui dentro — só `core/providers.ts` lê o ambiente (AD-4, mesmo padrão de',
      '// `Argon2AuthProvider`/`EnvSecretsProvider`, Story 2.1).',
      'export class SmtpEmailProvider implements EmailProvider {',
      '  private readonly transporter: ReturnType<typeof nodemailer.createTransport>;',
      '  private readonly from: string;',
      '',
      '  constructor(options: SmtpEmailProviderOptions) {',
      '    this.transporter = nodemailer.createTransport({',
      '      host: options.host,',
      '      port: options.port,',
      '      secure: false,',
      '    });',
      '    this.from = options.from;',
      '  }',
      '',
      '  async send(message: EmailMessage): Promise<void> {',
      '    const { subject, text, html } = renderTemplate(message);',
      '    await this.transporter.sendMail({',
      '      from: this.from,',
      '      to: message.to,',
      '      subject,',
      '      text,',
      '      html,',
      '    });',
      '  }',
      '}',
      '',
    ].join('\n'),

    'src/core/notifications/smtp-email-provider.test.ts': [
      "import { describe, it, expect, beforeEach } from 'vitest';",
      "import { SmtpEmailProvider, renderTemplate } from './smtp-email-provider.js';",
      '',
      "describe('renderTemplate', () => {",
      "  it('renderiza password-reset com assunto, texto e HTML contendo o link e o prazo', () => {",
      '    const rendered = renderTemplate({',
      "      template: 'password-reset',",
      "      to: 'usuario@example.com',",
      '      data: {',
      "        resetLink: 'https://app.example.com/reset/abc123',",
      '        expiresInMinutes: 30,',
      '      },',
      '    });',
      '',
      "    expect(rendered.subject).toBe('Redefinição de senha');",
      "    expect(rendered.text).toContain('https://app.example.com/reset/abc123');",
      "    expect(rendered.text).toContain('30');",
      "    expect(rendered.html).toContain('https://app.example.com/reset/abc123');",
      "    expect(rendered.html).toContain('30');",
      '  });',
      '',
      "  it('renderiza account-setup com assunto, texto e HTML contendo o link e o prazo (Story 5.1)', () => {",
      '    const rendered = renderTemplate({',
      "      template: 'account-setup',",
      "      to: 'usuario@example.com',",
      '      data: {',
      "        setupLink: 'https://app.example.com/setup/abc123',",
      '        expiresInMinutes: 60,',
      '      },',
      '    });',
      '',
      "    expect(rendered.subject).toBe('Configure sua senha');",
      "    expect(rendered.text).toContain('https://app.example.com/setup/abc123');",
      "    expect(rendered.text).toContain('60');",
      "    expect(rendered.html).toContain('https://app.example.com/setup/abc123');",
      "    expect(rendered.html).toContain('60');",
      '  });',
      '});',
      '',
      '// Mailpit real (Story 1.1, docker-compose.dev.yml) — nunca mockar o',
      '// transporte SMTP, mesmo racional de nunca mockar o Postgres quando um real',
      '// está disponível (padrão de todo o Épico 3). Precisa do Mailpit rodando:',
      '// `docker compose -f docker/docker-compose.dev.yml up -d mailpit`. Reaproveita',
      '// `SMTP_HOST` pro host da API HTTP também — é o mesmo "onde o Mailpit está"',
      '// pros dois protocolos, nunca hardcoded (achado real de validação: rodar o',
      '// teste de um container alcançando o Mailpit por nome, não por `localhost`,',
      '// quebrava se o host da API HTTP estivesse fixo).',
      "const MAILPIT_UI_URL = `http://${process.env.SMTP_HOST ?? 'localhost'}:${process.env.MAILPIT_UI_PORT ?? '8025'}`;",
      '',
      'interface MailpitMessageSummary {',
      '  ID: string;',
      '  To: { Address: string }[];',
      '  Subject: string;',
      '}',
      '',
      'describe.skipIf(!process.env.MAILPIT_SMTP_PORT)(',
      "  'SmtpEmailProvider (integração real, precisa do Mailpit rodando)',",
      '  () => {',
      '    const provider = new SmtpEmailProvider({',
      "      host: process.env.SMTP_HOST ?? 'localhost',",
      '      port: Number(process.env.MAILPIT_SMTP_PORT),',
      "      from: 'no-reply@aether.local',",
      '    });',
      '',
      '    beforeEach(async () => {',
      '      // Limpa a caixa do Mailpit antes de cada teste — achado do retro do',
      '      // Épico 3 (F4): nunca acumular mensagens num Mailpit compartilhado do',
      '      // Laboratório Integrit.',
      "      await fetch(`${MAILPIT_UI_URL}/api/v1/messages`, { method: 'DELETE' });",
      '    });',
      '',
      "    it('envia password-reset de verdade e o Mailpit captura destinatário/assunto/corpo', async () => {",
      '      await provider.send({',
      "        template: 'password-reset',",
      "        to: 'usuario@example.com',",
      '        data: {',
      "          resetLink: 'https://app.example.com/reset/abc123',",
      '          expiresInMinutes: 30,',
      '        },',
      '      });',
      '',
      '      const list = (await fetch(`${MAILPIT_UI_URL}/api/v1/messages`).then(',
      '        (res) => res.json(),',
      '      )) as { messages: MailpitMessageSummary[] };',
      '      expect(list.messages).toHaveLength(1);',
      '      const [message] = list.messages;',
      "      expect(message?.To[0]?.Address).toBe('usuario@example.com');",
      "      expect(message?.Subject).toBe('Redefinição de senha');",
      '',
      '      const detail = (await fetch(',
      '        `${MAILPIT_UI_URL}/api/v1/message/${message?.ID}`,',
      '      ).then((res) => res.json())) as { Text: string };',
      "      expect(detail.Text).toContain('https://app.example.com/reset/abc123');",
      '    });',
      '  },',
      ');',
      '',
    ].join('\n'),
  };
}
