export function buildRateLimitFiles(): Record<string, string> {
  return {
    // --- RateLimiter (FR-28, AC #1) — porta + adapter local. Mecanismo único reaproveitado ---
    // por login (esta story) e, no futuro, redefinição de senha (Epic 4) — nunca uma segunda
    // implementação paralela (AD-10). Ver Dev Notes da Story 2.2 pra reconciliação sobre por
    // que isso é uma chamada explícita na procedure, não um plugin Fastify/middleware tRPC.
    'src/core/auth/rate-limiter.ts': [
      '// Um identificador lógico por tentativa: email escopado por tenant + IP global (AD-5 —',
      '// um atacante não respeita fronteira de tenant, então IP nunca é escopado).',
      'export interface RateLimitIdentity {',
      '  tenantId: string;',
      '  email: string;',
      '  ip: string;',
      '}',
      '',
      'export interface RateLimiter {',
      '  // true se QUALQUER identificador derivado desta identity já excedeu o limite na',
      '  // janela atual — a procedure chamadora não precisa saber qual dos dois bloqueou.',
      '  isBlocked(identity: RateLimitIdentity): Promise<boolean>;',
      '  // Registra uma tentativa com credenciais inválidas pros identificadores derivados.',
      '  // Nunca chamado em login bem-sucedido (AC #5).',
      '  recordFailure(identity: RateLimitIdentity): Promise<void>;',
      '}',
      '',
    ].join('\n'),

    // Estrutural (mesmo racional de refresh-token-store.ts) — só o recorte que
    // PrismaRateLimiter precisa do Prisma Client.
    'src/core/auth/rate-limit-store.ts': [
      'export interface RateLimitHitRecord {',
      '  identifier: string;',
      '  windowStart: Date;',
      '  count: number;',
      '}',
      '',
      'export interface RateLimitStore {',
      '  rateLimitHit: {',
      '    upsert(args: {',
      '      where: {',
      '        identifier_windowStart: { identifier: string; windowStart: Date };',
      '      };',
      '      update: { count: { increment: number } };',
      '      create: { identifier: string; windowStart: Date; count: number };',
      '    }): Promise<RateLimitHitRecord>;',
      '    findUnique(args: {',
      '      where: {',
      '        identifier_windowStart: { identifier: string; windowStart: Date };',
      '      };',
      '    }): Promise<RateLimitHitRecord | null>;',
      '  };',
      '}',
      '',
    ].join('\n'),

    'src/core/auth/prisma-rate-limiter.ts': [
      "import type { RateLimiter, RateLimitIdentity } from './rate-limiter.js';",
      "import type { RateLimitStore } from './rate-limit-store.js';",
      '',
      '// Baseline OWASP (Authentication Cheat Sheet / WSTG, faixa 5-10 tentativas, lockout',
      '// medido em minutos) — valor mais conservador da faixa. Nomeadas, nunca mágicas soltas',
      '// no código (mesmo padrão de ARGON2_OPTIONS/ACCESS_TOKEN_TTL da Story 2.1).',
      'const RATE_LIMIT_MAX_ATTEMPTS = 5;',
      'const RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;',
      '',
      'function deriveIdentifiers(identity: RateLimitIdentity): string[] {',
      '  return [`email:${identity.tenantId}:${identity.email}`, `ip:${identity.ip}`];',
      '}',
      '',
      'export class PrismaRateLimiter implements RateLimiter {',
      '  constructor(',
      '    private readonly db: RateLimitStore,',
      '    // Injetável pra teste (janela expira sem precisar de fake timer) — produção',
      '    // nunca passa isto, usa o default `Date.now`.',
      '    private readonly now: () => number = Date.now,',
      '  ) {}',
      '',
      '  private currentWindowStart(): Date {',
      '    const windowMs = RATE_LIMIT_WINDOW_MS;',
      '    return new Date(Math.floor(this.now() / windowMs) * windowMs);',
      '  }',
      '',
      '  async isBlocked(identity: RateLimitIdentity): Promise<boolean> {',
      '    const windowStart = this.currentWindowStart();',
      '',
      '    const records = await Promise.all(',
      '      deriveIdentifiers(identity).map((identifier) =>',
      '        this.db.rateLimitHit.findUnique({',
      '          where: { identifier_windowStart: { identifier, windowStart } },',
      '        }),',
      '      ),',
      '    );',
      '',
      '    return records.some(',
      '      (record) => (record?.count ?? 0) >= RATE_LIMIT_MAX_ATTEMPTS,',
      '    );',
      '  }',
      '',
      '  async recordFailure(identity: RateLimitIdentity): Promise<void> {',
      '    const windowStart = this.currentWindowStart();',
      '',
      '    // upsert atômico no banco — nunca "ler count, somar 1, escrever" em dois passos,',
      '    // que teria uma janela de corrida sob requisições concorrentes pro mesmo',
      '    // identificador (mesma classe de TOCTOU corrigida no code review da Story 2.1).',
      '    await Promise.all(',
      '      deriveIdentifiers(identity).map((identifier) =>',
      '        this.db.rateLimitHit.upsert({',
      '          where: { identifier_windowStart: { identifier, windowStart } },',
      '          update: { count: { increment: 1 } },',
      '          create: { identifier, windowStart, count: 1 },',
      '        }),',
      '      ),',
      '    );',
      '  }',
      '}',
      '',
    ].join('\n'),

    'src/core/auth/prisma-rate-limiter.test.ts': [
      "import { describe, it, expect } from 'vitest';",
      "import { PrismaRateLimiter } from './prisma-rate-limiter.js';",
      "import type {",
      '  RateLimitStore,',
      '  RateLimitHitRecord,',
      "} from './rate-limit-store.js';",
      '',
      '// Fake em memória que simula o comportamento atômico de upsert do Postgres —',
      '// sem nenhum `await` entre ler e escrever a entrada do Map, então uma implementação',
      "// real (\"ler count, somar 1, escrever\" em dois passos) FALHARIA o teste de",
      '// concorrência abaixo, exatamente como pretendido.',
      'function makeInMemoryStore(): RateLimitStore {',
      '  const rows = new Map<string, RateLimitHitRecord>();',
      '  const key = (identifier: string, windowStart: Date) =>',
      '    `${identifier}|${windowStart.getTime()}`;',
      '  return {',
      '    rateLimitHit: {',
      '      async upsert({ where, update, create }) {',
      '        const { identifier, windowStart } = where.identifier_windowStart;',
      '        const k = key(identifier, windowStart);',
      '        const existing = rows.get(k);',
      '        const record: RateLimitHitRecord = existing',
      '          ? { ...existing, count: existing.count + update.count.increment }',
      '          : { identifier, windowStart, count: create.count };',
      '        rows.set(k, record);',
      '        return record;',
      '      },',
      '      async findUnique({ where }) {',
      '        const { identifier, windowStart } = where.identifier_windowStart;',
      '        return rows.get(key(identifier, windowStart)) ?? null;',
      '      },',
      '    },',
      '  };',
      '}',
      '',
      "const IDENTITY = {",
      "  tenantId: 'tenant-1',",
      "  email: 'ada@example.com',",
      "  ip: '203.0.113.10',",
      '};',
      '',
      "describe('PrismaRateLimiter', () => {",
      "  it('bloqueia depois de 5 falhas pro mesmo identificador (AC #4)', async () => {",
      '    const limiter = new PrismaRateLimiter(makeInMemoryStore());',
      '',
      '    for (let i = 0; i < 5; i++) {',
      '      expect(await limiter.isBlocked(IDENTITY)).toBe(false);',
      '      await limiter.recordFailure(IDENTITY);',
      '    }',
      '',
      '    expect(await limiter.isBlocked(IDENTITY)).toBe(true);',
      '  });',
      '',
      "  it('janela expira e reseta o contador (AC #4)', async () => {",
      '    let now = Date.parse(\'2026-01-01T00:00:00.000Z\');',
      '    const limiter = new PrismaRateLimiter(makeInMemoryStore(), () => now);',
      '',
      '    for (let i = 0; i < 5; i++) {',
      '      await limiter.recordFailure(IDENTITY);',
      '    }',
      '    expect(await limiter.isBlocked(IDENTITY)).toBe(true);',
      '',
      '    now += 16 * 60 * 1000; // 16min depois — nova janela de 15min',
      '',
      '    expect(await limiter.isBlocked(IDENTITY)).toBe(false);',
      '  });',
      '',
      "  it('identificadores distintos não interferem entre si (AC #3)', async () => {",
      '    const limiter = new PrismaRateLimiter(makeInMemoryStore());',
      '    const other = { ...IDENTITY, email: \'outra@example.com\', ip: \'198.51.100.7\' };',
      '',
      '    for (let i = 0; i < 5; i++) {',
      '      await limiter.recordFailure(IDENTITY);',
      '    }',
      '',
      '    expect(await limiter.isBlocked(IDENTITY)).toBe(true);',
      '    expect(await limiter.isBlocked(other)).toBe(false);',
      '  });',
      '',
      "  it('mesmo email em tenants diferentes não compartilha bloqueio (AC #3, AD-5)', async () => {",
      '    const limiter = new PrismaRateLimiter(makeInMemoryStore());',
      '    const otherTenant = { ...IDENTITY, tenantId: \'tenant-2\', ip: \'198.51.100.7\' };',
      '',
      '    for (let i = 0; i < 5; i++) {',
      '      await limiter.recordFailure(IDENTITY);',
      '    }',
      '',
      '    expect(await limiter.isBlocked(IDENTITY)).toBe(true);',
      '    expect(await limiter.isBlocked(otherTenant)).toBe(false);',
      '  });',
      '',
      "  it('IP é global, não escopado por tenant (AC #3, AD-5)', async () => {",
      '    const limiter = new PrismaRateLimiter(makeInMemoryStore());',
      '    const sameIpOtherTenant = {',
      "      tenantId: 'tenant-2',",
      "      email: 'outra-pessoa@example.com',",
      '      ip: IDENTITY.ip,',
      '    };',
      '',
      '    for (let i = 0; i < 5; i++) {',
      '      await limiter.recordFailure(IDENTITY);',
      '    }',
      '',
      '    // Mesmo IP, tenant e email diferentes — ainda bloqueado, porque o identificador',
      '    // `ip:<ip>` é compartilhado entre os dois (um atacante não respeita tenant).',
      '    expect(await limiter.isBlocked(sameIpOtherTenant)).toBe(true);',
      '  });',
      '',
      "  it('recordFailure concorrente pro mesmo identificador soma corretamente, sem perder incrementos', async () => {",
      '    const limiter = new PrismaRateLimiter(makeInMemoryStore());',
      '',
      '    await Promise.all([',
      '      limiter.recordFailure(IDENTITY),',
      '      limiter.recordFailure(IDENTITY),',
      '      limiter.recordFailure(IDENTITY),',
      '    ]);',
      '',
      '    // 3 falhas concorrentes registradas -- ainda não bloqueado (limite é 5) mas as 3',
      '    // devem ter sido contadas; mais 2 fecha o bloqueio.',
      '    expect(await limiter.isBlocked(IDENTITY)).toBe(false);',
      '    await limiter.recordFailure(IDENTITY);',
      '    await limiter.recordFailure(IDENTITY);',
      '    expect(await limiter.isBlocked(IDENTITY)).toBe(true);',
      '  });',
      '});',
      '',
    ].join('\n'),
  };
}
