export function buildRootFiles(projectName: string): Record<string, string> {
  return {
    'package.json':
      JSON.stringify(
        {
          name: projectName,
          private: true,
          version: '0.0.1',
          type: 'module',
          engines: { node: '24.x' },
          // Fixa a versão do pnpm que o Corepack deve ativar — sem isso, `corepack
          // enable` num build Docker do zero (Dockerfile.dev) não tem o que fixar
          // como versão (achado do code review, AC #9).
          packageManager: 'pnpm@11.24.0',
          scripts: {
            dev: 'echo "aether-admin dev chega na Epic 1 Story 3 (FR-4)"',
            lint: 'eslint .',
            'format:check': 'prettier --check .',
            format: 'prettier --write .',
            test: 'vitest run',
            typecheck: 'tsc --build',
          },
          devDependencies: {
            typescript: '5.9.3',
            eslint: '10.9.1',
            '@eslint/js': '10.0.1',
            'typescript-eslint': '8.68.0',
            prettier: '3.9.6',
            vitest: '4.1.11',
          },
        },
        null,
        2,
      ) + '\n',

    'pnpm-workspace.yaml': [
      'packages:',
      '  - "apps/*"',
      '  - "packages/*"',
      '',
      '# pnpm 11 bloqueia scripts de postinstall por padrão (supply-chain security) —',
      '# sem isso, `pnpm install` falha com ERR_PNPM_IGNORED_BUILDS na primeira vez que',
      '# alguém roda `aether-admin new`, mesmo sem nenhum problema real (esbuild é',
      '# dependência legítima do próprio stack pinado pela Architecture Spine, via',
      '# Vite/Vitest).',
      '#',
      '# @prisma/engines precisa do seu postinstall (baixa o binário real do schema',
      '# engine) — aprovado abaixo. Já o preinstall do pacote `prisma` em si trava de',
      "# verdade neste ambiente (Windows/Git Bash/pnpm 11.24 — 'Error: readStream must",
      "# be readable' em pnpm.mjs, reproduzido isolado, sem nenhum código deste",
      '# projeto no caminho — bug do próprio pnpm rodando esse lifecycle script',
      '# específico). O script em si só faz uma checagem de telemetria não-essencial',
      '# (scripts/preinstall-entry.js, com try/catch em volta de tudo) — negado',
      '# explicitamente abaixo via `allowBuilds: { prisma: false }` (sintaxe gerada',
      "# pelo próprio `pnpm approve-builds '!prisma'`), não só omitido, porque omitir",
      '# ainda deixa o install saindo com exit code 1 (ERR_PNPM_IGNORED_BUILDS). Negar',
      '# explicitamente é limpo — instala normalmente, schema engine funciona,',
      '# `prisma generate`/`migrate` não dependem desse script pra nada.',
      '#',
      '# argon2 (Story 2.1) também tem script de install (node-gyp-build, resolve o binário',
      '# nativo pré-compilado pra essa plataforma) — sem aprovar, ERR_PNPM_IGNORED_BUILDS de',
      '# novo. Diferente do preinstall do `prisma`, este é necessário (sem ele o binário',
      '# nativo não resolve) e não crasha neste ambiente — testado e aprovado normalmente.',
      'onlyBuiltDependencies:',
      '  - esbuild',
      '  - "@prisma/engines"',
      '  - argon2',
      'allowBuilds:',
      '  esbuild: true',
      '  "@prisma/engines": true',
      '  prisma: false',
      '  argon2: true',
      '',
    ].join('\n'),

    'tsconfig.json':
      JSON.stringify(
        {
          files: [],
          references: [
            { path: 'apps/web' },
            { path: 'apps/api' },
            { path: 'packages/shared' },
            { path: 'packages/db' },
          ],
        },
        null,
        2,
      ) + '\n',

    'tsconfig.base.json':
      JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2023',
            module: 'NodeNext',
            moduleResolution: 'NodeNext',
            lib: ['ES2023'],
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
            resolveJsonModule: true,
            declaration: true,
            declarationMap: true,
          },
        },
        null,
        2,
      ) + '\n',

    'eslint.config.js': [
      "import js from '@eslint/js';",
      "import tseslint from 'typescript-eslint';",
      '',
      'export default tseslint.config(',
      '  {',
      "    ignores: ['**/dist/**', '**/node_modules/**'],",
      '  },',
      '  js.configs.recommended,',
      '  ...tseslint.configs.recommendedTypeChecked,',
      '  ...tseslint.configs.stylisticTypeChecked,',
      '  {',
      '    languageOptions: {',
      '      parserOptions: {',
      '        projectService: {',
      '          // Arquivos de config (raiz e por pacote) não entram no include de nenhum',
      '          // tsconfig do monorepo — sem isso o ESLint typed falha com "not found by',
      '          // the project service" pra cada um deles. typescript-eslint proíbe glob',
      "          // com '**' aqui (custo de performance) — por isso a lista é explícita.",
      '          // prisma.config.ts NÃO entra aqui — já está coberto pelo tsconfig real de',
      '          // packages/db (senão colide com "found in the project service").',
      '          allowDefaultProject: [',
      "            'eslint.config.js',",
      "            'vitest.config.ts',",
      "            'vitest.shared.ts',",
      "            'apps/web/vite.config.ts',",
      "            'apps/web/vitest.config.ts',",
      "            'apps/api/vitest.config.ts',",
      "            'packages/shared/vitest.config.ts',",
      '          ],',
      '        },',
      '        tsconfigRootDir: import.meta.dirname,',
      '      },',
      '    },',
      '  },',
      '  {',
      '    // O "default project" (allowDefaultProject acima) não tem strict mode nem',
      '    // resolução completa de módulos — regras type-aware não funcionam direito',
      '    // pra esses arquivos de config. Config oficial do typescript-eslint pra isso.',
      '    files: [',
      "      'eslint.config.js',",
      "      'vitest.config.ts',",
      "      'vitest.shared.ts',",
      "      'apps/web/vite.config.ts',",
      "      'apps/web/vitest.config.ts',",
      "      'apps/api/vitest.config.ts',",
      "      'packages/shared/vitest.config.ts',",
      '    ],',
      '    ...tseslint.configs.disableTypeChecked,',
      '  },',
      '  {',
      '    // AD-3 verificável por ferramenta, não só por convenção: NENHUM arquivo de',
      "    // apps/web pode importar de 'api' — nem tipo, nem valor — EXCETO",
      '    // trpc/client.ts (bloco seguinte). Achado do code review: a versão anterior',
      '    // desta regra liberava `allowTypeImports: true` pra qualquer arquivo de',
      '    // apps/web, não só pro único arquivo que a AC #5 permite.',
      "    files: ['apps/web/**/*.ts', 'apps/web/**/*.tsx'],",
      "    ignores: ['apps/web/src/trpc/client.ts'],",
      '    rules: {',
      "      '@typescript-eslint/no-restricted-imports': [",
      "        'error',",
      '        {',
      '          patterns: [',
      '            {',
      "              group: ['api', 'api/*'],",
      '              message:',
      "                'só apps/web/src/trpc/client.ts pode importar de `api`, e só tipo (AD-3, AC #5).',",
      '            },',
      '          ],',
      '        },',
      '      ],',
      '    },',
      '  },',
      '  {',
      '    // Único arquivo autorizado (bloco anterior) — mesmo aqui, só TIPO, nunca valor.',
      "    files: ['apps/web/src/trpc/client.ts'],",
      '    rules: {',
      "      '@typescript-eslint/no-restricted-imports': [",
      "        'error',",
      '        {',
      '          patterns: [',
      '            {',
      "              group: ['api', 'api/*'],",
      '              allowTypeImports: true,',
      '              message:',
      "                'apps/web só pode importar TIPO de `api` (AD-3) — nunca valor.',",
      '            },',
      '          ],',
      '        },',
      '      ],',
      '    },',
      '  },',
      '  {',
      '    // packages/shared não importa nada de apps/* (AD-3) — nem tipo, nem valor.',
      "    files: ['packages/shared/**/*.ts'],",
      '    rules: {',
      "      'no-restricted-imports': [",
      "        'error',",
      '        {',
      "          patterns: [{ group: ['api', 'api/*', 'web', 'web/*'], message: 'packages/shared não pode importar de apps/* (AD-3).' }],",
      '        },',
      '      ],',
      '    },',
      '  },',
      '  {',
      '    // Mocks/stubs de teste (vi.fn(async () => ...) satisfazendo uma interface',
      '    // Promise<T>, sem await interno; expect(obj.metodo).toHaveBeenCalledWith(...)',
      '    // sem chamar) são padrões legítimos e comuns em teste — não indicam bug real',
      '    // aqui, ao contrário do código de produção (Story 2.1, achado real do lint).',
      '    // no-unsafe-assignment: matchers assimétricos do vitest (expect.any(),',
      '    // expect.objectContaining()) são tipados `any` de propósito — atribuí-los a',
      '    // uma posição de tipo conhecido (ex.: `maxAge: expect.any(Number)` contra',
      '    // `CookieSerializeOptions.maxAge?: number`) é o padrão normal de asserção',
      '    // de mock, não um `any` real vazando (Story 2.1, achado real do lint).',
      "    files: ['**/*.test.ts'],",
      '    rules: {',
      "      '@typescript-eslint/require-await': 'off',",
      "      '@typescript-eslint/unbound-method': 'off',",
      "      '@typescript-eslint/no-unsafe-assignment': 'off',",
      '    },',
      '  },',
      ');',
      '',
    ].join('\n'),

    '.prettierrc':
      JSON.stringify(
        { singleQuote: true, semi: true, trailingComma: 'all' },
        null,
        2,
      ) + '\n',

    '.env.development': [
      '# Gerado por `aether-admin new` — defaults de dev, não-secretos, prontos pra rodar (FR-6).',
      '# Nível de isolamento de tenant e credenciais reais chegam via `aether-admin` setup de banco (Epic 1 Story 2, FR-2).',
      'DATABASE_URL="postgresql://aether_dev:aether_dev_password@localhost:5432/aether_dev"',
      'API_PORT=3001',
      'WEB_PORT=5173',
      'MAILPIT_SMTP_PORT=1025',
      'MAILPIT_UI_PORT=8025',
      '',
      '# Vite só expõe pro código do cliente variáveis com prefixo VITE_ — duplicata',
      '# proposital de API_PORT, não um valor diferente (achado do code review, AC #7:',
      '# antes esta variável não existia e o client.ts lia algo que nunca resolvia).',
      'VITE_API_PORT=3001',
      '',
      '# Segredos de DEV, fixos e não-secretos de produção — mesmo espírito de',
      '# aether_dev_password acima (FR-6, zero edição manual pra rodar localmente).',
      '# Nunca reaproveitar estes valores literais fora de ambiente de desenvolvimento —',
      '# lidos via SecretsProvider (Story 2.1), nunca hardcoded no código.',
      'ARGON2_PEPPER=dev-only-pepper-3f9a1c7e5b8d4f2a9e6c0b1d7a4f8e2c',
      'JWT_SIGNING_KEY=dev-only-jwt-signing-key-7b2e9f4a1c6d8b3e5f0a9c2d7b4e1f8a6c3d0b9e2f5a8c1d4b7e0f3a6c9d2b5e',
      '',
    ].join('\n'),

    '.gitignore': [
      'node_modules/',
      'dist/',
      '.env',
      '.env.local',
      '*.log',
      '',
    ].join('\n'),

    '.prettierignore': ['node_modules/', 'dist/', 'pnpm-lock.yaml', ''].join(
      '\n',
    ),

    '.nvmrc': '24\n',

    'vitest.config.ts': [
      "import { defineConfig } from 'vitest/config';",
      '',
      'export default defineConfig({',
      '  test: {',
      '    projects: [',
      "      'apps/web/vitest.config.ts',",
      "      'apps/api/vitest.config.ts',",
      "      'packages/shared/vitest.config.ts',",
      '    ],',
      '  },',
      '});',
      '',
    ].join('\n'),

    'vitest.shared.ts': [
      "import { defineConfig } from 'vitest/config';",
      '',
      '// Opções compartilhadas por todo config de pacote — Vitest 4 não permite `extends`',
      '// de um config que já usa `projects` (causaria recursão), então cada pacote importa',
      '// isto diretamente em vez de estender o vitest.config.ts raiz.',
      'export const sharedTestConfig = defineConfig({',
      '  test: {',
      "    include: ['src/**/*.test.ts'],",
      '  },',
      '});',
      '',
    ].join('\n'),
  };
}
