export function buildSharedFiles(): Record<string, string> {
  return {
    'package.json':
      JSON.stringify(
        {
          name: 'shared',
          version: '0.0.1',
          private: true,
          type: 'module',
          exports: {
            './schemas/*': './src/schemas/*.ts',
          },
          dependencies: {
            zod: '4.4.3',
          },
          devDependencies: {
            typescript: '5.9.3',
            vitest: '4.1.11',
          },
        },
        null,
        2,
      ) + '\n',

    'tsconfig.json':
      JSON.stringify(
        {
          extends: '../../tsconfig.base.json',
          compilerOptions: {
            composite: true,
            outDir: 'dist',
            rootDir: 'src',
          },
          include: ['src/**/*.ts'],
        },
        null,
        2,
      ) + '\n',

    'vitest.config.ts': [
      "import { sharedTestConfig } from '../../vitest.shared.js';",
      '',
      'export default sharedTestConfig;',
      '',
    ].join('\n'),

    'src/schemas/auth.ts': [
      "import { z } from 'zod';",
      '',
      '// Fonte única dos schemas de login/refresh (AD-3) — importados por apps/api e',
      '// apps/web, nunca duplicados. Mensagens de validação genéricas de propósito: o',
      '// formato de erro Zod (400) já é distinto do erro de credenciais inválidas (401,',
      '// AC #9) — não precisa ecoar detalhe que ajude enumeração de usuário.',
      'export const loginInputSchema = z.object({',
      '  // .toLowerCase() além do .trim(): @@unique([tenantId, email]) no Prisma é',
      '  // case-sensitive — sem normalizar aqui, "Ada@x.com" e "ada@x.com" seriam',
      '  // tratados como usuários diferentes assim que existir um fluxo de registro.',
      '  email: z.string().trim().toLowerCase().email(),',
      '  // .max(256): limite de tamanho num endpoint público não-autenticado — sem isso,',
      '  // um payload de tamanho arbitrário seria aceito e hasheado via Argon2id.',
      '  password: z.string().min(1).max(256),',
      '  tenantId: z.string().min(1),',
      '});',
      '',
      'export const loginOutputSchema = z.object({',
      '  accessToken: z.string(),',
      '});',
      '',
      '// Mesmo formato de login por enquanto — reaproveita em vez de duplicar o literal',
      '// pra não dessincronizar silenciosamente se um dos dois precisar crescer.',
      'export const refreshOutputSchema = loginOutputSchema;',
      '',
      'export type LoginInput = z.infer<typeof loginInputSchema>;',
      '',
      '// Resposta sempre a mesma, email existindo ou não — nenhum campo que revele o',
      '// resultado da busca (Story 4.2, AC #1, mesma defesa de enumeração do login).',
      'export const requestPasswordResetInputSchema = z.object({',
      '  email: z.string().trim().toLowerCase().email(),',
      '  tenantId: z.string().min(1),',
      '});',
      '',
      '// Mesmo limite de tamanho de loginInputSchema.password (AC #7 original, Story',
      '// 2.1) — um payload de tamanho arbitrário não deveria ser aceito e hasheado.',
      'export const resetPasswordInputSchema = z.object({',
      '  token: z.string().min(1),',
      '  newPassword: z.string().min(1).max(256),',
      '});',
      '',
    ].join('\n'),

    // Fonte única dos schemas de admin.users.* (AD-3, Story 5.1) — importados por
    // apps/api e, no futuro, pelas telas de admin (apps/web) quando existirem.
    'src/schemas/admin.ts': [
      "import { z } from 'zod';",
      '',
      'export const listUsersOutputSchema = z.array(',
      '  z.object({',
      '    id: z.string(),',
      '    email: z.string(),',
      '    isAdmin: z.boolean(),',
      '    createdAt: z.coerce.date(),',
      '  }),',
      ');',
      '',
      '// Mesmas regras de email já usadas em requestPasswordResetInputSchema — sem',
      '// senha no input (Story 5.1, AC #5): o próprio create() nunca aceita uma',
      '// senha, o usuário configura a sua via o email account-setup.',
      'export const createUserInputSchema = z.object({',
      '  email: z.string().trim().toLowerCase().email(),',
      '});',
      '',
      'export const updateUserInputSchema = z.object({',
      '  userId: z.string().min(1),',
      '  email: z.string().trim().toLowerCase().email(),',
      '});',
      '',
    ].join('\n'),

    'src/schemas/system.ts': [
      "import { z } from 'zod';",
      '',
      '// Fonte única dos schemas de `system.hello` (AD-3) — importados por apps/api e apps/web, nunca duplicados.',
      '// Input opcional só pra este único procedure da story já exercitar validação Zod de',
      '// verdade (FR-17) — sem isso, nada nesta story testaria o caminho de erro RFC 9457.',
      'export const systemHelloInputSchema = z',
      '  .object({',
      '    // .trim() + .max() — string só-espaço não deve passar em .min(1), e nada',
      '    // limitava o tamanho aceito/logado antes (achado do code review).',
      '    name: z.string().trim().min(1).max(200).optional(),',
      '  })',
      '  .optional();',
      '',
      'export const systemHelloOutputSchema = z.object({',
      '  message: z.string(),',
      '});',
      '',
      'export type SystemHelloOutput = z.infer<typeof systemHelloOutputSchema>;',
      '',
    ].join('\n'),
  };
}
