export function buildSharedFiles(): Record<string, string> {
  return {
    'package.json':
      JSON.stringify(
        {
          name: 'shared',
          version: '0.0.1',
          private: true,
          type: 'module',
          exports: {
            './schemas/*': './src/schemas/*.ts',
          },
          dependencies: {
            zod: '4.4.3',
          },
          devDependencies: {
            typescript: '5.9.3',
            vitest: '4.1.11',
          },
        },
        null,
        2,
      ) + '\n',

    'tsconfig.json':
      JSON.stringify(
        {
          extends: '../../tsconfig.base.json',
          compilerOptions: {
            composite: true,
            outDir: 'dist',
            rootDir: 'src',
          },
          include: ['src/**/*.ts'],
        },
        null,
        2,
      ) + '\n',

    'vitest.config.ts': [
      "import { sharedTestConfig } from '../../vitest.shared.js';",
      '',
      'export default sharedTestConfig;',
      '',
    ].join('\n'),

    'src/schemas/auth.ts': [
      "import { z } from 'zod';",
      '',
      '// Fonte única dos schemas de login/refresh (AD-3) — importados por apps/api e',
      '// apps/web, nunca duplicados. Mensagens de validação genéricas de propósito: o',
      '// formato de erro Zod (400) já é distinto do erro de credenciais inválidas (401,',
      '// AC #9) — não precisa ecoar detalhe que ajude enumeração de usuário.',
      'export const loginInputSchema = z.object({',
      '  // .toLowerCase() além do .trim(): @@unique([tenantId, email]) no Prisma é',
      '  // case-sensitive — sem normalizar aqui, "Ada@x.com" e "ada@x.com" seriam',
      '  // tratados como usuários diferentes assim que existir um fluxo de registro.',
      '  email: z.string().trim().toLowerCase().email(),',
      '  // .max(256): limite de tamanho num endpoint público não-autenticado — sem isso,',
      '  // um payload de tamanho arbitrário seria aceito e hasheado via Argon2id.',
      '  password: z.string().min(1).max(256),',
      '  tenantId: z.string().min(1),',
      '});',
      '',
      'export const loginOutputSchema = z.object({',
      '  accessToken: z.string(),',
      '});',
      '',
      '// Mesmo formato de login por enquanto — reaproveita em vez de duplicar o literal',
      '// pra não dessincronizar silenciosamente se um dos dois precisar crescer.',
      'export const refreshOutputSchema = loginOutputSchema;',
      '',
      'export type LoginInput = z.infer<typeof loginInputSchema>;',
      '',
      '// Resposta sempre a mesma, email existindo ou não — nenhum campo que revele o',
      '// resultado da busca (Story 4.2, AC #1, mesma defesa de enumeração do login).',
      'export const requestPasswordResetInputSchema = z.object({',
      '  email: z.string().trim().toLowerCase().email(),',
      '  tenantId: z.string().min(1),',
      '});',
      '',
      '// Mesmo limite de tamanho de loginInputSchema.password (AC #7 original, Story',
      '// 2.1) — um payload de tamanho arbitrário não deveria ser aceito e hasheado.',
      'export const resetPasswordInputSchema = z.object({',
      '  token: z.string().min(1),',
      '  newPassword: z.string().min(1).max(256),',
      '});',
      '',
    ].join('\n'),

    // Fonte única dos schemas de admin.users.* (AD-3, Story 5.1) — importados por
    // apps/api e, no futuro, pelas telas de admin (apps/web) quando existirem.
    'src/schemas/admin.ts': [
      "import { z } from 'zod';",
      '',
      'export const listUsersOutputSchema = z.array(',
      '  z.object({',
      '    id: z.string(),',
      '    email: z.string(),',
      '    isAdmin: z.boolean(),',
      '    createdAt: z.coerce.date(),',
      '  }),',
      ');',
      '',
      '// Mesmas regras de email já usadas em requestPasswordResetInputSchema — sem',
      '// senha no input (Story 5.1, AC #5): o próprio create() nunca aceita uma',
      '// senha, o usuário configura a sua via o email account-setup.',
      'export const createUserInputSchema = z.object({',
      '  email: z.string().trim().toLowerCase().email(),',
      '});',
      '',
      'export const updateUserInputSchema = z.object({',
      '  userId: z.string().min(1),',
      '  email: z.string().trim().toLowerCase().email(),',
      '});',
      '',
      '// Story 5.2 — reaproveita TokenRevocationStore.revokeAllForUser (Story 2.1/4.2)',
      '// sem modificação; a procedure é que confirma posse do tenant antes de chamar.',
      'export const revokeSessionsInputSchema = z.object({',
      '  userId: z.string().min(1),',
      '});',
      '',
      '// Story 5.3 — CRUD de Group, sem @@unique de name por tenant (nenhuma AC/FR',
      '// exige isso; Role/Resource SÃO únicos por design, AD-7, mas Group não).',
      'export const listGroupsOutputSchema = z.array(',
      '  z.object({',
      '    id: z.string(),',
      '    name: z.string(),',
      '    createdAt: z.coerce.date(),',
      '  }),',
      ');',
      '',
      '// .max(200) — mesmo limite de systemHelloInputSchema.name; sem isso, um nome',
      '// de tamanho arbitrário seria aceito e persistido (achado do code review).',
      'export const createGroupInputSchema = z.object({',
      '  name: z.string().trim().min(1).max(200),',
      '});',
      '',
      'export const updateGroupInputSchema = z.object({',
      '  groupId: z.string().min(1),',
      '  name: z.string().trim().min(1).max(200),',
      '});',
      '',
      'export const deleteGroupInputSchema = z.object({',
      '  groupId: z.string().min(1),',
      '});',
      '',
      '// Story 5.4 — mesmo padrão de Group (Story 5.3), já com .max(200) desde o',
      '// início (achado do code review da 5.3 aplicado aqui preventivamente).',
      'export const listRolesOutputSchema = z.array(',
      '  z.object({',
      '    id: z.string(),',
      '    name: z.string(),',
      '    createdAt: z.coerce.date(),',
      '  }),',
      ');',
      '',
      'export const createRoleInputSchema = z.object({',
      '  name: z.string().trim().min(1).max(200),',
      '});',
      '',
      'export const updateRoleInputSchema = z.object({',
      '  roleId: z.string().min(1),',
      '  name: z.string().trim().min(1).max(200),',
      '});',
      '',
      'export const deleteRoleInputSchema = z.object({',
      '  roleId: z.string().min(1),',
      '});',
      '',
      '// Story 5.5 — discriminatedUnion replica a forma da CHECK constraint do',
      '// banco (role_assignments_assignee_check, Story 3.1): rejeita com erro Zod',
      '// claro (400) se o caller não mandar NENHUM dos dois campos pro',
      '// assigneeType escolhido. Mandar os DOIS campos juntos não é rejeitado',
      '// pelo schema em si (Zod só descarta o campo extra, não falha) — mas',
      '// nunca é um problema na prática, porque o handler (admin.ts) sempre',
      '// re-deriva userId/groupId a partir de assigneeType, nunca confia no',
      '// campo bruto do input (achado do code review).',
      'export const createRoleAssignmentInputSchema = z.discriminatedUnion(',
      "  'assigneeType',",
      '  [',
      '    z.object({',
      "      assigneeType: z.literal('user'),",
      '      userId: z.string().min(1),',
      '      roleId: z.string().min(1),',
      '      targetModuleId: z.string().min(1),',
      '    }),',
      '    z.object({',
      "      assigneeType: z.literal('group'),",
      '      groupId: z.string().min(1),',
      '      roleId: z.string().min(1),',
      '      targetModuleId: z.string().min(1),',
      '    }),',
      '  ],',
      ');',
      '',
      'export const listRoleAssignmentsInputSchema = z.discriminatedUnion(',
      "  'assigneeType',",
      '  [',
      '    z.object({',
      "      assigneeType: z.literal('user'),",
      '      userId: z.string().min(1),',
      '    }),',
      '    z.object({',
      "      assigneeType: z.literal('group'),",
      '      groupId: z.string().min(1),',
      '    }),',
      '  ],',
      ');',
      '',
      'export const listRoleAssignmentsOutputSchema = z.array(',
      '  z.object({',
      '    id: z.string(),',
      '    roleId: z.string(),',
      '    roleName: z.string(),',
      '    targetModuleId: z.string(),',
      '    targetModuleSlug: z.string(),',
      '    createdAt: z.coerce.date(),',
      '  }),',
      ');',
      '',
      'export const deleteRoleAssignmentInputSchema = z.object({',
      '  roleAssignmentId: z.string().min(1),',
      '});',
      '',
      '// Story 5.6 — mesma FORMA de { groupId, userId } pras duas, mas dois',
      '// `const` distintos de propósito (semânticas diferentes, mesmo que a',
      '// forma coincida hoje — nunca reaproveitar literalmente).',
      'export const addGroupMemberInputSchema = z.object({',
      '  groupId: z.string().min(1),',
      '  userId: z.string().min(1),',
      '});',
      '',
      'export const removeGroupMemberInputSchema = z.object({',
      '  groupId: z.string().min(1),',
      '  userId: z.string().min(1),',
      '});',
      '',
      'export const listGroupMembersInputSchema = z.object({',
      '  groupId: z.string().min(1),',
      '});',
      '',
      '// Mesma FORMA de listUsersOutputSchema (Story 5.1) — const próprio: "membros',
      '// de um Grupo" é conceitualmente diferente de "Usuários do tenant", mesmo',
      '// com os campos coincidindo hoje.',
      'export const listGroupMembersOutputSchema = z.array(',
      '  z.object({',
      '    id: z.string(),',
      '    email: z.string(),',
      '    isAdmin: z.boolean(),',
      '    createdAt: z.coerce.date(),',
      '  }),',
      ');',
      '',
      '// Story 5.7 — mesma decisão de design de addGroupMemberInputSchema/',
      '// removeGroupMemberInputSchema (Story 5.6): forma idêntica, dois `const`',
      '// distintos de propósito.',
      'export const addRoleResourceInputSchema = z.object({',
      '  roleId: z.string().min(1),',
      '  resourceId: z.string().min(1),',
      '});',
      '',
      'export const removeRoleResourceInputSchema = z.object({',
      '  roleId: z.string().min(1),',
      '  resourceId: z.string().min(1),',
      '});',
      '',
      'export const listRoleResourcesInputSchema = z.object({',
      '  roleId: z.string().min(1),',
      '});',
      '',
      "// 'kind' é o enum ResourceKind já existente desde a Story 3.1.",
      'export const listRoleResourcesOutputSchema = z.array(',
      '  z.object({',
      '    id: z.string(),',
      '    name: z.string(),',
      "    kind: z.enum(['NAMED_PERMISSION', 'BUSINESS_OBJECT']),",
      '  }),',
      ');',
      '',
      '// Story 5.8 (FR-15) — o INPUT de bulkImport não é Zod (é FormData bruto, ver',
      '// router.ts); só o resultado por linha tem schema. Um resultado por linha do',
      "// CSV, na ordem original — nunca aborta o lote inteiro por uma linha só.",
      'export const bulkImportUsersResultItemSchema = z.object({',
      '  email: z.string(),',
      "  status: z.enum(['created', 'duplicate', 'invalid']),",
      '});',
      '',
      'export const bulkImportUsersOutputSchema = z.array(',
      '  bulkImportUsersResultItemSchema,',
      ');',
      '',
    ].join('\n'),

    'src/schemas/system.ts': [
      "import { z } from 'zod';",
      '',
      '// Fonte única dos schemas de `system.hello` (AD-3) — importados por apps/api e apps/web, nunca duplicados.',
      '// Input opcional só pra este único procedure da story já exercitar validação Zod de',
      '// verdade (FR-17) — sem isso, nada nesta story testaria o caminho de erro RFC 9457.',
      'export const systemHelloInputSchema = z',
      '  .object({',
      '    // .trim() + .max() — string só-espaço não deve passar em .min(1), e nada',
      '    // limitava o tamanho aceito/logado antes (achado do code review).',
      '    name: z.string().trim().min(1).max(200).optional(),',
      '  })',
      '  .optional();',
      '',
      'export const systemHelloOutputSchema = z.object({',
      '  message: z.string(),',
      '});',
      '',
      'export type SystemHelloOutput = z.infer<typeof systemHelloOutputSchema>;',
      '',
    ].join('\n'),
  };
}
