import { slugToPascalCase, slugToCamelCase } from './naming.js';

/**
 * Arquivos Hexagonais (AD-1) de um Módulo gerado — 4 adapters fixos
 * (schema/resources/repository/router) mais `domain/` de verdade (porta +
 * serviço), não um `.gitkeep` vazio como o módulo `system` (Story 1.1). Ponto de
 * partida mínimo — o desenvolvedor edita à mão pra adicionar campos/regras reais
 * (ver Dev Notes "Escopo explicitamente cortado").
 */
export function buildModuleFiles(slug: string): Record<string, string> {
  const modelName = slugToPascalCase(slug);
  const camel = slugToCamelCase(slug);

  return {
    'domain/ports.ts': [
      `export interface ${modelName}Record {`,
      '  id: string;',
      '  name: string;',
      '  createdAt: Date;',
      '}',
      '',
      `// Porta que \`repository.ts\` implementa — \`domain/service.ts\` só conhece essa`,
      '// interface, nunca Prisma diretamente (AD-1).',
      `export interface ${modelName}Repository {`,
      `  list(tenantId: string): Promise<${modelName}Record[]>;`,
      `  create(tenantId: string, input: { name: string }): Promise<${modelName}Record>;`,
      '}',
      '',
    ].join('\n'),

    'domain/service.ts': [
      `import type { ${modelName}Repository } from './ports.js';`,
      '',
      '// Orquestração de negócio — hoje é passthrough mínimo (ponto de partida), é aqui',
      '// que regra de negócio real entra depois. Nunca importa @prisma/client nem',
      '// @trpc/* (AD-1) — só conhece a porta.',
      `export function list${modelName}(repo: ${modelName}Repository, tenantId: string) {`,
      '  return repo.list(tenantId);',
      '}',
      '',
      `export function create${modelName}(`,
      `  repo: ${modelName}Repository,`,
      '  tenantId: string,',
      '  input: { name: string },',
      ') {',
      '  return repo.create(tenantId, input);',
      '}',
      '',
    ].join('\n'),

    'schema.ts': [
      'export {',
      `  ${camel}CreateInputSchema,`,
      `  ${camel}RecordSchema,`,
      `  ${camel}ListOutputSchema,`,
      `} from 'shared/schemas/${slug}';`,
      '',
    ].join('\n'),

    'resources.ts': [
      `// Recursos deste módulo (AD-7). A migration gerada junto (Task 7) insere`,
      '// Resource rows com os MESMOS nomes, pela mesma convenção `<slug>.<ação>` —',
      '// os dois são derivados independentemente do nome do módulo no momento da',
      '// geração, não um lendo o outro em runtime (corrigido no code review: o',
      '// comentário original aqui afirmava que a migration "lia" este array, o que',
      '// nunca foi verdade). Editar este array à mão NÃO atualiza a árvore de',
      '// identidade já registrada — é só documentação/export de conveniência.',
      `export const ${camel}Resources = ['${slug}.list', '${slug}.create'] as const;`,
      '',
    ].join('\n'),

    'repository.ts': [
      "import { forTenant } from 'db/extensions/tenant';",
      `import type { ${modelName}Repository } from './domain/ports.js';`,
      '',
      '// Implementação concreta da porta — único lugar que fala com Prisma (AD-1).',
      '// Sempre via forTenant (AD-5), nunca o PrismaClient cru.',
      `export const ${camel}Repository: ${modelName}Repository = {`,
      '  async list(tenantId) {',
      '    const db = forTenant(tenantId);',
      `    return db.${camel}.findMany({`,
      '      select: { id: true, name: true, createdAt: true },',
      "      orderBy: { createdAt: 'desc' },",
      '    });',
      '  },',
      '  async create(tenantId, input) {',
      '    const db = forTenant(tenantId);',
      `    return db.${camel}.create({`,
      '      data: { tenantId, name: input.name },',
      '      select: { id: true, name: true, createdAt: true },',
      '    });',
      '  },',
      '};',
      '',
    ].join('\n'),

    'router.ts': [
      "import { router, publicProcedure } from '../../trpc.js';",
      "import { requireResource } from '../../core/authz/require-resource.js';",
      `import { list${modelName}, create${modelName} } from './domain/service.js';`,
      `import { ${camel}Repository } from './repository.js';`,
      `import {`,
      `  ${camel}CreateInputSchema,`,
      `  ${camel}ListOutputSchema,`,
      `  ${camel}RecordSchema,`,
      `} from './schema.js';`,
      '',
      `export const ${camel}Router = router({`,
      '  list: publicProcedure',
      `    .use(requireResource('${slug}.list'))`,
      `    .output(${camel}ListOutputSchema)`,
      '    .query(({ ctx }) => {',
      `      return list${modelName}(${camel}Repository, ctx.user.tenantId);`,
      '    }),',
      '  create: publicProcedure',
      `    .use(requireResource('${slug}.create'))`,
      `    .input(${camel}CreateInputSchema)`,
      `    .output(${camel}RecordSchema)`,
      '    .mutation(({ ctx, input }) => {',
      `      return create${modelName}(${camel}Repository, ctx.user.tenantId, input);`,
      '    }),',
      '});',
      '',
    ].join('\n'),

    'router.test.ts': [
      "import { describe, it, expect, beforeEach, afterEach } from 'vitest';",
      `import { ${camel}Router } from './router.js';`,
      "import { createTestContext } from '../../test-utils.js';",
      "import { prisma } from 'db/client';",
      '',
      '// Roda só quando DATABASE_URL está setado — mesmo padrão de',
      '// `require-resource.test.ts` (Story 3.1): a lógica de cobertura É a query',
      '// relacional real do requireResource, um fake não provaria nada aqui.',
      '//',
      '// Module/Resource NÃO são criados aqui — já existem, inseridos pela migration',
      "// que `generate module '" +
        slug +
        "'` escreveu atomicamente (AD-6). Cobertura de",
      '// herança por ancestralidade (níveis múltiplos da árvore) já é testada uma vez',
      '// só, no middleware requireResource em si (Story 3.1) — não repetida aqui, é',
      '// lógica do middleware, não deste router.',
      'describe.skipIf(!process.env.DATABASE_URL)(',
      `  '${camel}Router (integração real, precisa de DATABASE_URL)',`,
      '  () => {',
      '    let tenantId: string;',
      '    let moduleId: string;',
      '    let listResourceId: string;',
      '    let createResourceId: string;',
      '    // Todo Tenant criado durante o teste (inclusive o `tenantB` do cenário de',
      '    // isolamento abaixo) — limpo no afterEach pra não acumular linhas órfãs no',
      '    // Postgres compartilhado do Laboratório Integrit (achado do retro do Épico 3:',
      '    // nenhum teste real deste projeto limpava o que criava, só confiava em nomes',
      '    // aleatorizados pra evitar colisão de unique constraint).',
      '    let createdTenantIds: string[];',
      '',
      '    async function cleanupTenant(id: string) {',
      '      // Ordem importa: RoleAssignment/Role/Group/User referenciam Tenant sem',
      '      // onDelete: Cascade (só RoleAssignment.user/group têm Cascade, pra User/Group,',
      '      // não pra Tenant) — apagar o Tenant direto violaria a FK. Module/Resource são',
      '      // globais (Story 3.1), nunca apagados aqui.',
      '      await prisma.roleAssignment.deleteMany({ where: { tenantId: id } });',
      '      await prisma.role.deleteMany({ where: { tenantId: id } });',
      '      await prisma.group.deleteMany({ where: { tenantId: id } });',
      '      await prisma.user.deleteMany({ where: { tenantId: id } });',
      '      await prisma.tenant.delete({ where: { id } });',
      '    }',
      '',
      '    beforeEach(async () => {',
      '      const tenant = await prisma.tenant.create({',
      '        data: { name: `tenant-${Date.now()}-${Math.random()}` },',
      '      });',
      '      tenantId = tenant.id;',
      '      createdTenantIds = [tenantId];',
      '',
      '      const mod = await prisma.module.findUniqueOrThrow({',
      `        where: { slug: '${slug}' },`,
      '      });',
      '      moduleId = mod.id;',
      '      const listResource = await prisma.resource.findUniqueOrThrow({',
      `        where: { name: '${slug}.list' },`,
      '      });',
      '      listResourceId = listResource.id;',
      '      const createResource = await prisma.resource.findUniqueOrThrow({',
      `        where: { name: '${slug}.create' },`,
      '      });',
      '      createResourceId = createResource.id;',
      '    });',
      '',
      '    afterEach(async () => {',
      '      for (const id of createdTenantIds) {',
      '        await cleanupTenant(id);',
      '      }',
      '    });',
      '',
      '    async function makeUser() {',
      '      return prisma.user.create({',
      '        data: {',
      '          tenantId,',
      '          email: `user-${Date.now()}-${Math.random()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '    }',
      '',
      '    async function grantRole(userId: string, resourceIds: string[]) {',
      '      const role = await prisma.role.create({',
      '        data: {',
      '          tenantId,',
      '          name: `role-${Date.now()}-${Math.random()}`,',
      '          resources: { connect: resourceIds.map((id) => ({ id })) },',
      '        },',
      '      });',
      '      await prisma.roleAssignment.create({',
      '        data: { tenantId, userId, roleId: role.id, targetModuleId: moduleId },',
      '      });',
      '    }',
      '',
      "    it('list sem RoleAssignment é negado (FORBIDDEN, default-deny — AD-7)', async () => {",
      '      const user = await makeUser();',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId, isAdmin: false },',
      '      });',
      '',
      `      await expect(${camel}Router.createCaller(ctx).list()).rejects.toMatchObject({`,
      "        code: 'FORBIDDEN',",
      '      });',
      '    });',
      '',
      "    it('list com RoleAssignment cobrindo list é permitido', async () => {",
      '      const user = await makeUser();',
      '      await grantRole(user.id, [listResourceId]);',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId, isAdmin: false },',
      '      });',
      '',
      `      await expect(${camel}Router.createCaller(ctx).list()).resolves.toEqual([]);`,
      '    });',
      '',
      "    it('create com RoleAssignment cobrindo só list (não create) continua negado pra create', async () => {",
      '      const user = await makeUser();',
      '      await grantRole(user.id, [listResourceId]);',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId, isAdmin: false },',
      '      });',
      '',
      '      await expect(',
      `        ${camel}Router.createCaller(ctx).create({ name: 'Teste' }),`,
      "      ).rejects.toMatchObject({ code: 'FORBIDDEN' });",
      '    });',
      '',
      "    it('create com RoleAssignment cobrindo create é permitido e persiste', async () => {",
      '      const user = await makeUser();',
      '      await grantRole(user.id, [createResourceId]);',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId, isAdmin: false },',
      '      });',
      '',
      '      const result = await ' +
        camel +
        'Router.createCaller(ctx).create({',
      "        name: 'Teste',",
      '      });',
      '',
      "      expect(result.name).toBe('Teste');",
      '    });',
      '',
      "    it('atribuição via Group (não direta no usuário) é permitida', async () => {",
      '      const user = await makeUser();',
      '      const group = await prisma.group.create({',
      '        data: {',
      '          tenantId,',
      '          name: `group-${Date.now()}-${Math.random()}`,',
      '          users: { connect: { id: user.id } },',
      '        },',
      '      });',
      '      const role = await prisma.role.create({',
      '        data: {',
      '          tenantId,',
      '          name: `role-group-${Date.now()}`,',
      '          resources: { connect: { id: listResourceId } },',
      '        },',
      '      });',
      '      await prisma.roleAssignment.create({',
      '        data: { tenantId, groupId: group.id, roleId: role.id, targetModuleId: moduleId },',
      '      });',
      '      const ctx = createTestContext({',
      '        user: { userId: user.id, tenantId, isAdmin: false },',
      '      });',
      '',
      `      await expect(${camel}Router.createCaller(ctx).list()).resolves.toEqual([]);`,
      '    });',
      '',
      "    it('isolamento real entre tenants — list() nunca retorna linha criada por outro tenant (AD-5)', async () => {",
      '      // Tenant A (da beforeEach) cria uma linha de verdade.',
      '      const userA = await makeUser();',
      '      await grantRole(userA.id, [createResourceId]);',
      '      const ctxA = createTestContext({',
      '        user: { userId: userA.id, tenantId, isAdmin: false },',
      '      });',
      `      await ${camel}Router.createCaller(ctxA).create({`,
      "        name: 'Linha do Tenant A',",
      '      });',
      '',
      '      // Tenant B: outra instância inteira, usando o MESMO Module/Resource',
      '      // globais (Story 3.1) — concede list pro próprio usuário.',
      '      const tenantB = await prisma.tenant.create({',
      '        data: { name: `tenant-b-${Date.now()}-${Math.random()}` },',
      '      });',
      '      createdTenantIds.push(tenantB.id);',
      '      const userB = await prisma.user.create({',
      '        data: {',
      '          tenantId: tenantB.id,',
      '          email: `user-b-${Date.now()}-${Math.random()}@example.com`,',
      "          passwordHash: 'irrelevante-neste-teste',",
      '        },',
      '      });',
      '      const roleB = await prisma.role.create({',
      '        data: {',
      '          tenantId: tenantB.id,',
      '          name: `role-b-${Date.now()}`,',
      '          resources: { connect: { id: listResourceId } },',
      '        },',
      '      });',
      '      await prisma.roleAssignment.create({',
      '        data: {',
      '          tenantId: tenantB.id,',
      '          userId: userB.id,',
      '          roleId: roleB.id,',
      '          targetModuleId: moduleId,',
      '        },',
      '      });',
      '      const ctxB = createTestContext({',
      '        user: { userId: userB.id, tenantId: tenantB.id, isAdmin: false },',
      '      });',
      '',
      `      await expect(${camel}Router.createCaller(ctxB).list()).resolves.toEqual(`,
      '        [],',
      '      );',
      '    });',
      '  },',
      ');',
      '',
    ].join('\n'),
  };
}
